//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.20 at 10:32:26 AM CEST 
//


package org.easysdi.proxy.policy;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import org.easysdi.proxy.policy.Attributes;
import org.easysdi.proxy.policy.AvailabilityPeriod;
import org.easysdi.proxy.policy.BBOXFilter;
import org.easysdi.proxy.policy.BoundingBox;
import org.easysdi.proxy.policy.Date;
import org.easysdi.proxy.policy.FeatureTypes;
import org.easysdi.proxy.policy.ImageSize;
import org.easysdi.proxy.policy.Layer;
import org.easysdi.proxy.policy.Layers;
import org.easysdi.proxy.policy.Maximum;
import org.easysdi.proxy.policy.Metadata;
import org.easysdi.proxy.policy.Minimum;
import org.easysdi.proxy.policy.Name;
import org.easysdi.proxy.policy.ObjectContexts;
import org.easysdi.proxy.policy.ObjectFactory;
import org.easysdi.proxy.policy.ObjectStatus;
import org.easysdi.proxy.policy.ObjectTypes;
import org.easysdi.proxy.policy.ObjectVersion;
import org.easysdi.proxy.policy.ObjectVisibilities;
import org.easysdi.proxy.policy.Operations;
import org.easysdi.proxy.policy.Policy;
import org.easysdi.proxy.policy.PolicySet;
import org.easysdi.proxy.policy.Server;
import org.easysdi.proxy.policy.Servers;
import org.easysdi.proxy.policy.Status;
import org.easysdi.proxy.policy.Subjects;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.easysdi.proxy.policy package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _From_QNAME = new QName("", "From");
    private final static QName _CRS_QNAME = new QName("", "CRS");
    private final static QName _Filter_QNAME = new QName("", "Filter");
    private final static QName _Mask_QNAME = new QName("", "Mask");
    private final static QName _IncludeHarvested_QNAME = new QName("", "IncludeHarvested");
    private final static QName _Height_QNAME = new QName("", "Height");
    private final static QName _Mode_QNAME = new QName("", "mode");
    private final static QName _Date_QNAME = new QName("", "Date");
    private final static QName _Prefix_QNAME = new QName("", "Prefix");
    private final static QName _User_QNAME = new QName("", "User");
    private final static QName _Namespace_QNAME = new QName("", "Namespace");
    private final static QName _Maxx_QNAME = new QName("", "maxx");
    private final static QName _To_QNAME = new QName("", "To");
    private final static QName _Operation_QNAME = new QName("", "Operation");
    private final static QName _Visibility_QNAME = new QName("", "Visibility");
    private final static QName _Miny_QNAME = new QName("", "miny");
    private final static QName _Maxy_QNAME = new QName("", "maxy");
    private final static QName _Width_QNAME = new QName("", "Width");
    private final static QName _GeographicFilter_QNAME = new QName("", "GeographicFilter");
    private final static QName _Url_QNAME = new QName("", "url");
    private final static QName _Minx_QNAME = new QName("", "minx");
    private final static QName _Name_QNAME = new QName("", "Name");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.easysdi.proxy.policy
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link ObjectStatus }
     * 
     */
    public ObjectStatus createObjectStatus() {
        return new ObjectStatus();
    }

    /**
     * Create an instance of {@link Maximum }
     * 
     */
    public Maximum createMaximum() {
        return new Maximum();
    }

    /**
     * Create an instance of {@link Policy }
     * 
     */
    public Policy createPolicy() {
        return new Policy();
    }

    /**
     * Create an instance of {@link ObjectContexts }
     * 
     */
    public ObjectContexts createObjectContexts() {
        return new ObjectContexts();
    }

    /**
     * Create an instance of {@link ObjectTypes }
     * 
     */
    public ObjectTypes createObjectTypes() {
        return new ObjectTypes();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link ObjectVisibilities }
     * 
     */
    public ObjectVisibilities createObjectVisibilities() {
        return new ObjectVisibilities();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link Operations }
     * 
     */
    public Operations createOperations() {
        return new Operations();
    }

    /**
     * Create an instance of {@link ImageSize }
     * 
     */
    public ImageSize createImageSize() {
        return new ImageSize();
    }

    /**
     * Create an instance of {@link PolicySet }
     * 
     */
    public PolicySet createPolicySet() {
        return new PolicySet();
    }

    /**
     * Create an instance of {@link AvailabilityPeriod }
     * 
     */
    public AvailabilityPeriod createAvailabilityPeriod() {
        return new AvailabilityPeriod();
    }

    /**
     * Create an instance of {@link Layers }
     * 
     */
    public Layers createLayers() {
        return new Layers();
    }

    /**
     * Create an instance of {@link Layer }
     * 
     */
    public Layer createLayer() {
        return new Layer();
    }

    /**
     * Create an instance of {@link FeatureTypes }
     * 
     */
    public FeatureTypes createFeatureTypes() {
        return new FeatureTypes();
    }

    /**
     * Create an instance of {@link ObjectVersion }
     * 
     */
    public ObjectVersion createObjectVersion() {
        return new ObjectVersion();
    }

    /**
     * Create an instance of {@link Attributes }
     * 
     */
    public Attributes createAttributes() {
        return new Attributes();
    }

    /**
     * Create an instance of {@link BoundingBox }
     * 
     */
    public BoundingBox createBoundingBox() {
        return new BoundingBox();
    }

    /**
     * Create an instance of {@link Servers }
     * 
     */
    public Servers createServers() {
        return new Servers();
    }

    /**
     * Create an instance of {@link Minimum }
     * 
     */
    public Minimum createMinimum() {
        return new Minimum();
    }

    /**
     * Create an instance of {@link Server }
     * 
     */
    public Server createServer() {
        return new Server();
    }

    /**
     * Create an instance of {@link BBOXFilter }
     * 
     */
    public BBOXFilter createBBOXFilter() {
        return new BBOXFilter();
    }

    /**
     * Create an instance of {@link Subjects }
     * 
     */
    public Subjects createSubjects() {
        return new Subjects();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Date }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "From")
    public JAXBElement<Date> createFrom(Date value) {
        return new JAXBElement<Date>(_From_QNAME, Date.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CRS")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCRS(String value) {
        return new JAXBElement<String>(_CRS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Filter")
    public JAXBElement<String> createFilter(String value) {
        return new JAXBElement<String>(_Filter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Mask")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMask(String value) {
        return new JAXBElement<String>(_Mask_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IncludeHarvested")
    public JAXBElement<Boolean> createIncludeHarvested(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeHarvested_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Height")
    public JAXBElement<BigInteger> createHeight(BigInteger value) {
        return new JAXBElement<BigInteger>(_Height_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMode(String value) {
        return new JAXBElement<String>(_Mode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Date")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<String>(_Date_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prefix")
    public JAXBElement<String> createPrefix(String value) {
        return new JAXBElement<String>(_Prefix_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "User")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUser(String value) {
        return new JAXBElement<String>(_User_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Namespace")
    public JAXBElement<String> createNamespace(String value) {
        return new JAXBElement<String>(_Namespace_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "maxx")
    public JAXBElement<BigInteger> createMaxx(BigInteger value) {
        return new JAXBElement<BigInteger>(_Maxx_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Date }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "To")
    public JAXBElement<Date> createTo(Date value) {
        return new JAXBElement<Date>(_To_QNAME, Date.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Name }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Operation")
    public JAXBElement<Name> createOperation(Name value) {
        return new JAXBElement<Name>(_Operation_QNAME, Name.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Visibility")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createVisibility(String value) {
        return new JAXBElement<String>(_Visibility_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "miny")
    public JAXBElement<BigInteger> createMiny(BigInteger value) {
        return new JAXBElement<BigInteger>(_Miny_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "maxy")
    public JAXBElement<BigInteger> createMaxy(BigInteger value) {
        return new JAXBElement<BigInteger>(_Maxy_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Width")
    public JAXBElement<BigInteger> createWidth(BigInteger value) {
        return new JAXBElement<BigInteger>(_Width_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GeographicFilter")
    public JAXBElement<String> createGeographicFilter(String value) {
        return new JAXBElement<String>(_GeographicFilter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "url")
    public JAXBElement<String> createUrl(String value) {
        return new JAXBElement<String>(_Url_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "minx")
    public JAXBElement<BigInteger> createMinx(BigInteger value) {
        return new JAXBElement<BigInteger>(_Minx_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

}
