//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.13 at 04:39:39 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.interlis.ch/INTERLIS2.2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ch.interlis.interlis2.GM03V18;
