package org.easysdi.proxy.domain;

// Generated Oct 3, 2013 1:38:11 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;

/**
 * SdiPolicyOrganism generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
@FilterDef(name="entityState")
@Filter(name = "entityState",condition="enabled = 1")
public class SdiPolicyCategory implements java.io.Serializable {

	private Integer Id;
	private SdiCategory sdiCategory;
	private SdiPolicy sdiPolicy;

	public SdiPolicyCategory() {
	}

	public SdiPolicyCategory(SdiCategory sdiCategory,
			SdiPolicy sdiPolicy) {
		this.sdiCategory = sdiCategory;
		this.sdiPolicy = sdiPolicy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public SdiCategory getSdiCategory() {
		return this.sdiCategory;
	}

	public void setSdiCategory(SdiCategory sdiCategory) {
		this.sdiCategory = sdiCategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "policy_id", nullable = false)
	public SdiPolicy getSdiPolicy() {
		return this.sdiPolicy;
	}

	public void setSdiPolicy(SdiPolicy sdiPolicy) {
		this.sdiPolicy = sdiPolicy;
	}

}
