
OpenLayers.Protocol.WFS.Custom=OpenLayers.Class(OpenLayers.Protocol.WFS.v1,{initialize:function(options){this.readModeMulti=false;OpenLayers.Protocol.WFS.v1.prototype.initialize.apply(this,[options]);},handleRead:function(response,options){if(options.callback){var request=response.priv;if(request.status>=200&&request.status<300){response.features=[];var idx=0;for(var geom in SData.searchPrecisions){var p=SData.searchPrecisions[geom];if(p.required){this.format.geometryIndex=idx;var features=this.parseFeatures(request);response.features.push(features);idx++;}}
if(idx===0)
{this.format.geometryIndex=idx;var features=this.parseFeatures(request);response.features.push(features);}
response.code=OpenLayers.Protocol.Response.SUCCESS;}else{response.code=OpenLayers.Protocol.Response.FAILURE;}
options.callback.call(options.scope,response);};},CLASS_NAME:"OpenLayers.Protocol.WFS.Custom"});OpenLayers.Format.GML.custom=OpenLayers.Class(OpenLayers.Format.GML.v2,{initialize:function(options){OpenLayers.Format.GML.v2.prototype.initialize.apply(this,[options]);},readers:{"gml":OpenLayers.Util.applyDefaults({"boundedBy":function(node,obj){var container={};this.readChildNodes(node,container);if(container.components&&container.components.length>0){obj.bounds=container.components[this.geometryIndex];}},"MultiPoint":function(node,container){var obj={components:[]};this.readChildNodes(node,obj);container.components.push(new OpenLayers.Geometry.MultiPoint(obj.components));},"MultiLineString":function(node,container){var obj={components:[]};this.readChildNodes(node,obj);container.components.push(new OpenLayers.Geometry.MultiLineString(obj.components));},"LinearRing":function(node,obj){var container={};this.readChildNodes(node,container);if(typeof obj.components=="undefined")
obj.components=[];obj.components.push(new OpenLayers.Geometry.LinearRing(container.points));},"MultiPolygon":function(node,container){var obj={components:[]};this.readChildNodes(node,obj);container.components.push(new OpenLayers.Geometry.MultiPolygon(obj.components));}},OpenLayers.Format.GML.v2.prototype.readers["gml"]),"feature":OpenLayers.Util.applyDefaults({"_typeName":function(node,obj){var container={components:[],attributes:{}};this.readChildNodes(node,container);var attrs=OpenLayers.Util.applyDefaults({},container.attributes);if(container.name){attrs.name=container.name;}
var feature=new OpenLayers.Feature.Vector(container.components[this.geometryIndex],attrs);if(!this.singleFeatureType){feature.type=node.nodeName.split(":").pop();feature.namespace=node.namespaceURI;}
var fid=node.getAttribute("fid")||this.getAttributeNS(node,this.namespaces["gml"],"id");if(fid){feature.fid=fid;}
if(this.internalProjection&&this.externalProjection&&feature.geometry){feature.geometry.transform(this.externalProjection,this.internalProjection);}
if(container.bounds){feature.geometry.bounds=container.bounds;}
obj.features.push(feature);}},OpenLayers.Format.GML.Base.prototype.readers["feature"]),"wfs":OpenLayers.Format.GML.Base.prototype.readers["wfs"]},CLASS_NAME:"OpenLayers.Format.GML.custom"});OpenLayers.Format.WFST.Custom=OpenLayers.Class(OpenLayers.Format.WFST.v1_0_0,{initialize:function(options){this.geometryIndex=0;OpenLayers.Format.WFST.v1_0_0.prototype.initialize.apply(this,[options]);},readers:{"wfs":OpenLayers.Format.WFST.v1_0_0.prototype.readers["wfs"],"gml":OpenLayers.Format.GML.custom.prototype.readers["gml"],"feature":OpenLayers.Format.GML.custom.prototype.readers["feature"],"ogc":OpenLayers.Format.Filter.v1_0_0.prototype.readers["ogc"]},CLASS_NAME:"OpenLayers.Format.WFST.Custom"});OpenLayers.Strategy.FixedMultiLayer=OpenLayers.Class(OpenLayers.Strategy.Fixed,{initialize:function(options){this.layers=[];this.protocol=options.protocol;options.autoActivate=false;OpenLayers.Strategy.Fixed.prototype.initialize.apply(this,[options]);},destroy:function(){OpenLayers.Strategy.Fixed.prototype.destroy.apply(this,arguments);},setLayer:function(layer){this.layers.push(layer);},activate:function(){if(OpenLayers.Strategy.prototype.activate.apply(this,arguments)){Ext.each(this.layers,function(item){item.events.on({"refresh":this.load,scope:this});},this);this.load();return true;}
return false;},deactivate:function(){var deactivated=OpenLayers.Strategy.prototype.deactivate.call(this);if(deactivated){this.layer.events.un({"refresh":this.load,"visibilitychanged":this.load,scope:this});}
return deactivated;},load:function(options){Ext.each(this.layers,function(item){item.events.triggerEvent("loadstart");});if(typeof this.protocol!="undefined"){this.protocol.read(OpenLayers.Util.applyDefaults({callback:this.merge,scope:this},options));}},merge:function(resp){var featuresArr=resp.features;var geomAttrs={};var idx=0;for(var geom in SData.searchPrecisions){if(SData.searchPrecisions[geom].required){geomAttrs[geom]={index:idx};idx++;}}
if(idx===0)
{geomAttrs[SData.searchLayer.geometryName]={index:idx};}
Ext.each(this.layers,function(layer,i){layer.destroyFeatures();layer.addFeatures(featuresArr[geomAttrs[layer.geometryName].index]);layer.events.triggerEvent("loadend");},this);},CLASS_NAME:"OpenLayers.Strategy.FixedMultiLayer"});