//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.13 at 04:39:39 PM CET 
//


package ch.interlis.interlis2.GM03V18;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GM03Core.Core.CI_OnlineResource complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GM03Core.Core.CI_OnlineResource">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="protocol" type="{http://www.interlis.ch/INTERLIS2.2}GM03Core.Core.CharacterString" minOccurs="0"/>
 *         &lt;element name="applicationProfile" type="{http://www.interlis.ch/INTERLIS2.2}GM03Core.Core.CharacterString" minOccurs="0"/>
 *         &lt;element name="function" type="{http://www.interlis.ch/INTERLIS2.2}GM03Core.Core.CI_OnLineFunctionCode" minOccurs="0"/>
 *         &lt;element name="description" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GM03Core.Core.PT_FreeText" type="{http://www.interlis.ch/INTERLIS2.2}GM03Core.Core.PT_FreeText"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="name" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GM03Core.Core.PT_FreeText" type="{http://www.interlis.ch/INTERLIS2.2}GM03Core.Core.PT_FreeText"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="linkage">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GM03Core.Core.PT_FreeURL" type="{http://www.interlis.ch/INTERLIS2.2}GM03Core.Core.PT_FreeURL"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MD_DigitalTransferOptions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="REF" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
 *                 &lt;attribute name="EXTREF" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
 *                 &lt;attribute name="BID" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
 *                 &lt;attribute name="NEXT_TID" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MD_MetadataExtensionInformation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="REF" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
 *                 &lt;attribute name="EXTREF" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
 *                 &lt;attribute name="BID" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
 *                 &lt;attribute name="NEXT_TID" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GM03Core.Core.CI_OnlineResource", propOrder = {
    "protocol",
    "applicationProfile",
    "function",
    "description",
    "name",
    "linkage",
    "mdDigitalTransferOptions",
    "mdMetadataExtensionInformation"
})
@XmlSeeAlso({
    ch.interlis.interlis2.GM03V18.GM03ComprehensiveComprehensive.GM03CoreCoreCIOnlineResource.class,
    ch.interlis.interlis2.GM03V18.GM03CoreCore.GM03CoreCoreCIOnlineResource.class
})
public class GM03CoreCoreCIOnlineResource {

    protected String protocol;
    protected String applicationProfile;
    protected GM03CoreCoreCIOnLineFunctionCode function;
    protected GM03CoreCoreCIOnlineResource.Description description;
    protected GM03CoreCoreCIOnlineResource.Name name;
    @XmlElement(required = true)
    protected GM03CoreCoreCIOnlineResource.Linkage linkage;
    @XmlElement(name = "MD_DigitalTransferOptions")
    protected GM03CoreCoreCIOnlineResource.MDDigitalTransferOptions mdDigitalTransferOptions;
    @XmlElement(name = "MD_MetadataExtensionInformation")
    protected GM03CoreCoreCIOnlineResource.MDMetadataExtensionInformation mdMetadataExtensionInformation;

    /**
     * Gets the value of the protocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocol(String value) {
        this.protocol = value;
    }

    /**
     * Gets the value of the applicationProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationProfile() {
        return applicationProfile;
    }

    /**
     * Sets the value of the applicationProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationProfile(String value) {
        this.applicationProfile = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link GM03CoreCoreCIOnLineFunctionCode }
     *     
     */
    public GM03CoreCoreCIOnLineFunctionCode getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link GM03CoreCoreCIOnLineFunctionCode }
     *     
     */
    public void setFunction(GM03CoreCoreCIOnLineFunctionCode value) {
        this.function = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link GM03CoreCoreCIOnlineResource.Description }
     *     
     */
    public GM03CoreCoreCIOnlineResource.Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link GM03CoreCoreCIOnlineResource.Description }
     *     
     */
    public void setDescription(GM03CoreCoreCIOnlineResource.Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link GM03CoreCoreCIOnlineResource.Name }
     *     
     */
    public GM03CoreCoreCIOnlineResource.Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link GM03CoreCoreCIOnlineResource.Name }
     *     
     */
    public void setName(GM03CoreCoreCIOnlineResource.Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the linkage property.
     * 
     * @return
     *     possible object is
     *     {@link GM03CoreCoreCIOnlineResource.Linkage }
     *     
     */
    public GM03CoreCoreCIOnlineResource.Linkage getLinkage() {
        return linkage;
    }

    /**
     * Sets the value of the linkage property.
     * 
     * @param value
     *     allowed object is
     *     {@link GM03CoreCoreCIOnlineResource.Linkage }
     *     
     */
    public void setLinkage(GM03CoreCoreCIOnlineResource.Linkage value) {
        this.linkage = value;
    }

    /**
     * Gets the value of the mdDigitalTransferOptions property.
     * 
     * @return
     *     possible object is
     *     {@link GM03CoreCoreCIOnlineResource.MDDigitalTransferOptions }
     *     
     */
    public GM03CoreCoreCIOnlineResource.MDDigitalTransferOptions getMDDigitalTransferOptions() {
        return mdDigitalTransferOptions;
    }

    /**
     * Sets the value of the mdDigitalTransferOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link GM03CoreCoreCIOnlineResource.MDDigitalTransferOptions }
     *     
     */
    public void setMDDigitalTransferOptions(GM03CoreCoreCIOnlineResource.MDDigitalTransferOptions value) {
        this.mdDigitalTransferOptions = value;
    }

    /**
     * Gets the value of the mdMetadataExtensionInformation property.
     * 
     * @return
     *     possible object is
     *     {@link GM03CoreCoreCIOnlineResource.MDMetadataExtensionInformation }
     *     
     */
    public GM03CoreCoreCIOnlineResource.MDMetadataExtensionInformation getMDMetadataExtensionInformation() {
        return mdMetadataExtensionInformation;
    }

    /**
     * Sets the value of the mdMetadataExtensionInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link GM03CoreCoreCIOnlineResource.MDMetadataExtensionInformation }
     *     
     */
    public void setMDMetadataExtensionInformation(GM03CoreCoreCIOnlineResource.MDMetadataExtensionInformation value) {
        this.mdMetadataExtensionInformation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GM03Core.Core.PT_FreeText" type="{http://www.interlis.ch/INTERLIS2.2}GM03Core.Core.PT_FreeText"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gm03CoreCorePTFreeText"
    })
    public static class Description {

        @XmlElement(name = "GM03Core.Core.PT_FreeText", required = true)
        protected GM03CoreCorePTFreeText gm03CoreCorePTFreeText;

        /**
         * Gets the value of the gm03CoreCorePTFreeText property.
         * 
         * @return
         *     possible object is
         *     {@link GM03CoreCorePTFreeText }
         *     
         */
        public GM03CoreCorePTFreeText getGM03CoreCorePTFreeText() {
            return gm03CoreCorePTFreeText;
        }

        /**
         * Sets the value of the gm03CoreCorePTFreeText property.
         * 
         * @param value
         *     allowed object is
         *     {@link GM03CoreCorePTFreeText }
         *     
         */
        public void setGM03CoreCorePTFreeText(GM03CoreCorePTFreeText value) {
            this.gm03CoreCorePTFreeText = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GM03Core.Core.PT_FreeURL" type="{http://www.interlis.ch/INTERLIS2.2}GM03Core.Core.PT_FreeURL"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gm03CoreCorePTFreeURL"
    })
    public static class Linkage {

        @XmlElement(name = "GM03Core.Core.PT_FreeURL", required = true)
        protected GM03CoreCorePTFreeURL gm03CoreCorePTFreeURL;

        /**
         * Gets the value of the gm03CoreCorePTFreeURL property.
         * 
         * @return
         *     possible object is
         *     {@link GM03CoreCorePTFreeURL }
         *     
         */
        public GM03CoreCorePTFreeURL getGM03CoreCorePTFreeURL() {
            return gm03CoreCorePTFreeURL;
        }

        /**
         * Sets the value of the gm03CoreCorePTFreeURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link GM03CoreCorePTFreeURL }
         *     
         */
        public void setGM03CoreCorePTFreeURL(GM03CoreCorePTFreeURL value) {
            this.gm03CoreCorePTFreeURL = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="REF" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
     *       &lt;attribute name="EXTREF" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
     *       &lt;attribute name="BID" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
     *       &lt;attribute name="NEXT_TID" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class MDDigitalTransferOptions {

        @XmlAttribute(name = "REF")
        protected String ref;
        @XmlAttribute(name = "EXTREF")
        protected String extref;
        @XmlAttribute(name = "BID")
        protected String bid;
        @XmlAttribute(name = "NEXT_TID")
        protected String nexttid;

        /**
         * Gets the value of the ref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getREF() {
            return ref;
        }

        /**
         * Sets the value of the ref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setREF(String value) {
            this.ref = value;
        }

        /**
         * Gets the value of the extref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEXTREF() {
            return extref;
        }

        /**
         * Sets the value of the extref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEXTREF(String value) {
            this.extref = value;
        }

        /**
         * Gets the value of the bid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBID() {
            return bid;
        }

        /**
         * Sets the value of the bid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBID(String value) {
            this.bid = value;
        }

        /**
         * Gets the value of the nexttid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNEXTTID() {
            return nexttid;
        }

        /**
         * Sets the value of the nexttid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNEXTTID(String value) {
            this.nexttid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="REF" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
     *       &lt;attribute name="EXTREF" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
     *       &lt;attribute name="BID" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
     *       &lt;attribute name="NEXT_TID" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class MDMetadataExtensionInformation {

        @XmlAttribute(name = "REF")
        protected String ref;
        @XmlAttribute(name = "EXTREF")
        protected String extref;
        @XmlAttribute(name = "BID")
        protected String bid;
        @XmlAttribute(name = "NEXT_TID")
        protected String nexttid;

        /**
         * Gets the value of the ref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getREF() {
            return ref;
        }

        /**
         * Sets the value of the ref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setREF(String value) {
            this.ref = value;
        }

        /**
         * Gets the value of the extref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEXTREF() {
            return extref;
        }

        /**
         * Sets the value of the extref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEXTREF(String value) {
            this.extref = value;
        }

        /**
         * Gets the value of the bid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBID() {
            return bid;
        }

        /**
         * Sets the value of the bid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBID(String value) {
            this.bid = value;
        }

        /**
         * Gets the value of the nexttid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNEXTTID() {
            return nexttid;
        }

        /**
         * Sets the value of the nexttid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNEXTTID(String value) {
            this.nexttid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GM03Core.Core.PT_FreeText" type="{http://www.interlis.ch/INTERLIS2.2}GM03Core.Core.PT_FreeText"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gm03CoreCorePTFreeText"
    })
    public static class Name {

        @XmlElement(name = "GM03Core.Core.PT_FreeText", required = true)
        protected GM03CoreCorePTFreeText gm03CoreCorePTFreeText;

        /**
         * Gets the value of the gm03CoreCorePTFreeText property.
         * 
         * @return
         *     possible object is
         *     {@link GM03CoreCorePTFreeText }
         *     
         */
        public GM03CoreCorePTFreeText getGM03CoreCorePTFreeText() {
            return gm03CoreCorePTFreeText;
        }

        /**
         * Sets the value of the gm03CoreCorePTFreeText property.
         * 
         * @param value
         *     allowed object is
         *     {@link GM03CoreCorePTFreeText }
         *     
         */
        public void setGM03CoreCorePTFreeText(GM03CoreCorePTFreeText value) {
            this.gm03CoreCorePTFreeText = value;
        }

    }

}
