//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.13 at 04:39:39 PM CET 
//


package ch.interlis.interlis2.GM03V18;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GM03Comprehensive.Comprehensive.formatDistributordistributorFormat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GM03Comprehensive.Comprehensive.formatDistributordistributorFormat">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="formatDistributor" type="{http://www.interlis.ch/INTERLIS2.2}RoleType"/>
 *         &lt;element name="distributorFormat" type="{http://www.interlis.ch/INTERLIS2.2}RoleType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GM03Comprehensive.Comprehensive.formatDistributordistributorFormat", propOrder = {
    "formatDistributor",
    "distributorFormat"
})
@XmlSeeAlso({
    ch.interlis.interlis2.GM03V18.GM03ComprehensiveComprehensive.GM03ComprehensiveComprehensiveFormatDistributordistributorFormat.class
})
public class GM03ComprehensiveComprehensiveFormatDistributordistributorFormat {

    @XmlElement(required = true)
    protected RoleType formatDistributor;
    @XmlElement(required = true)
    protected RoleType distributorFormat;

    /**
     * Gets the value of the formatDistributor property.
     * 
     * @return
     *     possible object is
     *     {@link RoleType }
     *     
     */
    public RoleType getFormatDistributor() {
        return formatDistributor;
    }

    /**
     * Sets the value of the formatDistributor property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleType }
     *     
     */
    public void setFormatDistributor(RoleType value) {
        this.formatDistributor = value;
    }

    /**
     * Gets the value of the distributorFormat property.
     * 
     * @return
     *     possible object is
     *     {@link RoleType }
     *     
     */
    public RoleType getDistributorFormat() {
        return distributorFormat;
    }

    /**
     * Sets the value of the distributorFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleType }
     *     
     */
    public void setDistributorFormat(RoleType value) {
        this.distributorFormat = value;
    }

}
