//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.13 at 09:48:29 AM CET 
//


package net.opengis.gml.v311;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class Surface2
    extends JAXBElement<SurfaceType>
{

    protected final static QName NAME = new QName("http://www.opengis.net/gml", "Surface");

    public Surface2(SurfaceType value) {
        super(NAME, ((Class) SurfaceType.class), null, value);
    }

}
