<?php
/**
* @version     3.3.0
* @package     com_easysdi_core
* @copyright   Copyright (C) 2013. All rights reserved.
* @license     GNU General Public License version 3 or later; see LICENSE.txt
* @author      EasySDI Community <contact@easysdi.org> - http://www.easysdi.org
*/

defined('_JEXEC') or die( 'Restricted access' );

jimport('joomla.plugin.plugin');

if(!defined('DS')) {
	define( 'DS', DIRECTORY_SEPARATOR );
}

class plgUserEasysdi extends JPlugin {

	public function __construct(& $subject, $config)
	{
		parent::__construct($subject, $config);
		$this->loadLanguage();
	}

	/**
	 * Utility method to check if an easysdi account is linked to the Joomla account to delete.
	 *
	 * @param	array		$user		Holds the Joomla user data.
	 *
	 * @return	void
	 * @since	EasySDI 3.0.0
	 */
	function onUserBeforeDelete($user)
	{
		// ensure the user id is really an int
		$user_id = (int)$user['id'];

		// Load user_easysdi plugin language (not done automatically).
		$lang = JFactory::getLanguage();
		$lang->load('plg_user_easysdi', JPATH_ADMINISTRATOR);
		
		if (empty($user_id)) {
			JError::raiseWarning(41, JText::_('PLG_EASYSDIUSER_ERR_INVALID_USER'));
			return false;
		}

		$dbo = JFactory::getDBO();
		$dbo->setQuery('SELECT id FROM #__sdi_user WHERE user_id = '. $user_id );
		$id = $dbo->loadResult();
		
		if($id){
			JError::raiseWarning(41, JText::_('PLG_EASYSDIUSER_ERR_CANT_DELETE'));
			return false;
		}
	}

	/**
	 * Utility method to create an easysdi user after a joomla user was created.
	 *
	 * @param	array		$user		Holds the new user data.
	 * @param	boolean		$isnew		True if a new user is stored.
	 * @param	boolean		$success	True if user was succesfully stored in the database.
	 * @param	string		$msg		Message.
	 *
	 * @return	void
	 * @since	EasySDI 3.0.0
	 */
	function onUserAfterSave($user, $isnew, $success, $msg)
	{
		if(!$success) {
			return false; // if the user wasn't stored we don't create an easysdi user
		}
	
		if(!$isnew) {
			return false; // if the user isn't new we don't create an easysdi user
		}
	
		// ensure the user id is really an int
		$user_id = (int)$user['id'];
		
		// Load user_easysdi plugin language (not done automatically).
		if (empty($user_id)) {
			JError::raiseWarning(41, JText::_('PLG_EASYSDIUSER_ERR_INVALID_USER'));
			return false;
		}

		$dbo = JFactory::getDBO();
		
		//Get default user
		$params = JComponentHelper::getParams('com_easysdi_contact');
		$defaultaccount_id = $params->get( 'defaultaccount', null );
		$dbo->setQuery('SELECT * FROM #__sdi_user WHERE user_id = '. $defaultaccount_id );
		$defaultaccount = $dbo->loadObject();
		
		if (!$defaultaccount) {
			JError::raiseWarning(41, JText::_('PLG_EASYSDIUSER_ERR_FAILED_LOAD_USER'));
			return false; 
		}
		//Create new EasySDI User account
		JTable::addIncludePath(JPATH_ADMINISTRATOR.DS.'components'.DS.'com_easysdi_contact'.DS.'tables');
		$newaccount = JTable::getInstance('user', 'easysdi_contactTable');	
		
		if (!$newaccount) {
			JError::raiseWarning(41, JText::_('PLG_EASYSDIUSER_ERR_FAILED_INSTANTIATE'));
			return false;
		}
		
		$newaccount->user_id 						= $user_id;
		$newaccount->catid 							= $defaultaccount->catid;
		$newaccount->params 						= $defaultaccount->params;
		$newaccount->access 						= $defaultaccount->access;
		$newaccount->notificationrequesttreatment 	= $defaultaccount->notificationrequesttreatment;
		//Assets are automatically generated by the frameweork 
		//Check function sets the ordering
		$newaccount->check();
		$result = $newaccount->store();
		
		if (!(isset($result)) || !$result) {
			JError::raiseWarning(41, JText::_('PLG_EASYSDIUSER_ERR_FAILED_CREATE'));
			return false;
		}
		
		//Set the state of the new EasySDI account to unpublish
		$newaccount->publish(null, 0);
	}
}
