
Ext.namespace("EasySDI_Map");EasySDI_Map.SearchManager=function(searchPanel,viewPort,mapPanel,precisionTree){this.searchPanel=searchPanel;this.viewPort=viewPort;this.mapPanel=mapPanel;this.precisionTree=precisionTree;this.searchBars=[];};EasySDI_Map.SearchManager.prototype.doSearch=function(options){Ext.Msg.show({title:EasySDI_Map.lang.getLocal('Please_Wait')+'...',msg:EasySDI_Map.lang.getLocal('SM_LOADING_MAP'),icon:'msg-wait'});this._cleanup(options.searchBar,true,true);var featureType=SData.searchLayer.featureType;if(typeof options.switchAccess!="undefined"){featureType=featureType.replace(/private|public/,options.switchAccess);options.searchBar.switchAccess=options.switchAccess;}else{options.switchAccess=undefined;}
if(componentParams.WMSFilterSupport=='true'){var layers=this.mapPanel.addWmsLayerSet(featureType,options.searchBar.filter,options.searchBar.layerStyle,options.searchBar.barIdx);options.searchBar.wfsLoaded=false;options.searchBar.layers=layers;if(!rwg.gridPanel.collapsed){this.enableWfsSearch(options.searchBar);}else{this.trigger('refreshLegend');}}else{var layers=[];options.searchBar.wfsLoaded=false;options.searchBar.layers=layers;this.enableWfsSearch(options.searchBar);}};EasySDI_Map.SearchManager.prototype.enableWfsSearch=function(searchBar){if(typeof searchBar=="undefined"){Ext.each(this.searchBars,function(item){this.runSingleWfsSearch(item.searchBar);},this);}else{this.runSingleWfsSearch(searchBar);}
this.trigger('refreshLegend');};EasySDI_Map.SearchManager.prototype.runSingleWfsSearch=function(searchBar){Ext.Msg.show({title:EasySDI_Map.lang.getLocal('Please_Wait')+'...',msg:EasySDI_Map.lang.getLocal('SM_LOADING_SEARCH'),icon:'msg-wait'});this.doWfsSearch(searchBar);};EasySDI_Map.SearchManager.prototype.doWfsSearch=function(searchBar){if(SData.searchLayer){var propertyNames=this._getPropertyNames(SData.searchLayer.featureType+'Cols');if(searchBar.wfsLoaded){this._cleanup(searchBar,false,true);}
var protocol,layers,filter;var featureType=SData.searchLayer.featureType.replace('{geom}','');if(typeof searchBar.switchAccess!="undefined"){featureType=featureType.replace(/private|public/,searchBar.switchAccess);}
filter=searchBar.filter.clone();if(!filter.filters){filter.filters=[];}
filter.filters.push(new OpenLayers.Filter.Spatial({type:OpenLayers.Filter.Spatial.BBOX,property:SData.searchLayer.geometryName,value:rwg.mapPanel.map.getExtent()}));protocol=new OpenLayers.Protocol.WFS.Custom({url:componentParams.proxiedPubWfsUrl,featureNS:componentParams.pubFeatureNS,featurePrefix:componentParams.pubFeaturePrefix,featureType:featureType,filter:filter,srsName:componentParams.projection,version:componentParams.pubWfsVersion,propertyNames:propertyNames,maxFeatures:componentParams.maxFeatures,format:new OpenLayers.Format.WFST.Custom({featureType:featureType,featureNS:componentParams.pubFeatureNS,featurePrefix:componentParams.pubFeaturePrefix,geometryName:SData.searchLayer.geometryName,srsName:componentParams.projection})});layers=this.mapPanel.addWfsFeatureLayerSet(protocol);searchBar.layers=searchBar.layers.concat(layers);this.viewPort.gridPanel.addSearch(protocol,layers,this.mapPanel.selectFeatureCtrl,searchBar);searchBar.wfsLoaded=true;}};EasySDI_Map.SearchManager.prototype._getPropertyNames=function(stateName){var props=[];for(var geom in SData.searchPrecisions){var p=SData.searchPrecisions[geom];if(p.required){props.push(geom);}}
if(props.length===0){props.push(SData.searchLayer.geometryName);}
props.push(componentParams.featureIdAttribute);var visibleCols=Ext.state.Manager.get(stateName,null);if(visibleCols===null){visibleCols=SData.defaultAttrs[SData.searchLayer.featureType.replace('{geom}','')];}
Ext.each(SData.attrs[SData.searchLayer.featureType.replace('{geom}','')],function(attr){if((visibleCols.indexOf(attr.name)!=-1||attr.visible===false)&&attr.name!=componentParams.featureIdAttribute){props.push(attr.name);}});return props;};EasySDI_Map.SearchManager.prototype._cleanup=function(searchBar,removeWms,removeWfs){if(typeof removeWms=="undefined"){removeWms=true;}
if(typeof removeWfs=="undefined"){removeWfs=true;}
if(removeWfs){this._killGrids(searchBar);}
this.mapPanel.removeLayers(searchBar.layers,removeWms,removeWfs);for(var i=searchBar.layers.length-1;i>=0;i--){if((removeWms&&searchBar.layers[i].CLASS_NAME=="OpenLayers.Layer.WMS")||(removeWfs&&searchBar.layers[i].CLASS_NAME=="OpenLayers.Layer.Vector")){searchBar.layers.splice(i,1);}}};EasySDI_Map.SearchManager.prototype._killGrids=function(searchBar){if(this.viewPort.gridPanel.tabPanel!==null){Ext.each(searchBar.distinctGrids,function(grid){this.viewPort.gridPanel.tabPanel.remove(grid);grid.destroy();},this);searchBar.distinctGrids=[];if(searchBar.featureGrid!==null){this.viewPort.gridPanel.tabPanel.remove(searchBar.featureGrid);searchBar.featureGrid.destroy();searchBar.featureGrid=null;}
if(searchBar.selectionGrid!==null){this.viewPort.gridPanel.tabPanel.remove(searchBar.selectionGrid);searchBar.selectionGrid.destroy();searchBar.selectionGrid=null;}
var gridPanel=this.viewPort.gridPanel;if(gridPanel.tabPanel.items.getCount()===0){gridPanel.remove(gridPanel.tabPanel);gridPanel.tabPanel.destroy();gridPanel.tabPanel=null;}}};EasySDI_Map.SearchManager.prototype.addSearchBar=function(idx){var searchBar=this.searchPanel.getNewSearchBar(this,idx);if(idx===null){this.searchBars.push({searchBar:searchBar,featureSelector:null});}else{this.searchBars.splice(idx,0,{searchBar:searchBar,featureSelector:null});}
this.viewPort.doLayout();this.setBtnState();};EasySDI_Map.SearchManager.prototype.removeSearchBar=function(searchBar){var toDelete;Ext.each(this.searchBars,function(item,index){if(item.searchBar===searchBar){toDelete=index;}});searchBar.collapse();this.searchPanel.remove(searchBar,true);this.searchBars.splice(toDelete,1);this._cleanup(searchBar);searchBar.destroy();this.setBtnState();this.trigger('refreshLegend');return toDelete;};EasySDI_Map.SearchManager.prototype.clearSearchBar=function(searchBar){var idx=this.removeSearchBar(searchBar);this.addSearchBar(idx);this.trigger('refreshLegend');this.trigger('hideFilterPanel');};EasySDI_Map.SearchManager.prototype.setBtnState=function(){Ext.each(this.searchBars,function(item,index){item.searchBar.addButton.setVisible(index==this.searchBars.length-1&&this.searchBars.length<componentParams.maxSearchBars);item.searchBar.removeButton.setVisible(this.searchBars.length>1);},this);};Ext.mixin(EasySDI_Map.SearchManager,EasySDI_Map.TriggerManager);