//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.07 at 04:52:23 PM CET 
//


package ch.geocat._2003._05.gateway.gm03small;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ch.geocat._2003._05.gateway.gml.PolygonType;


/**
 * <p>Java class for MD_MetadataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MD_MetadataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fileIdentifier" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}optionalString" minOccurs="0"/>
 *         &lt;element name="dateStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="dataSetURI" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}optionalString" minOccurs="0"/>
 *         &lt;element name="metadataSetURI" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}optionalString" minOccurs="0"/>
 *         &lt;element name="identificationInfo" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="language" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}LanguageCodeISO" maxOccurs="unbounded"/>
 *                   &lt;element name="purpose" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}optionalPT_FreeText" minOccurs="0"/>
 *                   &lt;element name="topicCategory" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}optionalTopicCategory" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="abstract" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText"/>
 *                   &lt;element name="citation">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="title" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText"/>
 *                             &lt;element name="date" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="date">
 *                                         &lt;simpleType>
 *                                           &lt;union memberTypes=" {http://www.geocat.ch/2003/05/gateway/GM03Small}NotAvailable {http://www.w3.org/2001/XMLSchema}date">
 *                                           &lt;/union>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="dateType" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}CI_DateTypeCode"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="pointOfContact" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="role" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}CI_RoleCode" maxOccurs="unbounded"/>
 *                             &lt;element name="individualName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="positionName" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText" minOccurs="0"/>
 *                             &lt;element name="organisationName" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attGroup ref="{http://www.geocat.ch/2003/05/gateway/GM03Small}notSupportedGroup"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="descriptiveKeywords" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="keyword" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                           &lt;attGroup ref="{http://www.geocat.ch/2003/05/gateway/GM03Small}notSupportedGroup"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="extent" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="description" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}optionalPT_FreeText" minOccurs="0"/>
 *                             &lt;element name="geographicElement" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{http://www.geocat.ch/2003/05/gateway/GML}Polygon" minOccurs="0"/>
 *                                       &lt;element name="westBoundLongitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                                       &lt;element name="eastBoundLongitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                                       &lt;element name="southBoundLatitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                                       &lt;element name="northBoundLatitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                                       &lt;element name="geographicIdentifier" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="code" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText"/>
 *                                               &lt;/sequence>
 *                                               &lt;attGroup ref="{http://www.geocat.ch/2003/05/gateway/GM03Small}notSupportedGroup"/>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attGroup ref="{http://www.geocat.ch/2003/05/gateway/GM03Small}notSupportedGroup"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="objid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MD_MetadataType", propOrder = {
    "fileIdentifier",
    "dateStamp",
    "dataSetURI",
    "metadataSetURI",
    "identificationInfo"
})
public class MDMetadataType {

    protected OptionalString fileIdentifier;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateStamp;
    protected OptionalString dataSetURI;
    protected OptionalString metadataSetURI;
    @XmlElement(required = true)
    protected List<MDMetadataType.IdentificationInfo> identificationInfo;
    @XmlAttribute(required = true)
    protected String objid;

    /**
     * Gets the value of the fileIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalString }
     *     
     */
    public OptionalString getFileIdentifier() {
        return fileIdentifier;
    }

    /**
     * Sets the value of the fileIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalString }
     *     
     */
    public void setFileIdentifier(OptionalString value) {
        this.fileIdentifier = value;
    }

    /**
     * Gets the value of the dateStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateStamp() {
        return dateStamp;
    }

    /**
     * Sets the value of the dateStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateStamp(XMLGregorianCalendar value) {
        this.dateStamp = value;
    }

    /**
     * Gets the value of the dataSetURI property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalString }
     *     
     */
    public OptionalString getDataSetURI() {
        return dataSetURI;
    }

    /**
     * Sets the value of the dataSetURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalString }
     *     
     */
    public void setDataSetURI(OptionalString value) {
        this.dataSetURI = value;
    }

    /**
     * Gets the value of the metadataSetURI property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalString }
     *     
     */
    public OptionalString getMetadataSetURI() {
        return metadataSetURI;
    }

    /**
     * Sets the value of the metadataSetURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalString }
     *     
     */
    public void setMetadataSetURI(OptionalString value) {
        this.metadataSetURI = value;
    }

    /**
     * Gets the value of the identificationInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identificationInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentificationInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MDMetadataType.IdentificationInfo }
     * 
     * 
     */
    public List<MDMetadataType.IdentificationInfo> getIdentificationInfo() {
        if (identificationInfo == null) {
            identificationInfo = new ArrayList<MDMetadataType.IdentificationInfo>();
        }
        return this.identificationInfo;
    }

    /**
     * Gets the value of the objid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjid() {
        return objid;
    }

    /**
     * Sets the value of the objid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjid(String value) {
        this.objid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="language" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}LanguageCodeISO" maxOccurs="unbounded"/>
     *         &lt;element name="purpose" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}optionalPT_FreeText" minOccurs="0"/>
     *         &lt;element name="topicCategory" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}optionalTopicCategory" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="abstract" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText"/>
     *         &lt;element name="citation">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="title" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText"/>
     *                   &lt;element name="date" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="date">
     *                               &lt;simpleType>
     *                                 &lt;union memberTypes=" {http://www.geocat.ch/2003/05/gateway/GM03Small}NotAvailable {http://www.w3.org/2001/XMLSchema}date">
     *                                 &lt;/union>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="dateType" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}CI_DateTypeCode"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="pointOfContact" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="role" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}CI_RoleCode" maxOccurs="unbounded"/>
     *                   &lt;element name="individualName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="positionName" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText" minOccurs="0"/>
     *                   &lt;element name="organisationName" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attGroup ref="{http://www.geocat.ch/2003/05/gateway/GM03Small}notSupportedGroup"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="descriptiveKeywords" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="keyword" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *                 &lt;attGroup ref="{http://www.geocat.ch/2003/05/gateway/GM03Small}notSupportedGroup"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="extent" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="description" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}optionalPT_FreeText" minOccurs="0"/>
     *                   &lt;element name="geographicElement" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{http://www.geocat.ch/2003/05/gateway/GML}Polygon" minOccurs="0"/>
     *                             &lt;element name="westBoundLongitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
     *                             &lt;element name="eastBoundLongitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
     *                             &lt;element name="southBoundLatitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
     *                             &lt;element name="northBoundLatitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
     *                             &lt;element name="geographicIdentifier" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="code" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText"/>
     *                                     &lt;/sequence>
     *                                     &lt;attGroup ref="{http://www.geocat.ch/2003/05/gateway/GM03Small}notSupportedGroup"/>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attGroup ref="{http://www.geocat.ch/2003/05/gateway/GM03Small}notSupportedGroup"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "language",
        "purpose",
        "topicCategory",
        "_abstract",
        "citation",
        "pointOfContact",
        "descriptiveKeywords",
        "extent"
    })
    public static class IdentificationInfo {

        @XmlElement(required = true)
        protected List<String> language;
        protected OptionalPTFreeText purpose;
        protected List<OptionalTopicCategory> topicCategory;
        @XmlElement(name = "abstract", required = true)
        protected PTFreeText _abstract;
        @XmlElement(required = true)
        protected MDMetadataType.IdentificationInfo.Citation citation;
        protected List<MDMetadataType.IdentificationInfo.PointOfContact> pointOfContact;
        protected List<MDMetadataType.IdentificationInfo.DescriptiveKeywords> descriptiveKeywords;
        protected List<MDMetadataType.IdentificationInfo.Extent> extent;

        /**
         * Gets the value of the language property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the language property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLanguage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getLanguage() {
            if (language == null) {
                language = new ArrayList<String>();
            }
            return this.language;
        }

        /**
         * Gets the value of the purpose property.
         * 
         * @return
         *     possible object is
         *     {@link OptionalPTFreeText }
         *     
         */
        public OptionalPTFreeText getPurpose() {
            return purpose;
        }

        /**
         * Sets the value of the purpose property.
         * 
         * @param value
         *     allowed object is
         *     {@link OptionalPTFreeText }
         *     
         */
        public void setPurpose(OptionalPTFreeText value) {
            this.purpose = value;
        }

        /**
         * Gets the value of the topicCategory property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the topicCategory property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTopicCategory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OptionalTopicCategory }
         * 
         * 
         */
        public List<OptionalTopicCategory> getTopicCategory() {
            if (topicCategory == null) {
                topicCategory = new ArrayList<OptionalTopicCategory>();
            }
            return this.topicCategory;
        }

        /**
         * Gets the value of the abstract property.
         * 
         * @return
         *     possible object is
         *     {@link PTFreeText }
         *     
         */
        public PTFreeText getAbstract() {
            return _abstract;
        }

        /**
         * Sets the value of the abstract property.
         * 
         * @param value
         *     allowed object is
         *     {@link PTFreeText }
         *     
         */
        public void setAbstract(PTFreeText value) {
            this._abstract = value;
        }

        /**
         * Gets the value of the citation property.
         * 
         * @return
         *     possible object is
         *     {@link MDMetadataType.IdentificationInfo.Citation }
         *     
         */
        public MDMetadataType.IdentificationInfo.Citation getCitation() {
            return citation;
        }

        /**
         * Sets the value of the citation property.
         * 
         * @param value
         *     allowed object is
         *     {@link MDMetadataType.IdentificationInfo.Citation }
         *     
         */
        public void setCitation(MDMetadataType.IdentificationInfo.Citation value) {
            this.citation = value;
        }

        /**
         * Gets the value of the pointOfContact property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pointOfContact property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPointOfContact().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MDMetadataType.IdentificationInfo.PointOfContact }
         * 
         * 
         */
        public List<MDMetadataType.IdentificationInfo.PointOfContact> getPointOfContact() {
            if (pointOfContact == null) {
                pointOfContact = new ArrayList<MDMetadataType.IdentificationInfo.PointOfContact>();
            }
            return this.pointOfContact;
        }

        /**
         * Gets the value of the descriptiveKeywords property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the descriptiveKeywords property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDescriptiveKeywords().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MDMetadataType.IdentificationInfo.DescriptiveKeywords }
         * 
         * 
         */
        public List<MDMetadataType.IdentificationInfo.DescriptiveKeywords> getDescriptiveKeywords() {
            if (descriptiveKeywords == null) {
                descriptiveKeywords = new ArrayList<MDMetadataType.IdentificationInfo.DescriptiveKeywords>();
            }
            return this.descriptiveKeywords;
        }

        /**
         * Gets the value of the extent property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the extent property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExtent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MDMetadataType.IdentificationInfo.Extent }
         * 
         * 
         */
        public List<MDMetadataType.IdentificationInfo.Extent> getExtent() {
            if (extent == null) {
                extent = new ArrayList<MDMetadataType.IdentificationInfo.Extent>();
            }
            return this.extent;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="title" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText"/>
         *         &lt;element name="date" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="date">
         *                     &lt;simpleType>
         *                       &lt;union memberTypes=" {http://www.geocat.ch/2003/05/gateway/GM03Small}NotAvailable {http://www.w3.org/2001/XMLSchema}date">
         *                       &lt;/union>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="dateType" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}CI_DateTypeCode"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "title",
            "date"
        })
        public static class Citation {

            @XmlElement(required = true)
            protected PTFreeText title;
            @XmlElement(required = true)
            protected List<MDMetadataType.IdentificationInfo.Citation.Date> date;

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link PTFreeText }
             *     
             */
            public PTFreeText getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link PTFreeText }
             *     
             */
            public void setTitle(PTFreeText value) {
                this.title = value;
            }

            /**
             * Gets the value of the date property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the date property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDate().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link MDMetadataType.IdentificationInfo.Citation.Date }
             * 
             * 
             */
            public List<MDMetadataType.IdentificationInfo.Citation.Date> getDate() {
                if (date == null) {
                    date = new ArrayList<MDMetadataType.IdentificationInfo.Citation.Date>();
                }
                return this.date;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="date">
             *           &lt;simpleType>
             *             &lt;union memberTypes=" {http://www.geocat.ch/2003/05/gateway/GM03Small}NotAvailable {http://www.w3.org/2001/XMLSchema}date">
             *             &lt;/union>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="dateType" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}CI_DateTypeCode"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "date",
                "dateType"
            })
            public static class Date {

                @XmlElement(required = true)
                protected String date;
                @XmlElement(required = true)
                protected String dateType;

                /**
                 * Gets the value of the date property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDate() {
                    return date;
                }

                /**
                 * Sets the value of the date property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDate(String value) {
                    this.date = value;
                }

                /**
                 * Gets the value of the dateType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDateType() {
                    return dateType;
                }

                /**
                 * Sets the value of the dateType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDateType(String value) {
                    this.dateType = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="keyword" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *       &lt;attGroup ref="{http://www.geocat.ch/2003/05/gateway/GM03Small}notSupportedGroup"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "keyword"
        })
        public static class DescriptiveKeywords {

            @XmlElement(required = true)
            protected List<PTFreeText> keyword;
            @XmlAttribute
            protected Boolean notSupported;

            /**
             * Gets the value of the keyword property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the keyword property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getKeyword().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PTFreeText }
             * 
             * 
             */
            public List<PTFreeText> getKeyword() {
                if (keyword == null) {
                    keyword = new ArrayList<PTFreeText>();
                }
                return this.keyword;
            }

            /**
             * Gets the value of the notSupported property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isNotSupported() {
                if (notSupported == null) {
                    return false;
                } else {
                    return notSupported;
                }
            }

            /**
             * Sets the value of the notSupported property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setNotSupported(Boolean value) {
                this.notSupported = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="description" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}optionalPT_FreeText" minOccurs="0"/>
         *         &lt;element name="geographicElement" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{http://www.geocat.ch/2003/05/gateway/GML}Polygon" minOccurs="0"/>
         *                   &lt;element name="westBoundLongitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
         *                   &lt;element name="eastBoundLongitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
         *                   &lt;element name="southBoundLatitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
         *                   &lt;element name="northBoundLatitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
         *                   &lt;element name="geographicIdentifier" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="code" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText"/>
         *                           &lt;/sequence>
         *                           &lt;attGroup ref="{http://www.geocat.ch/2003/05/gateway/GM03Small}notSupportedGroup"/>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attGroup ref="{http://www.geocat.ch/2003/05/gateway/GM03Small}notSupportedGroup"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "description",
            "geographicElement"
        })
        public static class Extent {

            protected OptionalPTFreeText description;
            protected List<MDMetadataType.IdentificationInfo.Extent.GeographicElement> geographicElement;
            @XmlAttribute
            protected Boolean notSupported;

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link OptionalPTFreeText }
             *     
             */
            public OptionalPTFreeText getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link OptionalPTFreeText }
             *     
             */
            public void setDescription(OptionalPTFreeText value) {
                this.description = value;
            }

            /**
             * Gets the value of the geographicElement property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the geographicElement property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getGeographicElement().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link MDMetadataType.IdentificationInfo.Extent.GeographicElement }
             * 
             * 
             */
            public List<MDMetadataType.IdentificationInfo.Extent.GeographicElement> getGeographicElement() {
                if (geographicElement == null) {
                    geographicElement = new ArrayList<MDMetadataType.IdentificationInfo.Extent.GeographicElement>();
                }
                return this.geographicElement;
            }

            /**
             * Gets the value of the notSupported property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isNotSupported() {
                if (notSupported == null) {
                    return false;
                } else {
                    return notSupported;
                }
            }

            /**
             * Sets the value of the notSupported property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setNotSupported(Boolean value) {
                this.notSupported = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{http://www.geocat.ch/2003/05/gateway/GML}Polygon" minOccurs="0"/>
             *         &lt;element name="westBoundLongitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
             *         &lt;element name="eastBoundLongitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
             *         &lt;element name="southBoundLatitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
             *         &lt;element name="northBoundLatitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
             *         &lt;element name="geographicIdentifier" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="code" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText"/>
             *                 &lt;/sequence>
             *                 &lt;attGroup ref="{http://www.geocat.ch/2003/05/gateway/GM03Small}notSupportedGroup"/>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "polygon",
                "westBoundLongitude",
                "eastBoundLongitude",
                "southBoundLatitude",
                "northBoundLatitude",
                "geographicIdentifier"
            })
            public static class GeographicElement {

                @XmlElement(name = "Polygon", namespace = "http://www.geocat.ch/2003/05/gateway/GML")
                protected PolygonType polygon;
                protected Double westBoundLongitude;
                protected Double eastBoundLongitude;
                protected Double southBoundLatitude;
                protected Double northBoundLatitude;
                protected MDMetadataType.IdentificationInfo.Extent.GeographicElement.GeographicIdentifier geographicIdentifier;

                /**
                 * Gets the value of the polygon property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link PolygonType }
                 *     
                 */
                public PolygonType getPolygon() {
                    return polygon;
                }

                /**
                 * Sets the value of the polygon property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link PolygonType }
                 *     
                 */
                public void setPolygon(PolygonType value) {
                    this.polygon = value;
                }

                /**
                 * Gets the value of the westBoundLongitude property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getWestBoundLongitude() {
                    return westBoundLongitude;
                }

                /**
                 * Sets the value of the westBoundLongitude property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setWestBoundLongitude(Double value) {
                    this.westBoundLongitude = value;
                }

                /**
                 * Gets the value of the eastBoundLongitude property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getEastBoundLongitude() {
                    return eastBoundLongitude;
                }

                /**
                 * Sets the value of the eastBoundLongitude property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setEastBoundLongitude(Double value) {
                    this.eastBoundLongitude = value;
                }

                /**
                 * Gets the value of the southBoundLatitude property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getSouthBoundLatitude() {
                    return southBoundLatitude;
                }

                /**
                 * Sets the value of the southBoundLatitude property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setSouthBoundLatitude(Double value) {
                    this.southBoundLatitude = value;
                }

                /**
                 * Gets the value of the northBoundLatitude property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getNorthBoundLatitude() {
                    return northBoundLatitude;
                }

                /**
                 * Sets the value of the northBoundLatitude property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setNorthBoundLatitude(Double value) {
                    this.northBoundLatitude = value;
                }

                /**
                 * Gets the value of the geographicIdentifier property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link MDMetadataType.IdentificationInfo.Extent.GeographicElement.GeographicIdentifier }
                 *     
                 */
                public MDMetadataType.IdentificationInfo.Extent.GeographicElement.GeographicIdentifier getGeographicIdentifier() {
                    return geographicIdentifier;
                }

                /**
                 * Sets the value of the geographicIdentifier property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link MDMetadataType.IdentificationInfo.Extent.GeographicElement.GeographicIdentifier }
                 *     
                 */
                public void setGeographicIdentifier(MDMetadataType.IdentificationInfo.Extent.GeographicElement.GeographicIdentifier value) {
                    this.geographicIdentifier = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="code" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText"/>
                 *       &lt;/sequence>
                 *       &lt;attGroup ref="{http://www.geocat.ch/2003/05/gateway/GM03Small}notSupportedGroup"/>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "code"
                })
                public static class GeographicIdentifier {

                    @XmlElement(required = true)
                    protected PTFreeText code;
                    @XmlAttribute
                    protected Boolean notSupported;

                    /**
                     * Gets the value of the code property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link PTFreeText }
                     *     
                     */
                    public PTFreeText getCode() {
                        return code;
                    }

                    /**
                     * Sets the value of the code property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link PTFreeText }
                     *     
                     */
                    public void setCode(PTFreeText value) {
                        this.code = value;
                    }

                    /**
                     * Gets the value of the notSupported property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Boolean }
                     *     
                     */
                    public boolean isNotSupported() {
                        if (notSupported == null) {
                            return false;
                        } else {
                            return notSupported;
                        }
                    }

                    /**
                     * Sets the value of the notSupported property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Boolean }
                     *     
                     */
                    public void setNotSupported(Boolean value) {
                        this.notSupported = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="role" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}CI_RoleCode" maxOccurs="unbounded"/>
         *         &lt;element name="individualName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="positionName" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText" minOccurs="0"/>
         *         &lt;element name="organisationName" type="{http://www.geocat.ch/2003/05/gateway/GM03Small}PT_FreeText" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attGroup ref="{http://www.geocat.ch/2003/05/gateway/GM03Small}notSupportedGroup"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "role",
            "individualName",
            "positionName",
            "organisationName"
        })
        public static class PointOfContact {

            @XmlElement(required = true)
            protected List<String> role;
            protected String individualName;
            protected PTFreeText positionName;
            protected PTFreeText organisationName;
            @XmlAttribute
            protected Boolean notSupported;

            /**
             * Gets the value of the role property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the role property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRole().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getRole() {
                if (role == null) {
                    role = new ArrayList<String>();
                }
                return this.role;
            }

            /**
             * Gets the value of the individualName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIndividualName() {
                return individualName;
            }

            /**
             * Sets the value of the individualName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIndividualName(String value) {
                this.individualName = value;
            }

            /**
             * Gets the value of the positionName property.
             * 
             * @return
             *     possible object is
             *     {@link PTFreeText }
             *     
             */
            public PTFreeText getPositionName() {
                return positionName;
            }

            /**
             * Sets the value of the positionName property.
             * 
             * @param value
             *     allowed object is
             *     {@link PTFreeText }
             *     
             */
            public void setPositionName(PTFreeText value) {
                this.positionName = value;
            }

            /**
             * Gets the value of the organisationName property.
             * 
             * @return
             *     possible object is
             *     {@link PTFreeText }
             *     
             */
            public PTFreeText getOrganisationName() {
                return organisationName;
            }

            /**
             * Sets the value of the organisationName property.
             * 
             * @param value
             *     allowed object is
             *     {@link PTFreeText }
             *     
             */
            public void setOrganisationName(PTFreeText value) {
                this.organisationName = value;
            }

            /**
             * Gets the value of the notSupported property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isNotSupported() {
                if (notSupported == null) {
                    return false;
                } else {
                    return notSupported;
                }
            }

            /**
             * Sets the value of the notSupported property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setNotSupported(Boolean value) {
                this.notSupported = value;
            }

        }

    }

}
