package org.easysdi.proxy.domain;

// Generated Apr 9, 2013 11:54:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;

/**
 * Extensions generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
@FilterDef(name="entityState")
@Filter(name = "entityState",condition="enabled = 1")
public class Schemas implements java.io.Serializable {

	private Integer Extension_id;
	private String Version_id;

	public Schemas() {
	}

	public Schemas(String Version_id) {
		this.Version_id = Version_id;		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "extension_id", unique = true, nullable = false)
	public Integer getExtension_id() {
		return this.Extension_id;
	}

	public void setExtension_id(Integer Extension_id) {
		this.Extension_id = Extension_id;
	}

	@Column(name = "version_id", nullable = false, length = 20)
	public String getVersion_id() {
		return this.Version_id;
	}

	public void setVersion_id(String Version_id) {
		this.Version_id = Version_id;
	}
}
