package org.easysdi.proxy.domain;

// Generated Oct 3, 2013 1:38:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;

/**
 * SdiNamespace generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
@FilterDef(name="entityState")
@Filter(name = "entityState",condition="state = 1")
public class SdiNamespace implements java.io.Serializable {

	private Integer Id;
	private String Guid;
	private String Alias;
	private int Created_by;
	private Date Created;
	private Integer Modified_by;
	private Date Modified;
	private int Ordering;
	private boolean State;
	private int Checked_out;
	private Date Checked_out_time;
	private String Name;
	private String Prefix;
	private String Uri;
	private boolean System;
	private int Access;
	private int Asset_id;
	
	public SdiNamespace() {
	}

	public SdiNamespace(String Guid, String Alias, int Created_by,
			Date Created, int Ordering, boolean State, int Checked_out,
			Date Checked_out_time, String Name, String Prefix, String Uri,
			boolean System, int Access, int Asset_id) {
		this.Guid = Guid;
		this.Alias = Alias;
		this.Created_by = Created_by;
		this.Created = Created;
		this.Ordering = Ordering;
		this.State = State;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Name = Name;
		this.Prefix = Prefix;
		this.Uri = Uri;
		this.System = System;
		this.Access = Access;
		this.Asset_id = Asset_id;
	}

	public SdiNamespace(String Guid, String Alias, int Created_by,
			Date Created, Integer Modified_by, Date Modified, int Ordering,
			boolean State, int Checked_out, Date Checked_out_time, String Name,
			String Prefix, String Uri, boolean System, int Access,
			int Asset_id) {
		this.Guid = Guid;
		this.Alias = Alias;
		this.Created_by = Created_by;
		this.Created = Created;
		this.Modified_by = Modified_by;
		this.Modified = Modified;
		this.Ordering = Ordering;
		this.State = State;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Name = Name;
		this.Prefix = Prefix;
		this.Uri = Uri;
		this.System = System;
		this.Access = Access;
		this.Asset_id = Asset_id;		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "guid", nullable = false, length = 36)
	public String getGuid() {
		return this.Guid;
	}

	public void setGuid(String Guid) {
		this.Guid = Guid;
	}

	@Column(name = "alias", nullable = false, length = 50)
	public String getAlias() {
		return this.Alias;
	}

	public void setAlias(String Alias) {
		this.Alias = Alias;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreated_by() {
		return this.Created_by;
	}

	public void setCreated_by(int Created_by) {
		this.Created_by = Created_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.Created;
	}

	public void setCreated(Date Created) {
		this.Created = Created;
	}

	@Column(name = "modified_by")
	public Integer getModified_by() {
		return this.Modified_by;
	}

	public void setModified_by(Integer Modified_by) {
		this.Modified_by = Modified_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 19)
	public Date getModified() {
		return this.Modified;
	}

	public void setModified(Date Modified) {
		this.Modified = Modified;
	}

	@Column(name = "ordering", nullable = false)
	public int getOrdering() {
		return this.Ordering;
	}

	public void setOrdering(int Ordering) {
		this.Ordering = Ordering;
	}

	@Column(name = "state", nullable = false)
	public boolean isState() {
		return this.State;
	}

	public void setState(boolean State) {
		this.State = State;
	}

	@Column(name = "checked_out", nullable = false)
	public int getChecked_out() {
		return this.Checked_out;
	}

	public void setChecked_out(int Checked_out) {
		this.Checked_out = Checked_out;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checked_out_time", nullable = false, length = 19)
	public Date getChecked_out_time() {
		return this.Checked_out_time;
	}

	public void setChecked_out_time(Date Checked_out_time) {
		this.Checked_out_time = Checked_out_time;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}

	@Column(name = "prefix", nullable = false, length = 10)
	public String getPrefix() {
		return this.Prefix;
	}

	public void setPrefix(String Prefix) {
		this.Prefix = Prefix;
	}

	@Column(name = "uri", nullable = false)
	public String getUri() {
		return this.Uri;
	}

	public void setUri(String Uri) {
		this.Uri = Uri;
	}

	@Column(name = "system", nullable = false)
	public boolean isSystem() {
		return this.System;
	}

	public void setSystem(boolean System) {
		this.System = System;
	}

	@Column(name = "access", nullable = false)
	public int getAccess() {
		return this.Access;
	}

	public void setAccess(int Access) {
		this.Access = Access;
	}

	@Column(name = "asset_id", nullable = false)
	public int getAsset_id() {
		return this.Asset_id;
	}

	public void setAsset_id(int Asset_id) {
		this.Asset_id = Asset_id;
	}	
}
