CALL drop_column('sdi_language', 'datatable');
ALTER TABLE #__sdi_language ADD COLUMN `datatable` varchar(50) NOT NULL DEFAULT 'English';

UPDATE `#__sdi_language` SET datatable='Arabic' WHERE id='1';
UPDATE `#__sdi_language` SET datatable='Bulgarian' WHERE id='3';
UPDATE `#__sdi_language` SET datatable='Catalan' WHERE id='4';
UPDATE `#__sdi_language` SET datatable='Czech' WHERE id='5';
UPDATE `#__sdi_language` SET datatable='Danish' WHERE id='6';
UPDATE `#__sdi_language` SET datatable='German' WHERE id='7';
UPDATE `#__sdi_language` SET datatable='Greek' WHERE id='8';
UPDATE `#__sdi_language` SET datatable='English' WHERE id='9';
UPDATE `#__sdi_language` SET datatable='English' WHERE id='10';
UPDATE `#__sdi_language` SET datatable='Spanish' WHERE id='11';
UPDATE `#__sdi_language` SET datatable='Estonian' WHERE id='12';
UPDATE `#__sdi_language` SET datatable='Spanish' WHERE id='13';
UPDATE `#__sdi_language` SET datatable='Finnish' WHERE id='14';
UPDATE `#__sdi_language` SET datatable='French' WHERE id='15';
UPDATE `#__sdi_language` SET datatable='Irish' WHERE id='16';
UPDATE `#__sdi_language` SET datatable='Croatian' WHERE id='17';
UPDATE `#__sdi_language` SET datatable='Hungarian' WHERE id='18';
UPDATE `#__sdi_language` SET datatable='Italian' WHERE id='19';
UPDATE `#__sdi_language` SET datatable='Lithuanian' WHERE id='20';
UPDATE `#__sdi_language` SET datatable='Latvian' WHERE id='21';
UPDATE `#__sdi_language` SET datatable='Dutch' WHERE id='23';
UPDATE `#__sdi_language` SET datatable='Norwegian' WHERE id='24';
UPDATE `#__sdi_language` SET datatable='Polish' WHERE id='25';
UPDATE `#__sdi_language` SET datatable='Portuguese' WHERE id='26';
UPDATE `#__sdi_language` SET datatable='Romanian' WHERE id='27';
UPDATE `#__sdi_language` SET datatable='Russian' WHERE id='28';
UPDATE `#__sdi_language` SET datatable='Slovak' WHERE id='29';
UPDATE `#__sdi_language` SET datatable='Swedish' WHERE id='30';
UPDATE `#__sdi_language` SET datatable='Turkish' WHERE id='31';
UPDATE `#__sdi_language` SET datatable='Ukranian' WHERE id='32';
UPDATE `#__sdi_language` SET datatable='Chinese' WHERE id='33';