//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.13 at 04:39:39 PM CET 
//


package ch.interlis.interlis2.GM03V18;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GM03Comprehensive.Comprehensive.MD_Legislation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GM03Comprehensive.Comprehensive.MD_Legislation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="country">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CodeISO.CountryCodeISO_" type="{http://www.interlis.ch/INTERLIS2.2}CodeISO.CountryCodeISO_" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="language" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CodeISO.LanguageCodeISO_" type="{http://www.interlis.ch/INTERLIS2.2}CodeISO.LanguageCodeISO_" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="legislationType" type="{http://www.interlis.ch/INTERLIS2.2}GM03Comprehensive.Comprehensive.CI_LegislationTypeCode" minOccurs="0"/>
 *         &lt;element name="internalReference" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GM03Core.Core.CharacterString_" type="{http://www.interlis.ch/INTERLIS2.2}GM03Core.Core.CharacterString_" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="title">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="REF" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
 *                 &lt;attribute name="EXTREF" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
 *                 &lt;attribute name="BID" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
 *                 &lt;attribute name="NEXT_TID" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GM03Comprehensive.Comprehensive.MD_Legislation", propOrder = {
    "country",
    "language",
    "legislationType",
    "internalReference",
    "title"
})
@XmlSeeAlso({
    ch.interlis.interlis2.GM03V18.GM03ComprehensiveComprehensive.GM03ComprehensiveComprehensiveMDLegislation.class
})
public class GM03ComprehensiveComprehensiveMDLegislation {

    @XmlElement(required = true)
    protected GM03ComprehensiveComprehensiveMDLegislation.Country country;
    protected GM03ComprehensiveComprehensiveMDLegislation.Language language;
    protected GM03ComprehensiveComprehensiveCILegislationTypeCode legislationType;
    protected GM03ComprehensiveComprehensiveMDLegislation.InternalReference internalReference;
    @XmlElement(required = true)
    protected GM03ComprehensiveComprehensiveMDLegislation.Title title;

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link GM03ComprehensiveComprehensiveMDLegislation.Country }
     *     
     */
    public GM03ComprehensiveComprehensiveMDLegislation.Country getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link GM03ComprehensiveComprehensiveMDLegislation.Country }
     *     
     */
    public void setCountry(GM03ComprehensiveComprehensiveMDLegislation.Country value) {
        this.country = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link GM03ComprehensiveComprehensiveMDLegislation.Language }
     *     
     */
    public GM03ComprehensiveComprehensiveMDLegislation.Language getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link GM03ComprehensiveComprehensiveMDLegislation.Language }
     *     
     */
    public void setLanguage(GM03ComprehensiveComprehensiveMDLegislation.Language value) {
        this.language = value;
    }

    /**
     * Gets the value of the legislationType property.
     * 
     * @return
     *     possible object is
     *     {@link GM03ComprehensiveComprehensiveCILegislationTypeCode }
     *     
     */
    public GM03ComprehensiveComprehensiveCILegislationTypeCode getLegislationType() {
        return legislationType;
    }

    /**
     * Sets the value of the legislationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GM03ComprehensiveComprehensiveCILegislationTypeCode }
     *     
     */
    public void setLegislationType(GM03ComprehensiveComprehensiveCILegislationTypeCode value) {
        this.legislationType = value;
    }

    /**
     * Gets the value of the internalReference property.
     * 
     * @return
     *     possible object is
     *     {@link GM03ComprehensiveComprehensiveMDLegislation.InternalReference }
     *     
     */
    public GM03ComprehensiveComprehensiveMDLegislation.InternalReference getInternalReference() {
        return internalReference;
    }

    /**
     * Sets the value of the internalReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link GM03ComprehensiveComprehensiveMDLegislation.InternalReference }
     *     
     */
    public void setInternalReference(GM03ComprehensiveComprehensiveMDLegislation.InternalReference value) {
        this.internalReference = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link GM03ComprehensiveComprehensiveMDLegislation.Title }
     *     
     */
    public GM03ComprehensiveComprehensiveMDLegislation.Title getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link GM03ComprehensiveComprehensiveMDLegislation.Title }
     *     
     */
    public void setTitle(GM03ComprehensiveComprehensiveMDLegislation.Title value) {
        this.title = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CodeISO.CountryCodeISO_" type="{http://www.interlis.ch/INTERLIS2.2}CodeISO.CountryCodeISO_" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "codeISOCountryCodeISO"
    })
    public static class Country {

        @XmlElement(name = "CodeISO.CountryCodeISO_", required = true)
        protected List<GM03CoreCoreCountryCodeISO2> codeISOCountryCodeISO;

        /**
         * Gets the value of the codeISOCountryCodeISO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the codeISOCountryCodeISO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCodeISOCountryCodeISO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GM03CoreCoreCountryCodeISO2 }
         * 
         * 
         */
        public List<GM03CoreCoreCountryCodeISO2> getCodeISOCountryCodeISO() {
            if (codeISOCountryCodeISO == null) {
                codeISOCountryCodeISO = new ArrayList<GM03CoreCoreCountryCodeISO2>();
            }
            return this.codeISOCountryCodeISO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GM03Core.Core.CharacterString_" type="{http://www.interlis.ch/INTERLIS2.2}GM03Core.Core.CharacterString_" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gm03CoreCoreCharacterString"
    })
    public static class InternalReference {

        @XmlElement(name = "GM03Core.Core.CharacterString_", required = true)
        protected List<GM03CoreCoreCharacterString> gm03CoreCoreCharacterString;

        /**
         * Gets the value of the gm03CoreCoreCharacterString property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the gm03CoreCoreCharacterString property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGM03CoreCoreCharacterString().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GM03CoreCoreCharacterString }
         * 
         * 
         */
        public List<GM03CoreCoreCharacterString> getGM03CoreCoreCharacterString() {
            if (gm03CoreCoreCharacterString == null) {
                gm03CoreCoreCharacterString = new ArrayList<GM03CoreCoreCharacterString>();
            }
            return this.gm03CoreCoreCharacterString;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CodeISO.LanguageCodeISO_" type="{http://www.interlis.ch/INTERLIS2.2}CodeISO.LanguageCodeISO_" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "codeISOLanguageCodeISO"
    })
    public static class Language {

        @XmlElement(name = "CodeISO.LanguageCodeISO_", required = true)
        protected List<GM03CoreCoreLanguageCodeISO2> codeISOLanguageCodeISO;

        /**
         * Gets the value of the codeISOLanguageCodeISO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the codeISOLanguageCodeISO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCodeISOLanguageCodeISO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GM03CoreCoreLanguageCodeISO2 }
         * 
         * 
         */
        public List<GM03CoreCoreLanguageCodeISO2> getCodeISOLanguageCodeISO() {
            if (codeISOLanguageCodeISO == null) {
                codeISOLanguageCodeISO = new ArrayList<GM03CoreCoreLanguageCodeISO2>();
            }
            return this.codeISOLanguageCodeISO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="REF" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
     *       &lt;attribute name="EXTREF" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
     *       &lt;attribute name="BID" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
     *       &lt;attribute name="NEXT_TID" type="{http://www.interlis.ch/INTERLIS2.2}IliID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Title {

        @XmlAttribute(name = "REF")
        protected String ref;
        @XmlAttribute(name = "EXTREF")
        protected String extref;
        @XmlAttribute(name = "BID")
        protected String bid;
        @XmlAttribute(name = "NEXT_TID")
        protected String nexttid;

        /**
         * Gets the value of the ref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getREF() {
            return ref;
        }

        /**
         * Sets the value of the ref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setREF(String value) {
            this.ref = value;
        }

        /**
         * Gets the value of the extref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEXTREF() {
            return extref;
        }

        /**
         * Sets the value of the extref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEXTREF(String value) {
            this.extref = value;
        }

        /**
         * Gets the value of the bid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBID() {
            return bid;
        }

        /**
         * Sets the value of the bid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBID(String value) {
            this.bid = value;
        }

        /**
         * Gets the value of the nexttid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNEXTTID() {
            return nexttid;
        }

        /**
         * Sets the value of the nexttid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNEXTTID(String value) {
            this.nexttid = value;
        }

    }

}
