//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.07 at 04:52:23 PM CET 
//


package ch.geocat._2003._05.gateway.query;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.geocat._2003._05.gateway.query package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ValueTypeDummy_QNAME = new QName("http://www.geocat.ch/2003/05/gateway/query", "dummy");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.geocat._2003._05.gateway.query
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExpressionType }
     * 
     */
    public ExpressionType createExpressionType() {
        return new ExpressionType();
    }

    /**
     * Create an instance of {@link QueryRequestType }
     * 
     */
    public QueryRequestType createQueryRequestType() {
        return new QueryRequestType();
    }

    /**
     * Create an instance of {@link PresentationRequestType }
     * 
     */
    public PresentationRequestType createPresentationRequestType() {
        return new PresentationRequestType();
    }

    /**
     * Create an instance of {@link CriteriaType }
     * 
     */
    public CriteriaType createCriteriaType() {
        return new CriteriaType();
    }

    /**
     * Create an instance of {@link FormatType }
     * 
     */
    public FormatType createFormatType() {
        return new FormatType();
    }

    /**
     * Create an instance of {@link DummyType }
     * 
     */
    public DummyType createDummyType() {
        return new DummyType();
    }

    /**
     * Create an instance of {@link QueryResultType }
     * 
     */
    public QueryResultType createQueryResultType() {
        return new QueryResultType();
    }

    /**
     * Create an instance of {@link CatalogGatewayRequest }
     * 
     */
    public CatalogGatewayRequest createCatalogGatewayRequest() {
        return new CatalogGatewayRequest();
    }

    /**
     * Create an instance of {@link ValueType }
     * 
     */
    public ValueType createValueType() {
        return new ValueType();
    }

    /**
     * Create an instance of {@link ConcatenatedExpressionType }
     * 
     */
    public ConcatenatedExpressionType createConcatenatedExpressionType() {
        return new ConcatenatedExpressionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DummyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geocat.ch/2003/05/gateway/query", name = "dummy", scope = ValueType.class)
    public JAXBElement<DummyType> createValueTypeDummy(DummyType value) {
        return new JAXBElement<DummyType>(_ValueTypeDummy_QNAME, DummyType.class, ValueType.class, value);
    }

}
