//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.13 at 04:39:39 PM CET 
//


package ch.interlis.interlis2.GM03V18;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GM03Comprehensive.Comprehensive.distributorTransferOptionsMD_Distributor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GM03Comprehensive.Comprehensive.distributorTransferOptionsMD_Distributor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="distributorTransferOptions" type="{http://www.interlis.ch/INTERLIS2.2}RoleType"/>
 *         &lt;element name="MD_Distributor" type="{http://www.interlis.ch/INTERLIS2.2}RoleType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GM03Comprehensive.Comprehensive.distributorTransferOptionsMD_Distributor", propOrder = {
    "distributorTransferOptions",
    "mdDistributor"
})
@XmlSeeAlso({
    ch.interlis.interlis2.GM03V18.GM03ComprehensiveComprehensive.GM03ComprehensiveComprehensiveDistributorTransferOptionsMDDistributor.class
})
public class GM03ComprehensiveComprehensiveDistributorTransferOptionsMDDistributor {

    @XmlElement(required = true)
    protected RoleType distributorTransferOptions;
    @XmlElement(name = "MD_Distributor", required = true)
    protected RoleType mdDistributor;

    /**
     * Gets the value of the distributorTransferOptions property.
     * 
     * @return
     *     possible object is
     *     {@link RoleType }
     *     
     */
    public RoleType getDistributorTransferOptions() {
        return distributorTransferOptions;
    }

    /**
     * Sets the value of the distributorTransferOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleType }
     *     
     */
    public void setDistributorTransferOptions(RoleType value) {
        this.distributorTransferOptions = value;
    }

    /**
     * Gets the value of the mdDistributor property.
     * 
     * @return
     *     possible object is
     *     {@link RoleType }
     *     
     */
    public RoleType getMDDistributor() {
        return mdDistributor;
    }

    /**
     * Sets the value of the mdDistributor property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleType }
     *     
     */
    public void setMDDistributor(RoleType value) {
        this.mdDistributor = value;
    }

}
