//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.13 at 04:39:39 PM CET 
//


package ch.interlis.interlis2.GM03V18;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GM03Core.Core.PT_FreeURL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GM03Core.Core.PT_FreeURL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="URLGroup">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GM03Core.Core.PT_URLGroup" type="{http://www.interlis.ch/INTERLIS2.2}GM03Core.Core.PT_URLGroup" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GM03Core.Core.PT_FreeURL", propOrder = {
    "urlGroup"
})
public class GM03CoreCorePTFreeURL {

    @XmlElement(name = "URLGroup", required = true)
    protected GM03CoreCorePTFreeURL.URLGroup urlGroup;

    /**
     * Gets the value of the urlGroup property.
     * 
     * @return
     *     possible object is
     *     {@link GM03CoreCorePTFreeURL.URLGroup }
     *     
     */
    public GM03CoreCorePTFreeURL.URLGroup getURLGroup() {
        return urlGroup;
    }

    /**
     * Sets the value of the urlGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link GM03CoreCorePTFreeURL.URLGroup }
     *     
     */
    public void setURLGroup(GM03CoreCorePTFreeURL.URLGroup value) {
        this.urlGroup = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GM03Core.Core.PT_URLGroup" type="{http://www.interlis.ch/INTERLIS2.2}GM03Core.Core.PT_URLGroup" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gm03CoreCorePTURLGroup"
    })
    public static class URLGroup {

        @XmlElement(name = "GM03Core.Core.PT_URLGroup", required = true)
        protected List<GM03CoreCorePTURLGroup> gm03CoreCorePTURLGroup;

        /**
         * Gets the value of the gm03CoreCorePTURLGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the gm03CoreCorePTURLGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGM03CoreCorePTURLGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GM03CoreCorePTURLGroup }
         * 
         * 
         */
        public List<GM03CoreCorePTURLGroup> getGM03CoreCorePTURLGroup() {
            if (gm03CoreCorePTURLGroup == null) {
                gm03CoreCorePTURLGroup = new ArrayList<GM03CoreCorePTURLGroup>();
            }
            return this.gm03CoreCorePTURLGroup;
        }

    }

}
