//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.13 at 04:39:39 PM CET 
//


package ch.interlis.interlis2.GM03V18;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GM03Comprehensive.Comprehensive.MD_ObliqueLineAzimuth complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GM03Comprehensive.Comprehensive.MD_ObliqueLineAzimuth">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="azimuthAngle" type="{http://www.interlis.ch/INTERLIS2.2}GM03Core.Core.Real"/>
 *         &lt;element name="azimuthMeasurePointLongitude" type="{http://www.interlis.ch/INTERLIS2.2}GM03Core.Core.Real"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GM03Comprehensive.Comprehensive.MD_ObliqueLineAzimuth", propOrder = {
    "azimuthAngle",
    "azimuthMeasurePointLongitude"
})
@XmlSeeAlso({
    ch.interlis.interlis2.GM03V18.GM03ComprehensiveComprehensive.GM03ComprehensiveComprehensiveMDObliqueLineAzimuth.class
})
public class GM03ComprehensiveComprehensiveMDObliqueLineAzimuth {

    protected double azimuthAngle;
    protected double azimuthMeasurePointLongitude;

    /**
     * Gets the value of the azimuthAngle property.
     * 
     */
    public double getAzimuthAngle() {
        return azimuthAngle;
    }

    /**
     * Sets the value of the azimuthAngle property.
     * 
     */
    public void setAzimuthAngle(double value) {
        this.azimuthAngle = value;
    }

    /**
     * Gets the value of the azimuthMeasurePointLongitude property.
     * 
     */
    public double getAzimuthMeasurePointLongitude() {
        return azimuthMeasurePointLongitude;
    }

    /**
     * Sets the value of the azimuthMeasurePointLongitude property.
     * 
     */
    public void setAzimuthMeasurePointLongitude(double value) {
        this.azimuthMeasurePointLongitude = value;
    }

}
