<script>
Ext.onReady(function()
{
	Ext.QuickTips.init();
	bd=Ext.get('centercolumn');
	bd.createChild({tag: 'h2', html: 'Form 1 - Very Simple'});
	var simple = new Ext.form.FormPanel({items: [{name: 'first',fieldLabel: 'First Name',allowBlank: false,xtype: 'textfield'},{name: 'last',fieldLabel: 'Last Name',xtype: 'textfield'},{name: 'company',fieldLabel: 'Company',xtype: 'textfield'},{name: 'email',fieldLabel: 'Email',vtype: 'email',xtype: 'textfield'},{name: 'time',fieldLabel: 'Time',minValue: '8:00am',maxValue: '6:00pm',xtype: 'timefield'}],buttons: [{text: 'Save',xtype: 'button'},{text: 'Cancel',xtype: 'button'}],labelWidth: 75,url: 'save-form.php',frame: true,title: 'Simple Form',bodyStyle: 'padding:5px 5px 0',width: 350,defaults: {width: 230},defaultType: 'textfield'});
	simple.render(Ext.get('centercolumn'));
	bd.createChild({tag: 'h2', html: 'Form 2 - Adding fieldsets'});
	var fsf = new Ext.form.FormPanel({items: [{items: [{name: 'first',fieldLabel: 'First Name',allowBlank: false,xtype: 'textfield'},{name: 'last',fieldLabel: 'Last Name',xtype: 'textfield'},{name: 'company',fieldLabel: 'Company',xtype: 'textfield'},{name: 'email',fieldLabel: 'Email',vtype: 'email',xtype: 'textfield'}],checkboxToggle: true,title: 'User Information',autoHeight: true,defaults: {width: 210},collapsed: true,xtype: 'fieldset'},{items: [{name: 'home',fieldLabel: 'Home',value: '(888) 555-1212',xtype: 'textfield'},{name: 'business',fieldLabel: 'Business',xtype: 'textfield'},{name: 'mobile',fieldLabel: 'Mobile',xtype: 'textfield'},{name: 'fax',fieldLabel: 'Fax',xtype: 'textfield'}],title: 'Phone Number',collapsible: true,autoHeight: true,defaults: {width: 210},xtype: 'fieldset'}],buttons: [{text: 'Save',xtype: 'button'},{text: 'Cancel',xtype: 'button'}],labelWidth: 75,url: 'save-form.php',frame: true,title: 'Simple Form with FieldSets',bodyStyle: 'padding:5px 5px 0',width: 350});
	fsf.render(Ext.get('centercolumn'));
	bd.createChild({tag: 'h2', html: 'Form 3 - A little more complex'});
	var top = new Ext.form.FormPanel({items: [{items: [{items: [{name: 'first',fieldLabel: 'First Name',tabIndex: 1,xtype: 'textfield',anchor: '95%'},{name: 'company',fieldLabel: 'Company',tabIndex: 3,xtype: 'textfield',anchor: '95%'}],xtype: 'panel',columnWidth: 0.5,layout: 'form'},{items: [{name: 'last',fieldLabel: 'Last Name',tabIndex: 2,xtype: 'textfield',anchor: '95%'},{name: 'email',fieldLabel: 'Email',vtype: 'email',tabIndex: 4,xtype: 'textfield',anchor: '95%'}],xtype: 'panel',columnWidth: 0.5,layout: 'form'}],xtype: 'panel',layout: 'column'},{name: 'bio',fieldLabel: 'Biography',id: 'bio',tabIndex: 5,height: 200,xtype: 'htmleditor',anchor: '98%'}],buttons: [{text: 'Save',xtype: 'button'},{text: 'Cancel',xtype: 'button'}],labelAlign: 'top',frame: true,title: 'Multi Column, Nested Layouts and Anchoring',bodyStyle: 'padding:5px 5px 0',width: 600});
	top.render(Ext.get('centercolumn'));
	bd.createChild({tag: 'h2', html: 'Form 4 - Forms can be a TabPanel...'});
	var tabs = new Ext.form.FormPanel({items: {items: [{items: [{name: 'first',fieldLabel: 'First Name',allowBlank: false,value: 'Jack',xtype: 'textfield'},{name: 'company',fieldLabel: 'Company',value: 'Slocum',xtype: 'textfield'},{name: 'last',fieldLabel: 'Last Name',value: 'Ext JS',xtype: 'textfield'},{name: 'email',fieldLabel: 'Email',vtype: 'email',xtype: 'textfield'}],title: 'Personal Details',defaults: {width: 230},defaultType: 'textfield',xtype: 'panel',layout: 'form'},{items: [{name: 'home',fieldLabel: 'Home',value: '(888) 555-1212',xtype: 'textfield'},{name: 'business',fieldLabel: 'Business',xtype: 'textfield'},{name: 'mobile',fieldLabel: 'Mobile',xtype: 'textfield'},{name: 'fax',fieldLabel: 'Fax',xtype: 'textfield'}],title: 'Phone Numbers',defaults: {width: 230},defaultType: 'textfield',xtype: 'panel',layout: 'form'}],activeTab: 0,defaults: {autoHeight: true,bodyStyle: 'padding:10px'},xtype: 'tabpanel'},buttons: [{text: 'Save',xtype: 'button'},{text: 'Cancel',xtype: 'button'}],border: false,labelWidth: 75,width: 350});
	tabs.render(Ext.get('centercolumn'));
	bd.createChild({tag: 'h2', html: 'Form 5 - ... and forms can contain TabPanel(s)'});
	var tabs2 = new Ext.form.FormPanel({items: [{items: [{items: [{name: 'first',fieldLabel: 'First Name',xtype: 'textfield',anchor: '95%'},{name: 'company',fieldLabel: 'Company',xtype: 'textfield',anchor: '95%'}],border: false,xtype: 'panel',columnWidth: 0.5,layout: 'form'},{items: [{name: 'last',fieldLabel: 'Last Name',xtype: 'textfield',anchor: '95%'},{name: 'email',fieldLabel: 'Email',vtype: 'email',xtype: 'textfield',anchor: '95%'}],border: false,xtype: 'panel',columnWidth: 0.5,layout: 'form'}],border: false,xtype: 'panel',layout: 'column'},{items: [{items: [{name: 'first',fieldLabel: 'First Name',allowBlank: false,value: 'Jack',xtype: 'textfield'},{name: 'company',fieldLabel: 'Company',value: 'Slocum',xtype: 'textfield'},{name: 'last',fieldLabel: 'Last Name',value: 'Ext JS',xtype: 'textfield'},{name: 'email',fieldLabel: 'Email',vtype: 'email',xtype: 'textfield'}],title: 'Personal Details',defaults: {width: 230},defaultType: 'textfield',xtype: 'panel',layout: 'form'},{items: [{name: 'home',fieldLabel: 'Home',value: '(888) 555-1212',xtype: 'textfield'},{name: 'business',fieldLabel: 'Business',xtype: 'textfield'},{name: 'mobile',fieldLabel: 'Mobile',xtype: 'textfield'},{name: 'fax',fieldLabel: 'Fax',xtype: 'textfield'}],title: 'Phone Numbers',defaults: {width: 230},defaultType: 'textfield',xtype: 'panel',layout: 'form'},{items: {name: 'bio2',fieldLabel: 'Biography',id: 'bio2',xtype: 'htmleditor'},cls: 'x-plain',title: 'Biography',xtype: 'panel',layout: 'fit'}],plain: true,activeTab: 0,height: 235,defaults: {bodyStyle: 'padding:10px'},xtype: 'tabpanel'}],buttons: [{text: 'Save',xtype: 'button'},{text: 'Cancel',xtype: 'button'}],labelAlign: 'top',title: 'Inner Tabs',bodyStyle: 'padding:5px',width: 600});
	tabs2.render(Ext.get('centercolumn'));
}
);
</script>