
Ext.namespace("EasySDI_Map");EasySDI_Map.MapPanel=Ext.extend(Ext.Panel,{selectFeatureCtrl:null,projMenuButton:null,overviewWidth:120,overviewHeight:80,constructor:function(config){this._initProjections();this._initMap();this.GeoExtMapPanel=new GeoExt.MapPanel({border:true,region:"center",id:'geoMap',map:this.map});config.layout="border";config.items=[this.GeoExtMapPanel];config.items.push(this._getToolbar());config.items.push(this._getToolbarSouth());EasySDI_Map.MapPanel.superclass.constructor.apply(this,arguments);},addWmsLayerSet:function(featureType,filter,style,searchBarIdx){var layer,layerOptions,p,dom=new OpenLayers.Format.Filter.v1_0_0().write(filter);var filterText=this._XMLtoString(dom);var actualFeatureType,layers=[];for(var geom in SData.searchPrecisions){p=SData.searchPrecisions[geom];actualFeatureType=featureType.replace('{geom}',geom);if(p.active){var WMSoptions={LAYERS:componentParams.pubFeaturePrefix+':'+actualFeatureType,SERVICE:'WMS',STYLES:style+(geom=='_geom_orig'?'_geom_orig':''),SRS:componentParams.projection,TRANSPARENT:true,FILTER:filterText,GEOMETRYNAME:geom,FORMAT:'image/png',VERSION:componentParams.pubWmsVersion};layerOptions={isBaseLayer:false,singleTile:true,opacity:(p.style!==undefined?p.style.fillOpacity||0.8:0.8)};if(p.maxScale!==null&&p.maxScale!==0){layerOptions.maxScale=p.maxScale;}
if(p.minScale!==null){layerOptions.minScale=p.minScale;}
layer=new OpenLayers.Layer.WMS(EasySDI_Map.lang.getLocal('MP_SEARCH_RESULTS')+' '+(searchBarIdx+1),componentParams.pubWmsUrl,WMSoptions,layerOptions);layer.events.register('loadend',layer,this._hideMsg);layers.push(layer);if(p.minScale&&p.lowScaleSwitchTo){actualFeatureType=featureType.replace('{geom}',p.lowScaleSwitchTo);lp=SData.searchPrecisions[p.lowScaleSwitchTo];var LowScaleWMSoptions={LAYERS:actualFeatureType,SERVICE:'WMS',STYLES:style,SRS:componentParams.projection,TRANSPARENT:true,FILTER:filterText,GEOMETRYNAME:p.lowScaleSwitchTo,FORMAT:'image/png',VERSION:componentParams.pubWmsVersion};layerOptions={isBaseLayer:false,singleTile:true,opacity:(lp.style!==undefined?lp.style.fillOpacity||0.8:0.8),maxScale:p.minScale,minScale:lp.minScale||1000,displayInLayerSwitcher:false};var lowScaleLayer=new OpenLayers.Layer.WMS("Search results",componentParams.pubWmsUrl,LowScaleWMSoptions,layerOptions);this.map.addLayer(lowScaleLayer);layers.push(lowScaleLayer);lowScaleLayer.events.register('loadend',lowScaleLayer,this._hideMsg);}
this.map.addLayer(layer);}}
if(layers.length===0){var geom=SData.searchLayer.geometryName;actualFeatureType=featureType.replace('{geom}',geom);var WMSoptions={LAYERS:componentParams.pubFeaturePrefix+':'+actualFeatureType,SERVICE:'WMS',STYLES:style,SRS:componentParams.projection,TRANSPARENT:true,FILTER:filterText,GEOMETRYNAME:geom,FORMAT:'image/png',TILED:true,VERSION:componentParams.pubWmsVersion};layerOptions={isBaseLayer:false,singleTile:true,opacity:0.4};layer=new OpenLayers.Layer.WMS(EasySDI_Map.lang.getLocal('MP_SEARCH_RESULTS')+' '+(searchBarIdx+1),componentParams.pubWmsUrl,WMSoptions,layerOptions);layer.events.register('loadend',layer,this._hideMsg);layers.push(layer);this.map.addLayer(layer);}
return layers;},_XMLtoString:function(elem){var serializer,serialized;try{serializer=new XMLSerializer();serialized=serializer.serializeToString(elem);}catch(e){serialized=elem.xml;}
return serialized;},addWfsFeatureLayerSet:function(protocol){var layers=[],lp,p;var strategy=new OpenLayers.Strategy.FixedMultiLayer({protocol:protocol});protocol.readModeMulti=true;try{var layer,lowScaleLayer;for(var geom in SData.searchPrecisions){p=SData.searchPrecisions[geom];if(p.active){var selectOpacity=(p.style!==undefined?p.style.fillOpacity||0.4:0.4)+0.3;layer=new OpenLayers.Layer.Vector(EasySDI_Map.lang.getLocal('MP_SELECTABLE_LAYER'),{strategies:[strategy],protocol:protocol,maxScale:p.maxScale,minScale:p.minScale,geometryName:geom,styleMap:new OpenLayers.StyleMap({"default":new OpenLayers.Style({strokeColor:"#3399ff",strokeWidth:2,fillOpacity:0}),"select":new OpenLayers.Style({fillColor:"#ff9933",strokeColor:"#3399ff",fillOpacity:selectOpacity})})});this.map.addLayer(layer);layers.push(layer);if(p.minScale&&p.lowScaleSwitchTo){lp=SData.searchPrecisions[p.lowScaleSwitchTo];selectOpacity=(lp.style!==undefined?lp.style.fillOpacity||0.4:0.4)+0.3;lowScaleLayer=new OpenLayers.Layer.Vector(p.title+' low scale',{strategies:[strategy],protocol:protocol,maxScale:p.minScale,minScale:lp.minScale||1000,geometryName:p.lowScaleSwitchTo,displayInLayerSwitcher:false,styleMap:new OpenLayers.StyleMap({"default":new OpenLayers.Style({strokeColor:"#3399ff",strokeWidth:2,fillOpacity:0}),"select":new OpenLayers.Style({fillColor:"#66ccff",strokeColor:"#3399ff",fillOpacity:lp.style.fillOpacity+0.3})})});this.map.addLayer(lowScaleLayer);layers.push(lowScaleLayer);}}}
if(layers.length===0){layer=new OpenLayers.Layer.Vector(EasySDI_Map.lang.getLocal('MP_SELECTABLE_LAYER'),{strategies:[strategy],protocol:protocol,geometryName:SData.searchLayer.geometryName,styleMap:new OpenLayers.StyleMap({"default":new OpenLayers.Style({strokeColor:"#3399ff",strokeWidth:2,fillOpacity:0}),"select":new OpenLayers.Style({fillColor:"#ff9933",strokeColor:"#3399ff",fillOpacity:0.7})})});this.map.addLayer(layer);layers.push(layer);}
strategy.activate(protocol);}finally{protocol.readModeMulti=false;}
var origActive=this.selectFeatureCtrl.active;if(origActive){this.selectFeatureCtrl.deactivate();}
if(this.selectFeatureCtrl.layers===null){this.selectFeatureCtrl.layers=[];}
this.selectFeatureCtrl.layers=this.selectFeatureCtrl.layers.concat(layers);this.selectFeatureCtrl.layer=new OpenLayers.Layer.Vector.RootContainer(this.selectFeatureCtrl.id+"_container",{layers:this.selectFeatureCtrl.layers});this.selectFeatureCtrl.handlers.feature.layer=this.selectFeatureCtrl.layer;if(origActive){this.selectFeatureCtrl.activate();}
return layers;},_initMap:function(){var options={controls:[],layers:[]};if(componentParams.projection!='')
options.projection=componentParams.projection;if(componentParams.mapUnit!='')
options.units=componentParams.mapUnit;if(componentParams.mapMaxExtent!='')
options.maxExtent=componentParams.mapMaxExtent;if(componentParams.mapMinScale!='')
options.minScale=componentParams.mapMinScale;if(componentParams.mapMaxScale!='')
options.maxScale=componentParams.mapMaxScale;if(componentParams.mapResolutions!='')
options.resolutions=componentParams.mapResolutions;if(componentParams.mapMinResolution!='')
options.minResolution=componentParams.mapMinResolution;if(componentParams.mapMaxResolution!='')
options.maxResolution=componentParams.mapMaxResolution;if(componentParams.numZoomLevels!='')
options.numZoomLevels=componentParams.numZoomLevels;var ov_options={};if(componentParams.mapMaxExtent!='')
ov_options.maxExtent=componentParams.mapMaxExtent;this.map=new OpenLayers.Map(options);if($.browser.mozilla)
this.map.events.hack=5;else if($.browser.msie)
this.map.events.hack=2;if($.browser.safari)
this.map.events.hack=4;this.map.events.getMousePosition=function(evt){if(!this.includeXY){this.clearMouseCache();}else if(!this.element.hasScrollEvent){OpenLayers.Event.observe(window,"scroll",this.clearMouseListener);this.element.hasScrollEvent=true;}
if(!this.element.scrolls){this.element.scrolls=[(document.documentElement.scrollLeft||document.body.scrollLeft),(document.documentElement.scrollTop||document.body.scrollTop)];}
if(!this.element.lefttop){this.element.lefttop=[(document.documentElement.clientLeft||0),(document.documentElement.clientTop||0)];}
if(!this.element.offsets){this.element.offsets=OpenLayers.Util.pagePosition(this.element);this.element.offsets[0]+=this.element.scrolls[0];this.element.offsets[1]+=this.element.scrolls[1];}
return new OpenLayers.Pixel((evt.clientX+this.element.scrolls[0])-this.element.offsets[0]-this.element.lefttop[0]
-this.hack,(evt.clientY+this.element.scrolls[1])-this.element.offsets[1]-this.element.lefttop[1]-this.hack);}
this.map.addControl(new OpenLayers.Control.ScaleLine());this.map.addControl(new OpenLayers.Control.PanZoomBar());this.navHistoryCtrl=new OpenLayers.Control.NavigationHistory();this.map.addControl(this.navHistoryCtrl);this.navCtrl=new OpenLayers.Control.Navigation();this.map.addControl(this.navCtrl);this.navCtrl.activate();this.selectFeatureCtrl=new OpenLayers.Control.SelectFeature(null,{clickout:true,toggle:true,multiple:false,hover:false,toggleKey:"ctrlKey",multipleKey:"shiftKey",box:true});this.zoomInBoxCtrl=new OpenLayers.Control.ZoomBox();this.map.addControl(this.zoomInBoxCtrl);this.zoomOutBoxCtrl=new OpenLayers.Control.ZoomBox({out:true});this.map.addControl(this.zoomOutBoxCtrl);this.map.addControl(this.selectFeatureCtrl);this.addGetFeatureCtrl();this.map.events.register('moveend',this,this._onMapMoveEnd);var loadingpanel=new OpenLayers.Control.LoadingPanel();this.map.addControl(loadingpanel);this.map.loadingPanel=loadingpanel;},_addOverView:function(){if(componentDisplayOption.MapOverviewEnable){overviewLayer=this.createOverviewBaseLayer(SData.overviewLayer[0]);var bounds;var viewSize=new OpenLayers.Size(200,150)
if(SData.overviewLayer[0].projection!=this.map.getProjection()){bounds=this.map.getExtent().transform(this.map.getProjectionObject(),new OpenLayers.Projection(SData.overviewLayer[0].projection));}else{bounds=this.map.maxExtent;}
if(SData.overviewLayer[0].type=="WMS"){overviewLayer.maxExtent=bounds;overviewLayer.minExtent=bounds;var wRes=bounds.getWidth()/viewSize.w;var hRes=bounds.getHeight()/viewSize.h;maxResolution=Math.max(wRes,hRes);}
else{maxResolution=overviewLayer.maxResolution;}
overviewLayer.minResolution=maxResolution
overviewLayer.maxResolution=maxResolution;overviewLayer.resolutions=[maxResolution];overviewLayer.scales=null;overviewLayer.minScale=null;overviewLayer.maxScale=null;ovControl=new OpenLayers.Control.OverviewMap({mapOptions:{maxExtent:bounds,restrictedExtent:bounds,minExtent:bounds,maxResolution:maxResolution,minResolution:maxResolution,resolutions:[maxResolution],minScale:null,maxScale:null,scales:null,numZoomLevels:1,projection:SData.overviewLayer[0].projection,center:bounds.getCenterLonLat()},layers:[overviewLayer],size:viewSize});ovControl.isSuitableOverview=function(){return true;};this.map.addControl(ovControl);}},addGetFeatureCtrl:function(){this.getFeatureCtrl=new EasySDI_Map.WMSGetFeatureInfo({url:componentParams.componentUrl+'&view=getfeatureinfo',infoFormat:'text/html',queryVisible:true,format:new OpenLayers.Format.WMSGetFeatureInfo(),eventListeners:{getfeatureinfo:function(event){if(this.popup!=null)
this.popup.destroy();this.popup=new OpenLayers.Popup.FramedCloud("epopup",this.map.getLonLatFromPixel(event.xy),null,event.text,null,true);this.map.addPopup(this.popup);$(".tabs").tabs();this.popup.updateSize();}}});this.map.addControl(this.getFeatureCtrl);},_displayFeaturePopup:function(feature){this.trigger('featurePopup',feature.attributes[componentParams.featureIdAttribute]);},_onMapMoveEnd:function(){if(this.previousButton.xtype!="tbspacer"){this.previousButton.setDisabled(this.navHistoryCtrl.previousStack.length<2);this.nextButton.setDisabled(this.navHistoryCtrl.nextStack.length===0);}},_onZoomToLocation:function(combo,newValue,index){Ext.getCmp('geoMap').map.zoomToExtent(newValue.data.feature.geometry.getBounds());if(false){var x,y,start,q;var mode=0;var rawValue=this.locAutocomplete.getRawValue();for(q=0;q<rawValue.length;q++){if(mode===0){if(rawValue.charAt(q)!==' '){mode=1;start=q;}}else if(mode==1){if(rawValue.charAt(q)===' '||rawValue.charAt(q)==','){mode=2;x=rawValue.substring(start,q);}}else if(mode==2){if(rawValue.charAt(q)!=' '&&rawValue.charAt(q)!=','){mode=3;y=rawValue.substring(q);}}}
if(mode!=3||isNaN(parseFloat(x))||isNaN(parseFloat(y))){alert(EasySDI_Map.lang.getLocal('MP_ZOOM_ERROR')+" : ["+x+"] ["+y+"]");}else{var point=new OpenLayers.Geometry.Point(parseFloat(x),parseFloat(y));var projTitle=this.projMenuButton.getText();var fromProjection;for(q=0;q<componentParams.displayProjections.length;q++){if(projTitle==componentParams.displayProjections[q].title){fromProjection=new OpenLayers.Projection(componentParams.displayProjections[q].name);}}
var toProjection=new OpenLayers.Projection(componentParams.projection);point.transform(fromProjection,toProjection);var lonlat=new OpenLayers.LonLat(point.x,point.y);this.map.panTo(lonlat);this.map.zoomTo(componentParams.defaultCoordMapZoom||4);}}},removeLayers:function(layers,removeWms,removeWfs){Ext.each(layers,function(layer){if(this.selectFeatureCtrl.layers!==null&&typeof this.selectFeatureCtrl.layers!=="undefined"){OpenLayers.Util.removeItem(this.selectFeatureCtrl.layers,layer);}
if(layer.CLASS_NAME=="OpenLayers.Layer.WMS"&&removeWms){layer.events.unregister('loadend',layer,this._hideMsg);}
if((removeWms&&layer.CLASS_NAME=="OpenLayers.Layer.WMS")||(removeWfs&&layer.CLASS_NAME=="OpenLayers.Layer.Vector")){this.map.removeLayer(layer);}},this);},_hideMsg:function(layer){Ext.Msg.hide();layer.object.events.unregister('loadend',null,arguments.callee);},_initProjections:function(){Ext.each(componentParams.displayProjections,function(proj){if(typeof proj.proj4text!=="undefined"){Proj4js.defs[proj.name]=proj.proj4text;}});},zoomToExtent:function(bounds){this.map.zoomToExtent(bounds);},highlightFeature:function(feature){this.selectFeatureCtrl.select(feature);},clearSelection:function(){this.selectFeatureCtrl.unselectAll();},refreshLegend:function(){this.trigger('refreshLegend');},_getToolbarSouth:function(){var styleDropDownItems;styleDropDownItems=this._createAnnotationStyleDropDownItems();if(componentDisplayOption.rectangleButtonEnable){this.rectangleButton=new Ext.Toolbar.Button({iconCls:'rectangleBtn',minWidth:26,enableToggle:true,toggleGroup:'mapCtrl',allowDepress:false,handler:this._updateCtrlBtns,scope:this});}else{this.rectangleButton={xtype:'tbspacer'}}
if(componentDisplayOption.polygonButtonEnable){this.polygonButton=new Ext.Toolbar.Button({iconCls:'polygonBtn',minWidth:26,enableToggle:true,toggleGroup:'mapCtrl',allowDepress:false,handler:this._updateCtrlBtns,scope:this});}else{this.polygonButton={xtype:'tbspacer'}}
if(componentDisplayOption.pointButtonEnable){this.pointButton=new Ext.Toolbar.Button({iconCls:'pointBtn',minWidth:26,enableToggle:true,toggleGroup:'mapCtrl',allowDepress:false,handler:this._updateCtrlBtns,scope:this});}else{this.pointButton={xtype:'tbspacer'}}
if(componentDisplayOption.modifyFeatureButtonEnable){this.modifyFeatureButton=new Ext.Toolbar.Button({iconCls:'modifyFeatureBtn',minWidth:26,enableToggle:true,toggleGroup:'mapCtrl',allowDepress:false,handler:this._updateCtrlBtns,scope:this});}else{this.modifyFeatureButton={xtype:'tbspacer'}}
if(componentDisplayOption.pathButtonEnable){this.pathButton=new Ext.Toolbar.Button({iconCls:'pathBtn',minWidth:26,enableToggle:true,toggleGroup:'mapCtrl',allowDepress:false,handler:this._updateCtrlBtns,scope:this});}else{this.pathButton={xtype:'tbspacer'}}
if(componentDisplayOption.selectFeatureButtonEnable){this.selectFeatureButton=new Ext.Toolbar.Button({iconCls:'deleteFeatureBtn',minWidth:26,enableToggle:true,toggleGroup:'mapCtrl',allowDepress:false,handler:this._updateCtrlBtns,scope:this});}else{this.selectFeatureButton={xtype:'tbspacer'}}
if(componentDisplayOption.CoordinateEnable){var mouseposDiv=document.createElement("div");mouseposDiv.setAttribute('id','mapposition');this.mousePos=new OpenLayers.Control.MousePosition({div:mouseposDiv,numDigits:0});this.map.addControl(this.mousePos);var projMenuItems=[];Ext.each(componentParams.displayProjections,function(item,i){projMenuItems.push(new Ext.menu.CheckItem({text:item.title,checked:i===0,group:'proj',checkHandler:function(e){this.onProjChecked(e);},scope:this,stateId:i}));},this);var projMenu={items:projMenuItems};this.projMenuButton=new Ext.Toolbar.Button({text:EasySDI_Map.lang.getLocal(projMenuItems[0].text),menu:projMenu});}else{this.projMenuButton={xtype:'tbspacer'}}
return new Ext.Toolbar({region:"south",id:"southToolbar",autoHeight:true,items:[this.rectangleButton,this.polygonButton,this.pointButton,this.pathButton,this.modifyFeatureButton,this.selectFeatureButton,componentDisplayOption.selectAnnotationStyleButtonEnable?{iconCls:'styleChooserBtn',menu:{items:styleDropDownItems}}:{xtype:'tbspacer'},{xtype:'tbfill'},this.projMenuButton,new Ext.Toolbar.Item(mouseposDiv)]});},_getToolbar:function(){if(SData.localisationLayers.length>0){var storeObject={fields:[{name:'ipa_fullid',type:'string'},{name:'ipa_display_name',type:'string'}],wfslist:[]};Ext.each(SData.localisationLayers,function(loc){var parts=loc.feature_type_name.split(":");if(parts[1]!=null&&parts[0]!=null)
{storeObject.wfslist.push({url:loc.wfs_url,featureType:parts[1],featurePrefix:parts[0],featureNS:loc.featureNS,fields:[{name:'ipa_fullid',mapping:(componentParams.autocompleteUseFID?'fid':loc.id_field_name),type:'string',prefix:loc.id},{name:'ipa_display_name',mapping:loc.name_field_name,type:'string',append:" ("+loc.title+")"}],filterField:loc.name_field_name,maxFeatures:componentParams.autocompleteMaxFeat});}
else
{storeObject.wfslist.push({url:loc.wfs_url,featureType:loc.feature_type_name,fields:[{name:'ipa_fullid',mapping:(componentParams.autocompleteUseFID?'fid':loc.id_field_name),type:'string',prefix:loc.id},{name:'ipa_display_name',mapping:loc.name_field_name,type:'string',append:" ("+loc.title+")"}],filterField:loc.name_field_name,maxFeatures:componentParams.autocompleteMaxFeat});}},this);this.locStore=new EasySDI_Map.WfsMultiStore({},storeObject);}else{this.locStore=new Ext.data.SimpleStore({fields:['ipa_fullid','ipa_display_name'],data:[['0',EasySDI_Map.lang.getLocal('SP_ERROR_NO_LOCALISATION')]]});}
if(componentParams.localisationInputWidth==undefined)
componentParams.localisationInputWidth=200;else
componentParams.localisationInputWidth=parseInt(componentParams.localisationInputWidth);if(componentDisplayOption.locAutocompleteEnable){this.locAutocomplete=new Ext.form.ComboBox({id:'localisationInputWidth',store:this.locStore,valueField:'ipa_fullid',displayField:'ipa_display_name',emptyText:EasySDI_Map.lang.getLocal('FP_SURVEY_SEARCH_FOR'),loadingText:EasySDI_Map.lang.getLocal('SP_SEARCHING'),width:componentParams.localisationInputWidth,triggerAction:'all',mode:'remote',selectOnFocus:true,minChars:componentParams.autocompleteNumChars});this.locAutocomplete.on('select',this._onZoomToLocation);}else{this.locAutocomplete={xtype:'tbspacer'}}
if(componentDisplayOption.previousButtonEnable){this.previousButton=new Ext.Toolbar.Button({iconCls:'previousBtn',tooltip:EasySDI_Map.lang.getLocal('MP_HIST_BACK_TTIP'),handler:function(){this.navHistoryCtrl.previousTrigger();},scope:this});}
else{this.previousButton={xtype:'tbspacer'}}
if(componentDisplayOption.nextButtonEnable){this.nextButton=new Ext.Toolbar.Button({iconCls:'nextBtn',tooltip:EasySDI_Map.lang.getLocal('MP_HIST_NEXT_TTIP'),handler:function(){this.navHistoryCtrl.nextTrigger();},scope:this});}else{this.nextButton={xtype:'tbspacer'}}
if(componentDisplayOption.navButtonEnable){this.navButton=new Ext.Toolbar.Button({iconCls:'navBtn',tooltip:EasySDI_Map.lang.getLocal('MP_PAN_TTIP'),enableToggle:true,toggleGroup:'mapCtrl',allowDepress:false,handler:this._updateCtrlBtns,scope:this,pressed:true});}else{this.navButton={xtype:'tbspacer'}}
if(componentDisplayOption.zoomInBoxButtonEnable){this.zoomInBoxButton=new Ext.Toolbar.Button({iconCls:'zoomInBoxBtn',tooltip:EasySDI_Map.lang.getLocal('MP_ZOOM_IN_TTIP'),enableToggle:true,toggleGroup:'mapCtrl',allowDepress:false,handler:this._updateCtrlBtns,scope:this});}else{this.zoomInBoxButton={xtype:'tbspacer'}}
if(componentDisplayOption.zoomOutBoxButtonEnable){this.zoomOutBoxButton=new Ext.Toolbar.Button({iconCls:'zoomOutBoxBtn',tooltip:EasySDI_Map.lang.getLocal('MP_ZOOM_OUT_TTIP'),enableToggle:true,toggleGroup:'mapCtrl',allowDepress:false,handler:this._updateCtrlBtns,scope:this});}else{this.zoomOutBoxButton={xtype:'tbspacer'}}
var showScale=true;if(componentDisplayOption.zoomToScaleFieldEnable){this.zoomToScaleField=new Ext.form.TextField({height:20,width:50,tooltip:EasySDI_Map.lang.getLocal('MP_ZOOM_TO_SCALE_TTIP'),readOnly:false,enableKeyEvents:true});}else{showScale=false;this.zoomToScaleField={xtype:'tbspacer'}}
if(componentDisplayOption.zoomToMaxExtentButtonEnable){this.zoomToMaxExtentButton=new Ext.Toolbar.Button({iconCls:'zoomToScaleBtn',tooltip:EasySDI_Map.lang.getLocal('MP_ZOOM_TO_EXTENT_TTIP'),enableToggle:false,allowDepress:false,handler:function(){this._zoomToMaxExtent();},scope:this});}else{this.zoomToMaxExtentButton={xtype:'tbspacer'}}
if(componentDisplayOption.printMapButtonEnable){this.printMapButton=new Ext.Toolbar.Button({iconCls:'printMapBtn',tooltip:EasySDI_Map.lang.getLocal('MP_PRINT_VERSION_TTIP'),enableToggle:true,allowDepress:false,handler:this._updateCtrlBtns,scope:this});}else{this.printMapButton={xtype:'tbspacer'}}
if(componentDisplayOption.saveMapButtonEnable){this.saveMapButton=new Ext.Toolbar.Button({iconCls:'saveMapBtn',tooltip:EasySDI_Map.lang.getLocal('MP_SAVE_AS_IMAGE_TTIP'),enableToggle:true,allowDepress:false,handler:this._updateCtrlBtns,scope:this});}else{this.saveMapButton={xtype:'tbspacer'}}
if(componentDisplayOption.pdfButtonEnable){this.pdfButton=new Ext.Toolbar.Button({iconCls:'pdfBtn',tooltip:EasySDI_Map.lang.getLocal('MP_PDF'),enableToggle:true,allowDepress:false,handler:this._updateCtrlBtns,scope:this});}else{this.pdfButton={xtype:'tbspacer'}}
if(componentDisplayOption.getFeatureButtonEnable){this.getFeatureButton=new Ext.Toolbar.Button({iconCls:'selectBtn',tooltip:EasySDI_Map.lang.getLocal('MP_SELECT_BUTTON_TOOLTIP'),enableToggle:true,toggleGroup:'mapCtrl',allowDepress:false,handler:this._updateCtrlBtns,scope:this});}else{this.getFeatureButton={xtype:'tbspacer'}}
return new Ext.Toolbar({region:"north",autoHeight:true,items:[this.previousButton,this.nextButton,{xtype:'tbseparator'},this.zoomInBoxButton,this.zoomOutBoxButton,this.zoomToMaxExtentButton,this.navButton,this.getFeatureButton,{xtype:'tbseparator'},showScale?EasySDI_Map.lang.getLocal('1:'):{xtype:'tbfill'},this.zoomToScaleField,{xtype:'tbseparator'},this.saveMapButton,this.printMapButton,this.pdfButton,{xtype:'tbfill'},componentDisplayOption.locAutocompleteEnable?EasySDI_Map.lang.getLocal('MP_ZOOM'):{xtype:'tbspacer'},this.locAutocomplete]});},_createAnnotationStyleDropDownItems:function(){var styleDropDownItems=[];var first=true;Ext.each(annotationStyle,function(style){var item=style;first?item.checked=true:item.checked=false;item.group='theme';item.checkHandler=this._onAnnotationStyleSelect;item.scope=this;styleDropDownItems.push(item);if(first){this.defaultAnnotationStyle=item;}
first=false;},this);return styleDropDownItems;},_onAnnotationStyleSelect:function(item,checked){if(!item){item=this.defaultAnnotationStyle;}else{this.rectangleButton.toggle(false);this.polygonButton.toggle(false);this.pointButton.toggle(false);this.modifyFeatureButton.toggle(false);this.pathButton.toggle(false);this.selectFeatureButton.toggle(false);this.printMapButton.toggle(false);this.rectControl.deactivate();this.polyControl.deactivate();this.pointControl.deactivate();this.modifyFeatureControl.deactivate();this.pathControl.deactivate();this.selectControl.deactivate();}
if(checked){if(!item)
return;this.template={pointRadius:item.pointRadius,fillColor:item.fillColor,fillOpacity:item.fillOpacity,strokeColor:item.strokeColor,strokeWidth:item.strokeWidth,strokeOpacity:item.strokeOpacity,stroke:item.stroke,fill:item.fill,externalGraphic:item.externalGraphic,graphicWidth:item.graphicWidth,graphicHeight:item.graphicHeight,graphicYOffset:item.graphicYOffset,graphicXOffset:item.graphicXOffset,graphicOpacity:item.graphicOpacity};var style={"default":new OpenLayers.Style(this.template)};var exists=false;for(i=0;i<this.map.layers.length;i++){if(this.map.layers[i].name===item.text){this.vectors=this.map.layers[i];this.vectors.styleMap=new OpenLayers.StyleMap(style);exists=true;break;}}
if(!exists){this.vectors=new OpenLayers.Layer.Vector(item.text,{isBaseLayer:false,transparent:"true",styleMap:new OpenLayers.StyleMap(style)});this.vectors.events.register("featureadded",this,function(myEvent){this.refreshLegend();});this.vectors.events.register("featureremoved",this,function(myEvent){this.refreshLegend();});this.map.addLayer(this.vectors);if(!this.vectorsLayersArray){this.vectorsLayersArray=[];}
this.vectorsLayersArray.push(this.vectors);}
if(componentDisplayOption.rectangleButtonEnable){if(!this.rectControl){this.rectControl=new OpenLayers.Control.DrawFeature(this.vectors,OpenLayers.Handler.RegularPolygon);this.rectControl.handler.setOptions({irregular:true});this.map.addControl(this.rectControl);}else{this.rectControl.layer=this.vectors;}}
if(componentDisplayOption.polygonButtonEnable){if(!this.polyControl){this.polyControl=new OpenLayers.Control.DrawFeature(this.vectors,OpenLayers.Handler.Polygon);this.map.addControl(this.polyControl);}else{this.polyControl.layer=this.vectors;}}
if(componentDisplayOption.pointButtonEnable){if(!this.pointControl){this.pointControl=new OpenLayers.Control.DrawFeature(this.vectors,OpenLayers.Handler.Point);this.map.addControl(this.pointControl);}else{this.pointControl.layer=this.vectors;}}
if(componentDisplayOption.modifyFeatureButtonEnable){if(this.modifyFeatureControl){this.modifyFeatureControl.destroy();}
this.modifyFeatureControl=new OpenLayers.Control.ModifyFeature(this.vectors);this.map.addControl(this.modifyFeatureControl);}
if(componentDisplayOption.pathButtonEnable){if(!this.pathControl){this.pathControl=new OpenLayers.Control.DrawFeature(this.vectors,OpenLayers.Handler.Path);this.map.addControl(this.pathControl);}else{this.pathControl.layer=this.vectors;}}
if(componentDisplayOption.selectFeatureButtonEnable){if(!this.selectControl){this.selectControl=new OpenLayers.Control.SelectFeature(this.vectorsLayersArray,{box:true,onSelect:function(feature){feature.destroy();}});this.map.addControl(this.selectControl);}else{this.selectControl.layers=this.vectorsLayersArray;}}}},_updateCtrlBtns:function(){if(componentDisplayOption.navButtonEnable){if(this.navButton.pressed){this.navCtrl.activate();}else{this.navCtrl.deactivate();}}
if(componentDisplayOption.selectButtonEnable){if(this.selectButton.pressed){this.selectFeatureCtrl.activate();}else{this.selectFeatureCtrl.deactivate();}}
if(componentDisplayOption.zoomInBoxButtonEnable){if(this.zoomInBoxButton.pressed){this.zoomInBoxCtrl.activate();}else{this.zoomInBoxCtrl.deactivate();}}
if(componentDisplayOption.zoomOutBoxButtonEnable){if(this.zoomOutBoxButton.pressed){this.zoomOutBoxCtrl.activate();}else{this.zoomOutBoxCtrl.deactivate();}}
if(componentDisplayOption.printMapButtonEnable){if(this.printMapButton.pressed){window.open(componentParams.componentUrl+'&view=printMap&mapPanel='+this._encodeCurrentMap()+'&mapPanelHeight='
+this.map.getCurrentSize().h+'&mapPanelWidth='+this.map.getCurrentSize().w,'_blank');this.printMapButton.toggle(false);}}
if(componentDisplayOption.saveMapButtonEnable){if(this.saveMapButton.pressed){var popup=new EasySDI_Map.Dlg.SaveAsPopup({mapPanel:this});popup.show();this.saveMapButton.toggle(false);}}
if(componentDisplayOption.pdfButtonEnable){if(this.pdfButton.pressed){var popup=new EasySDI_Map.Dlg.InputPDFTitle({mapPanel:this});popup.show();this.pdfButton.toggle(false);}}
if(componentDisplayOption.rectangleButtonEnable){if(this.rectangleButton.pressed){this.rectControl.activate();}else{this.rectControl.deactivate();}}
if(componentDisplayOption.polygonButtonEnable){if(this.polygonButton.pressed){this.polyControl.activate();}else{this.polyControl.deactivate();}}
if(componentDisplayOption.pointButtonEnable){if(this.pointButton.pressed){this.pointControl.activate();}else{this.pointControl.deactivate();}}
if(componentDisplayOption.modifyFeatureButtonEnable){if(this.modifyFeatureButton.pressed){this.modifyFeatureControl.activate();}else{this.modifyFeatureControl.deactivate();}}
if(componentDisplayOption.pathButtonEnable){if(this.pathButton.pressed){this.pathControl.activate();}else{this.pathControl.deactivate();}}
if(componentDisplayOption.selectFeatureButtonEnable){if(this.selectFeatureButton.pressed){this.selectControl.activate();}else{this.selectControl.deactivate();}}
if(componentDisplayOption.getFeatureButtonEnable){if(this.getFeatureButton.pressed){this.getFeatureCtrl.activate();}else{this.getFeatureCtrl.deactivate();}}},_encodeCurrentMap:function(){var currentMap={};currentMap.extent=this.map.getExtent();currentMap.basemap=this.map.baseLayer.params.LAYERS;currentMap.basemapVisible=this.map.baseLayer.getVisibility();var currentLayers=[];var count=0;for(i=0;i<this.map.layers.length;i++){if(this.map.layers[i].getVisibility()){var l=this.map.layers[i];var currentLayer={}
currentLayer.name=(l.CLASS_NAME=='OpenLayers.Layer.Vector')?l.name:l.params.LAYERS;var geometries='';var featGeom={};if(l.isVector){for(j=0;j<l.features.length;j++){var feature=l.features[j];featGeom.value=feature.geometry;;geometries+=feature.geometry;if(j<l.features.length-1){geometries+=";";}}
currentLayer.features=geometries;}
currentLayers[count]=currentLayer;count+=1;}}
currentMap.layers=currentLayers;var styles=Ext.state.Manager.get('overlayLayerStyle',null);currentMap.style=styles;return JSON.stringify(currentMap)},_getOneImageMapURL:function(img_format){var styles=Ext.state.Manager.get('overlayLayerStyle',null);var url='';url+=componentParams.pubWmsUrl;url+="?LAYERS=";var found=false;Ext.each(this.map.layers,function(layer){if(layer.inRange&&layer.getVisibility()&&layer.CLASS_NAME=="OpenLayers.Layer.WMS")
url+=layer.params.LAYERS+",";found=true;},this);if(found){url=url.substr(0,url.length-1);}
url+="&VERSION="+componentParams.pubWmsVersion+"&SRS="+componentParams.projection+"&FORMAT="+img_format
+"&SERVICE=WMS&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&BBOX=";url+=this.map.getExtent().left+","+this.map.getExtent().bottom+","+this.map.getExtent().right+","
+this.map.getExtent().top;url+="&WIDTH="+this.GeoExtMapPanel.getSize().width+"&HEIGHT="+this.GeoExtMapPanel.getSize().height;var sld="";var first=true;if(styles){for(i=0;i<this.map.layers.length;i++){if(this.map.layers[i].getVisibility()){Ext.each(SData.overlayLayers,function(layer){if(layer.name==this.map.layers[i].name){if(styles&&styles[layer.id]){if(first){url+="&SLD_BODY=";sld+=EasySDI_Map.StyledLayerDescriptor.getSLDHeader();first=false;}
sld+=EasySDI_Map.StyledLayerDescriptor.getSLD(layer.layers,styles[layer.id].fillColor,styles[layer.id].opacity,styles[layer.id].strokeColor);}}},this);}}
if(!first){sld+=EasySDI_Map.StyledLayerDescriptor.getSLDFooter();sld=encodeURIComponent(sld);}}
url+=sld;return url;},_zoomToScale:function(scale){this.map.zoomToScale(scale);},_zoomToMaxExtent:function(){this.map.zoomToExtent(componentParams.mapMaxExtent);},onProjChecked:function(item){if(item.checked){this.projMenuButton.setText(item.text);this.mousePos.displayProjection=new OpenLayers.Projection(componentParams.displayProjections[item.stateId].name);this.mousePos.numDigits=componentParams.displayProjections[item.stateId].numDigits;}},createOverviewBaseLayer:function(layer){var extraOptions={isBaseLayer:true,singleTile:layer.singletile,buffer:0,opacity:layer.defaultOpacity,projection:layer.projection}
if(layer.customStyle!=undefined)
extraOptions.customStyle=layer.customStyle;if(layer.units!=undefined)
extraOptions.units=layer.units;else if(extraOptions.units!=undefined)
extraOptions.units=this.map.units;else{}
if(layer.maxExtent!=undefined)
extraOptions.maxExtent=layer.maxExtent;else if(this.map.maxExtent!=undefined)
extraOptions.maxExtent=this.map.maxExtent;else{}
if(layer.minScale!=undefined)
extraOptions.minScale=layer.minScale;else if(this.map.minScale!=undefined)
extraOptions.minScale=this.map.minScale;else{}
if(layer.maxScale!=undefined)
extraOptions.maxScale=layer.maxScale;else if(this.map.maxScale!=undefined)
extraOptions.maxScale=this.map.maxScale;else{}
if(layer.resolutions!=undefined)
extraOptions.resolutions=layer.resolutions;if(layer.minResolution!=undefined)
extraOptions.minResolution=layer.minResolution;if(layer.maxResolution!=undefined)
extraOptions.maxResolution=layer.maxResolution;if(layer.resolutions==undefined&&layer.minResolution==undefined&&layer.maxResolution==undefined){extraOptions.minResolution="auto";extraOptions.maxResolution="auto";}
var l=null;switch(layer.type.toUpperCase()){case'WMTS':extraOptions.name=layer.name;extraOptions.url=layer.url;extraOptions.layer=layer.layers;extraOptions.matrixSet=layer.matrixSet;if(layer.matrixIds!=undefined)
extraOptions.matrixIds=layer.matrixIds;if(layer.style!=undefined)
extraOptions.style=layer.style;extraOptions.format=layer.imageFormat;extraOptions.matrix=layer.matrix;l=new OpenLayers.Layer.WMTS(extraOptions);l.grid=[];l.map=null;break;case'WMS':var WMSoptions={LAYERS:layer.layers,SERVICE:layer.type,VERSION:layer.version,STYLES:'',SRS:layer.projection,FORMAT:layer.imageFormat};if(layer.cache)
WMSoptions.CACHE=true;l=new OpenLayers.Layer.WMS(layer.name,layer.url,WMSoptions,extraOptions);if(layer.cache)
l.params.CACHE=true;break;}
console.log("overviewlayercreated");console.log(l.clone());return l;}});Ext.mixin(EasySDI_Map.MapPanel,EasySDI_Map.TriggerManager);