
Ext.namespace("GeoExt.tree");GeoExt.tree.LayerNode=Ext.extend(GeoExt.tree.TristateCheckboxNode,{layer:null,map:null,haveLayer:null,updating:false,constructor:function(config){this.layer=config.layer;this.map=config.map;this.haveLayer=false;config.leaf=config.leaf||!config.children;config.iconCls=typeof config.iconCls=="undefined"&&!config.children?"layer-icon":config.iconCls;config.checked=false;this.defaultUI=this.defaultUI||GeoExt.tree.LayerNodeUI;this.addEvents.apply(this,GeoExt.tree.LayerNode.EVENT_TYPES);GeoExt.tree.LayerNode.superclass.constructor.apply(this,arguments);},render:function(bulkRender){if(!this.rendered||!this.haveLayer){var map=this.map instanceof OpenLayers.Map?this.map:(typeof this.map=="string"?Ext.getCmp(this.map).map:Ext.ComponentMgr.all.find(function(o){return o.map instanceof OpenLayers.Map;}).map);var layer=this.attributes.layer||this.layer;this.haveLayer=layer&&typeof layer=="object";if(typeof layer=="string"){var matchingLayers=map.getLayersByName(layer);if(matchingLayers.length>0){layer=matchingLayers[0];this.haveLayer=true;}}
var ui=this.getUI();if(this.haveLayer){this.attributes.layer=layer;if(layer.queryable==true){this.attributes.radioGroup=layer.map.id;}
if(!this.text){this.text=layer.name;}
ui.show();ui.toggleCheck(layer.getVisibility());layer.events.register("visibilitychanged",this,function(){this.updating=true;if(this.attributes.checked!=layer.getVisibility()){ui.toggleCheck(layer.getVisibility());}
this.updating=false;});this.on("checkchange",function(node,checked){if(!this.updating){if(checked&&layer.isBaseLayer){map.setBaseLayer(layer);}
layer.setVisibility(checked);}
if(!layer.isBaseLayer||checked){this.fireEvent("postcheckchange",this);}},this);this.attributes.checked=layer.getVisibility();}else{ui.hide();}
map.events.register("addlayer",this,function(e){if(layer==e.layer){this.getUI().show();}else if(layer==e.layer.name){this.render(bulkRender);return;}});map.events.register("removelayer",this,function(e){if(layer==e.layer){this.getUI().hide();}});}
GeoExt.tree.LayerNode.superclass.render.call(this,bulkRender);}});GeoExt.tree.LayerNode.EVENT_TYPES=["querylayerchange","postcheckchange"];Ext.tree.TreePanel.nodeTypes.gxLayer=GeoExt.tree.LayerNode;