//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.13 at 04:39:39 PM CET 
//


package ch.interlis.interlis2.GM03V18;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GM03Core.Core.GM_Object complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GM03Core.Core.GM_Object">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SURFACE">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BOUNDARY" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="POLYLINE" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;choice maxOccurs="unbounded" minOccurs="2">
 *                                       &lt;element name="COORD" type="{http://www.interlis.ch/INTERLIS2.2}CoordValue"/>
 *                                       &lt;element name="ARC" type="{http://www.interlis.ch/INTERLIS2.2}ArcPoint"/>
 *                                     &lt;/choice>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GM03Core.Core.GM_Object", propOrder = {
    "surface"
})
public class GM03CoreCoreGMObject {

    @XmlElement(name = "SURFACE", required = true)
    protected GM03CoreCoreGMObject.SURFACE surface;

    /**
     * Gets the value of the surface property.
     * 
     * @return
     *     possible object is
     *     {@link GM03CoreCoreGMObject.SURFACE }
     *     
     */
    public GM03CoreCoreGMObject.SURFACE getSURFACE() {
        return surface;
    }

    /**
     * Sets the value of the surface property.
     * 
     * @param value
     *     allowed object is
     *     {@link GM03CoreCoreGMObject.SURFACE }
     *     
     */
    public void setSURFACE(GM03CoreCoreGMObject.SURFACE value) {
        this.surface = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BOUNDARY" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="POLYLINE" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;choice maxOccurs="unbounded" minOccurs="2">
     *                             &lt;element name="COORD" type="{http://www.interlis.ch/INTERLIS2.2}CoordValue"/>
     *                             &lt;element name="ARC" type="{http://www.interlis.ch/INTERLIS2.2}ArcPoint"/>
     *                           &lt;/choice>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "boundary"
    })
    public static class SURFACE {

        @XmlElement(name = "BOUNDARY", required = true)
        protected List<GM03CoreCoreGMObject.SURFACE.BOUNDARY> boundary;

        /**
         * Gets the value of the boundary property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the boundary property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBOUNDARY().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GM03CoreCoreGMObject.SURFACE.BOUNDARY }
         * 
         * 
         */
        public List<GM03CoreCoreGMObject.SURFACE.BOUNDARY> getBOUNDARY() {
            if (boundary == null) {
                boundary = new ArrayList<GM03CoreCoreGMObject.SURFACE.BOUNDARY>();
            }
            return this.boundary;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="POLYLINE" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;choice maxOccurs="unbounded" minOccurs="2">
         *                   &lt;element name="COORD" type="{http://www.interlis.ch/INTERLIS2.2}CoordValue"/>
         *                   &lt;element name="ARC" type="{http://www.interlis.ch/INTERLIS2.2}ArcPoint"/>
         *                 &lt;/choice>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "polyline"
        })
        public static class BOUNDARY {

            @XmlElement(name = "POLYLINE", required = true)
            protected List<GM03CoreCoreGMObject.SURFACE.BOUNDARY.POLYLINE> polyline;

            /**
             * Gets the value of the polyline property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the polyline property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPOLYLINE().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link GM03CoreCoreGMObject.SURFACE.BOUNDARY.POLYLINE }
             * 
             * 
             */
            public List<GM03CoreCoreGMObject.SURFACE.BOUNDARY.POLYLINE> getPOLYLINE() {
                if (polyline == null) {
                    polyline = new ArrayList<GM03CoreCoreGMObject.SURFACE.BOUNDARY.POLYLINE>();
                }
                return this.polyline;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;choice maxOccurs="unbounded" minOccurs="2">
             *         &lt;element name="COORD" type="{http://www.interlis.ch/INTERLIS2.2}CoordValue"/>
             *         &lt;element name="ARC" type="{http://www.interlis.ch/INTERLIS2.2}ArcPoint"/>
             *       &lt;/choice>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "coordOrARC"
            })
            public static class POLYLINE {

                @XmlElements({
                    @XmlElement(name = "ARC", type = ArcPoint.class),
                    @XmlElement(name = "COORD", type = CoordValue.class)
                })
                protected List<Object> coordOrARC;

                /**
                 * Gets the value of the coordOrARC property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the coordOrARC property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getCOORDOrARC().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ArcPoint }
                 * {@link CoordValue }
                 * 
                 * 
                 */
                public List<Object> getCOORDOrARC() {
                    if (coordOrARC == null) {
                        coordOrARC = new ArrayList<Object>();
                    }
                    return this.coordOrARC;
                }

            }

        }

    }

}
