//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.13 at 04:39:39 PM CET 
//


package ch.interlis.interlis2.GM03V18;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GM03Comprehensive.Comprehensive.MD_MaintenanceFrequencyCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GM03Comprehensive.Comprehensive.MD_MaintenanceFrequencyCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="continual"/>
 *     &lt;enumeration value="daily"/>
 *     &lt;enumeration value="weekly"/>
 *     &lt;enumeration value="fortnightly"/>
 *     &lt;enumeration value="monthly"/>
 *     &lt;enumeration value="quarterly"/>
 *     &lt;enumeration value="biannually"/>
 *     &lt;enumeration value="annually"/>
 *     &lt;enumeration value="asNeeded"/>
 *     &lt;enumeration value="irregular"/>
 *     &lt;enumeration value="notPlanned"/>
 *     &lt;enumeration value="unknown"/>
 *     &lt;enumeration value="userDefined"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GM03Comprehensive.Comprehensive.MD_MaintenanceFrequencyCode")
@XmlEnum
public enum GM03ComprehensiveComprehensiveMDMaintenanceFrequencyCode {

    @XmlEnumValue("continual")
    CONTINUAL("continual"),
    @XmlEnumValue("daily")
    DAILY("daily"),
    @XmlEnumValue("weekly")
    WEEKLY("weekly"),
    @XmlEnumValue("fortnightly")
    FORTNIGHTLY("fortnightly"),
    @XmlEnumValue("monthly")
    MONTHLY("monthly"),
    @XmlEnumValue("quarterly")
    QUARTERLY("quarterly"),
    @XmlEnumValue("biannually")
    BIANNUALLY("biannually"),
    @XmlEnumValue("annually")
    ANNUALLY("annually"),
    @XmlEnumValue("asNeeded")
    AS_NEEDED("asNeeded"),
    @XmlEnumValue("irregular")
    IRREGULAR("irregular"),
    @XmlEnumValue("notPlanned")
    NOT_PLANNED("notPlanned"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),
    @XmlEnumValue("userDefined")
    USER_DEFINED("userDefined");
    private final String value;

    GM03ComprehensiveComprehensiveMDMaintenanceFrequencyCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GM03ComprehensiveComprehensiveMDMaintenanceFrequencyCode fromValue(String v) {
        for (GM03ComprehensiveComprehensiveMDMaintenanceFrequencyCode c: GM03ComprehensiveComprehensiveMDMaintenanceFrequencyCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
