UPDATE jos_sdi_searchcriteria SET rendertype_id = 5 WHERE `name` = 'fulltext';
UPDATE jos_sdi_searchcriteria SET rendertype_id = 2, `name` = 'resourcetype' WHERE `name` = 'objecttype';
UPDATE jos_sdi_searchcriteria SET rendertype_id = 3 WHERE `name` = 'versions';
UPDATE jos_sdi_searchcriteria SET rendertype_id = 5, `name` = 'resourcename' WHERE `name` = 'code';
UPDATE jos_sdi_searchcriteria SET rendertype_id = 6 WHERE `name` = 'metadata_created';
UPDATE jos_sdi_searchcriteria SET rendertype_id = 6 WHERE `name` = 'metadata_published';
INSERT INTO `jos_sdi_searchcriteria` VALUES (null, 'ec4730bb-1fed-4adb-8b15-6c2b3fdfb945', 'organism', '356', '2013-06-17 11:22:36', null, null, '0', '1', '0', '0000-00-00 00:00:00', 'organism', '1', '1', '1', null, '0', '0');
UPDATE jos_sdi_searchcriteria SET rendertype_id = 4 WHERE `name` = 'definedBoundary';
UPDATE jos_sdi_searchcriteria SET rendertype_id = 2 WHERE `name` = 'isDownloadable';
UPDATE jos_sdi_searchcriteria SET rendertype_id = 2 WHERE `name` = 'isFree';
UPDATE jos_sdi_searchcriteria SET rendertype_id = 2 WHERE `name` = 'isOrderable';
UPDATE jos_sdi_searchcriteria SET rendertype_id = 2 WHERE `name` = 'isViewable';
