package org.easysdi.domain;

// Generated Mar 14, 2013 5:38:18 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProxySdiUser generated by hbm2java
 */
@Entity
@Table(name = "proxy_sdi_user", catalog = "proxy330")
public class ProxySdiUser implements java.io.Serializable {

	private Integer id;
	private String guid;
	private int createdBy;
	private Date created;
	private Integer modifiedBy;
	private Date modified;
	private Integer ordering;
	private boolean state;
	private int checkedOut;
	private Date checkedOutTime;
	private int userId;
	private String description;
	private boolean notificationrequesttreatment;
	private Integer catid;
	private String params;
	private int access;
	private Integer assetId;

	public ProxySdiUser() {
	}

	public ProxySdiUser(String guid, int createdBy, Date created,
			boolean state, int checkedOut, Date checkedOutTime, int userId,
			boolean notificationrequesttreatment, int access) {
		this.guid = guid;
		this.createdBy = createdBy;
		this.created = created;
		this.state = state;
		this.checkedOut = checkedOut;
		this.checkedOutTime = checkedOutTime;
		this.userId = userId;
		this.notificationrequesttreatment = notificationrequesttreatment;
		this.access = access;
	}

	public ProxySdiUser(String guid, int createdBy, Date created,
			Integer modifiedBy, Date modified, Integer ordering, boolean state,
			int checkedOut, Date checkedOutTime, int userId,
			String description, boolean notificationrequesttreatment,
			Integer catid, String params, int access, Integer assetId) {
		this.guid = guid;
		this.createdBy = createdBy;
		this.created = created;
		this.modifiedBy = modifiedBy;
		this.modified = modified;
		this.ordering = ordering;
		this.state = state;
		this.checkedOut = checkedOut;
		this.checkedOutTime = checkedOutTime;
		this.userId = userId;
		this.description = description;
		this.notificationrequesttreatment = notificationrequesttreatment;
		this.catid = catid;
		this.params = params;
		this.access = access;
		this.assetId = assetId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "guid", nullable = false, length = 36)
	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "modified_by")
	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 19)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Column(name = "ordering")
	public Integer getOrdering() {
		return this.ordering;
	}

	public void setOrdering(Integer ordering) {
		this.ordering = ordering;
	}

	@Column(name = "state", nullable = false)
	public boolean isState() {
		return this.state;
	}

	public void setState(boolean state) {
		this.state = state;
	}

	@Column(name = "checked_out", nullable = false)
	public int getCheckedOut() {
		return this.checkedOut;
	}

	public void setCheckedOut(int checkedOut) {
		this.checkedOut = checkedOut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checked_out_time", nullable = false, length = 19)
	public Date getCheckedOutTime() {
		return this.checkedOutTime;
	}

	public void setCheckedOutTime(Date checkedOutTime) {
		this.checkedOutTime = checkedOutTime;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "notificationrequesttreatment", nullable = false)
	public boolean isNotificationrequesttreatment() {
		return this.notificationrequesttreatment;
	}

	public void setNotificationrequesttreatment(
			boolean notificationrequesttreatment) {
		this.notificationrequesttreatment = notificationrequesttreatment;
	}

	@Column(name = "catid")
	public Integer getCatid() {
		return this.catid;
	}

	public void setCatid(Integer catid) {
		this.catid = catid;
	}

	@Column(name = "params", length = 1024)
	public String getParams() {
		return this.params;
	}

	public void setParams(String params) {
		this.params = params;
	}

	@Column(name = "access", nullable = false)
	public int getAccess() {
		return this.access;
	}

	public void setAccess(int access) {
		this.access = access;
	}

	@Column(name = "asset_id")
	public Integer getAssetId() {
		return this.assetId;
	}

	public void setAssetId(Integer assetId) {
		this.assetId = assetId;
	}

}
