//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.07 at 04:52:04 PM CET 
//


package net.opengis.cat.csw.v201;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import net.opengis.ows.BoundingBoxType;
import net.opengis.ows.WGS84BoundingBoxType;


/**
 * 
 *       This type extends DCMIRecordType to add ows:BoundingBox; it may be 
 *       used to specify a spatial envelope for the catalogued resource.
 *       
 * 
 * <p>Java class for RecordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecordType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/cat/csw}DCMIRecordType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/ows}BoundingBox" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecordType", propOrder = {
    "boundingBox"
})
public class RecordType
    extends DCMIRecordType
{

    @XmlElementRef(name = "BoundingBox", namespace = "http://www.opengis.net/ows", type = JAXBElement.class)
    protected JAXBElement<? extends BoundingBoxType> boundingBox;

    /**
     * Gets the value of the boundingBox property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link WGS84BoundingBoxType }{@code >}
     *     {@link JAXBElement }{@code <}{@link BoundingBoxType }{@code >}
     *     
     */
    public JAXBElement<? extends BoundingBoxType> getBoundingBox() {
        return boundingBox;
    }

    /**
     * Sets the value of the boundingBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link WGS84BoundingBoxType }{@code >}
     *     {@link JAXBElement }{@code <}{@link BoundingBoxType }{@code >}
     *     
     */
    public void setBoundingBox(JAXBElement<? extends BoundingBoxType> value) {
        this.boundingBox = ((JAXBElement<? extends BoundingBoxType> ) value);
    }

}
