
Ext.namespace("EasySDI_Map");EasySDI_Map.LegendPanel=function(config){Ext.apply(this,config);EasySDI_Map.LegendPanel.superclass.constructor.call(this);};EasySDI_Map.LegendPanel.LEGENDURL=1;EasySDI_Map.LegendPanel.GETLEGENDGRAPHIC=0;EasySDI_Map.LegendPanel=Ext.extend(Ext.Panel,{layerTree:null,constructor:function(config){EasySDI_Map.LegendPanel.superclass.constructor.apply(this,arguments);},refresh:function(){if(typeof this.items!=="undefined"){this.removeAll(true);}
var layersToDo=[].concat(this.map.layers);Ext.each(this.layerTree.root.childNodes,function(group){Ext.each(group.childNodes,function(layerNode){OpenLayers.Util.removeItem(layersToDo,layerNode.layer);},this);},this);layersToDo.reverse();Ext.each(layersToDo,function(layer){if(layer.displayInLayerSwitcher)
{if(layer instanceof OpenLayers.Layer.Vector)
{if(layer.features.length>0)
{var styleToApply='';var styleToApplyToLine='';var styleToApplyToPoint='';var bodystyleToApply='';Ext.each(annotationStyle,function(style)
{if(style.text==layer.name)
{styleToApply="border: solid "+style.strokeColor+" 1px; ";styleToApplyToLine="border-top: solid 1px "+style.strokeColor+";border-left: solid 1px "+style.strokeColor+";";bodystyleToApply="background-color: "+style.fillColor+"; opacity:"+style.fillOpacity+";filter:alpha(opacity="+style.fillOpacity*100+")";styleToApplyToPoint="background-image:url('"+style.externalGraphic+"');";}});var panel=new Ext.Panel({layout:'column',border:false,items:[new Ext.form.Label({text:layer.name}),new Ext.Panel({style:'',bodyStyle:'"'+styleToApplyToPoint+'"',cls:"legend-icon",border:false}),new Ext.Panel({style:'"'+styleToApplyToLine+'"',bodyStyle:'',cls:"graphic",border:false}),new Ext.Panel({style:'"'+styleToApply+'"',bodyStyle:'"'+bodystyleToApply+'"',cls:"graphic",border:false})]});this.add(panel);}}
else
{var panel=new Ext.Panel({layout:'column',baseCls:'legend x-panel',border:false,items:[new Ext.form.Label({text:layer.name})]});if(layer instanceof OpenLayers.Layer.WMS)
{this._addServerWMSLegend(panel,layer);}
else
{panel.add(new Ext.Panel({style:"border: solid #3399ff 1px;",cls:"graphic",border:false}));}
this.add(panel);}}},this);Ext.each(this.layerTree.root.childNodes,function(group){Ext.each(group.childNodes,function(layerNode){if(this._isVisible(layerNode)&&this._isInScaleRange(layerNode)){var panel=new Ext.Panel({layout:'column',border:false,baseCls:'legend x-panel',items:[new Ext.form.Label({text:layerNode.text})]});if(layerNode.fillColor!==null&&typeof layerNode.strokeColor!=="undefined"){panel.add(new Ext.Panel({style:"border: solid #"+layerNode.strokeColor+" 1px;",bodyStyle:"background-color: #"+layerNode.fillColor+"; opacity:"+layerNode.opacity+";filter:alpha(opacity="+layerNode.opacity*100+")",cls:"graphic",border:false}));}else{if(layerNode.layer instanceof OpenLayers.Layer.WMS){if(layerNode.layer.isBaseLayer){panel.add(new Ext.Panel({width:18,height:18,style:"margin: 3px;",bodyStyle:"opacity: 0",cls:"baseLayer",border:false}));}else{this._addServerWMSLegend(panel,layerNode.layer);}}else{panel.add(new Ext.Panel({style:"border: solid #ee9900 1px;",bodyStyle:"background-color: #ee9900; opacity: 0.4; filter:alpha(opacity=50)",cls:"graphic",border:false}));}}
this.add(panel);}},this);},this);if(this.rendered){this.doLayout();}},_isVisible:function(layerNode){if(layerNode.ui.rendered){return layerNode.ui.isChecked()||typeof layerNode.ui.checkbox=="undefined";}else if(layerNode.layer!==undefined){return layerNode.layer.getVisibility()||typeof layerNode.layer.getVisibility=="undefined";}else{return false;}},_isInScaleRange:function(layerNode){if(layerNode.isInScaleRange||layerNode.isInScaleRange=="undefined"){return true;}else{return false;}},_addServerWMSLegend:function(panel,layer){var layers=layer.params.LAYERS.split(",");var legImg=[];for(var i=0;i<layers.length;i++){var layerName=layers[i];legImg.push(this._createImage((layer.legendURL?layer.legendURL:this._getLegendUrl(layer,layerName)),this._generatePanelId(layer)+i,layer));}
for(i=0;i<legImg.length;i++){panel.add(new Ext.BoxComponent({el:legImg[i]}));}},_createImage:function(src,id,layer){var legendImage=document.createElement("img");Ext.EventManager.addListener(legendImage,'error',this.onImageLoadError,{img:legendImage,lyr:layer});legendImage.src=src;legendImage.id=id+'_img';return legendImage;},_getLegendUrl:function(layer,layerName){var url;if(this.wmsMode==EasySDI_Map.LegendPanel.GETLEGENDGRAPHIC){url=layer.getFullRequestString({REQUEST:"GetLegendGraphic",WIDTH:null,HEIGHT:null,EXCEPTIONS:"application/vnd.ogc.se_xml",LAYER:layerName,LAYERS:null,STYLE:layer.params.STYLES,STYLES:null,FILTER:null,SRS:null,FORMAT:this.wmsLegendFormat,VERSION:layer.params.VERSION});layer.legendURL=url;return url;}},_generatePanelId:function(layer){if(layer&&layer.params){return this.idPrefix+layer.params.LAYERS+layer.name;}},onImageLoadError:function(){this.img.src=Ext.BLANK_IMAGE_URL;this.lyr.legendURL=null;}});