INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'العربية', 'ar-DZ', 'ar', 'ara', 'ar', 'DZ', 'ara');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'български език', 'bg-BG', 'bg', 'bul', 'bg', 'BG', 'bul');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'català', 'ca-ES', 'ca', 'cat', 'ca', 'ES', 'cat');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'čeština', 'cs-CZ', 'cs', 'ces', 'cs', 'CZ', 'cze');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'dansk', 'da-DK', 'da', 'dan', 'da', 'DK', 'dan');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'Deutsch', 'de-DE', 'de', 'deu', 'de', 'DE', 'ger');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'ελληνικά', 'el-GR', 'el', 'ell', 'el', 'GR', 'gre');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'English (UK)', 'en-GB', 'en', 'eng', 'en', 'GB', 'eng');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'English (US)', 'en-US', 'en-US', 'eng', 'en', 'US', 'eng');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'español', 'es-ES', 'es', 'spa', 'es', 'ES', 'spa');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'eesti', 'et-EE', 'et', 'est', 'et', 'EE', 'est');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'euskara', 'eu-ES', 'eu', 'eus', 'eu', 'ES', 'baq');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'suomi', 'fi-FI', 'fi', 'fin', 'fi', 'FI', 'fin');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'Français', 'fr-FR', 'fr', 'fra', 'fr', 'FR', 'fre');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'Gaeilge', 'ga-IE', 'ga', 'gle', 'ga', 'IE', 'gle');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'hrvatski jezik', 'hr-HR', 'hr', 'scr', 'hr', 'HR', 'hrv');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'magyar', 'hu-HU', 'hu', 'hun', 'hu', 'HU', 'hun');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'italiano', 'it-IT', 'it', 'ita', 'it', 'IT', 'ita');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'lietuvių kalba', 'lt-LT', 'lt', 'lit', 'lt', 'LT', 'lit');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'latviešu valoda', 'lv-LV', 'lv', 'lav', 'lv', 'LV', 'lav');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'Malti', 'mt-MT', 'mt', 'mlt', 'mt', 'MT', 'mlt');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'Nederlands', 'nl-NL', 'nl', 'nld', 'nl', 'NL', 'dut');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'Norsk', 'no-NO', 'no', 'nor', 'no', 'NO', 'nor');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'język polski', 'pl-PL', 'pl', 'pol', 'pl', 'PL', 'pol');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'português', 'pt-PT', 'pt', 'por', 'pt', 'PT', 'por');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'română', 'ro-RO', 'ro', 'ron', 'ro', 'RO', 'rum');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'русский язык', 'ru-RU', 'ru', 'rus', 'ru', 'RU', 'rus');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'slovenčina', 'sk-SK', 'sk', 'slk', 'sk', 'SK', 'slo');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'Svenska', 'sv-SE', 'sv', 'swe', 'sv', 'SE', 'swe');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'Türkçe', 'tr-TR', 'tr', 'tur', 'tr', 'TR', 'tur');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'українська мова', 'uk-UA', 'uk', 'ukr', 'uk', 'UA', 'ukr');
INSERT INTO #__sdi_language (ordering, state, value, code, gemet, "iso639-2T", "iso639-1", "iso3166-1-alpha2", "iso639-2B") VALUES (0, 1, 'Chinese', 'zh-CN', 'zh-CN', 'zho', 'zh', 'CN', 'chi');

INSERT INTO #__sdi_namespace (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, prefix, uri, system, access, asset_id) VALUES ('6df1fcd1-0a57-8b74-cd21-354dc5ef0b3d', 'gmd', 356, '2013-06-21 12:12:47', NULL, NULL, 1, 1, 0, '2013-06-21 12:12:47', 'gmd', 'gmd', 'http://www.isotc211.org/2005/gmd', 1, 1, 0);
INSERT INTO #__sdi_namespace (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, prefix, uri, system, access, asset_id) VALUES ('016318b2-29ec-3a74-c161-14aa1b1d3b97', 'gco', 356, '2013-06-21 12:12:47', NULL, NULL, 2, 1, 0, '2013-06-21 12:12:47', 'gco', 'gco', 'http://www.isotc211.org/2005/gco', 1, 1, 0);
INSERT INTO #__sdi_namespace (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, prefix, uri, system, access, asset_id) VALUES ('3e31cc00-8fa3-97a4-8510-dac7e4bac992', 'gml', 356, '2013-06-21 12:12:47', NULL, NULL, 3, 1, 0, '2013-06-21 12:12:47', 'gml', 'gml', 'http://www.opengis.net/gml', 1, 1, 0);
INSERT INTO #__sdi_namespace (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, prefix, uri, system, access, asset_id) VALUES ('d4b19594-af15-0b44-516b-22284be8dc66', 'sdi', 356, '2013-06-21 12:12:47', NULL, NULL, 4, 1, 0, '2013-06-21 12:12:47', 'sdi', 'sdi', 'http://www.easysdi.org/2011/sdi', 1, 1, 0);
INSERT INTO #__sdi_namespace (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, prefix, uri, system, access, asset_id) VALUES ('d84c3757-6471-49ed-a109-c8cef52840a8', 'catalog', 356, '2013-06-21 12:12:47', NULL, NULL, 5, 1, 0, '2013-06-21 12:12:47', 'catalog', 'catalog', 'http://www.easysdi.org/2011/sdi/catalog', 1, 1, 0);

INSERT INTO #__sdi_perimeter (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, description, accessscope_id, perimetertype_id, wfsservice_id, wfsservicetype_id, featuretypename, prefix, namespace, featuretypefieldid, featuretypefieldname, featuretypefieldsurface, featuretypefielddescription, featuretypefieldgeometry, featuretypefieldresource, wmsservice_id, wmsservicetype_id, layername, access, asset_id) VALUES ('1a9f342c-bb1e-9bc4-dd19-38910dff0f59', 'freeperimeter', 356, '2013-07-23 09:16:11', NULL, NULL, 1, 1, 0, '0002-11-30 00:00:00', 'Free perimeter', '', 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0);
INSERT INTO #__sdi_perimeter (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, description, accessscope_id, perimetertype_id, wfsservice_id, wfsservicetype_id, featuretypename, prefix, namespace, featuretypefieldid, featuretypefieldname, featuretypefieldsurface, featuretypefielddescription, featuretypefieldgeometry, featuretypefieldresource, wmsservice_id, wmsservicetype_id, layername, access, asset_id) VALUES ('9adc6d4e-262a-d6e4-e152-6de437ba80ed', 'myperimeter', 356, '2013-07-23 09:16:11', NULL, NULL, 2, 1, 0, '0002-11-30 00:00:00', 'My perimeter', '', 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0);

INSERT INTO #__sdi_searchcriteria (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, issystem, criteriatype_id, rendertype_id, relation_id, access, asset_id) VALUES ('58dfe161-60c3-4b72-b768-e4a09bae8cdb', 'fulltext', 356, '2013-06-17 11:22:36', NULL, NULL, 0, 1, 0, '2013-06-21 12:12:47', 'fulltext', 1, 1, 5, NULL, 0, 0);
INSERT INTO #__sdi_searchcriteria (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, issystem, criteriatype_id, rendertype_id, relation_id, access, asset_id) VALUES ('05b0fb40-459c-4ed2-a985-ce1611593969', 'resourcetype', 356, '2013-06-17 11:22:36', NULL, NULL, 0, 1, 0, '2013-06-21 12:12:47', 'resourcetype', 1, 1, 2, NULL, 0, 0);
INSERT INTO #__sdi_searchcriteria (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, issystem, criteriatype_id, rendertype_id, relation_id, access, asset_id) VALUES ('f839e3ae-d983-4366-b24f-2678f4cbe188', 'versions', 356, '2013-06-17 11:22:36', NULL, NULL, 0, 1, 0, '2013-06-21 12:12:47', 'versions', 1, 1, 2, NULL, 0, 0);
INSERT INTO #__sdi_searchcriteria (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, issystem, criteriatype_id, rendertype_id, relation_id, access, asset_id) VALUES ('4d402bfd-b50a-42ae-8db4-af8ef940575b', 'resourcename', 356, '2013-06-17 11:22:36', NULL, NULL, 0, 1, 0, '2013-06-21 12:12:47', 'resourcename', 1, 1, 5, NULL, 0, 0);
INSERT INTO #__sdi_searchcriteria (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, issystem, criteriatype_id, rendertype_id, relation_id, access, asset_id) VALUES ('2157fe2c-3705-4db9-a623-462ae38405fa', 'created', 356, '2013-06-17 11:22:36', NULL, NULL, 0, 1, 0, '2013-06-21 12:12:47', 'created', 1, 1, 6, NULL, 0, 0);
INSERT INTO #__sdi_searchcriteria (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, issystem, criteriatype_id, rendertype_id, relation_id, access, asset_id) VALUES ('979a4e90-601e-46fe-9239-9080e4238c1e', 'published', 356, '2013-06-17 11:22:36', NULL, NULL, 0, 1, 0, '2013-06-21 12:12:47', 'published', 1, 1, 6, NULL, 0, 0);
INSERT INTO #__sdi_searchcriteria (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, issystem, criteriatype_id, rendertype_id, relation_id, access, asset_id) VALUES ('f761bc2d-57ac-4252-9cd2-17ae5e92793b', 'organism', 356, '2013-06-17 11:22:36', NULL, NULL, 0, 1, 0, '2013-06-21 12:12:47', 'organism', 1, 1, 4, NULL, 0, 0);
INSERT INTO #__sdi_searchcriteria (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, issystem, criteriatype_id, rendertype_id, relation_id, access, asset_id) VALUES ('b2a4c66a-f40c-473d-a03f-5b5e4f93f760', 'definedBoundary', 356, '2013-06-17 11:22:36', NULL, NULL, 0, 1, 0, '2013-06-21 12:12:47', 'definedBoundary', 1, 1, 4, NULL, 0, 0);
INSERT INTO #__sdi_searchcriteria (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, issystem, criteriatype_id, rendertype_id, relation_id, access, asset_id) VALUES ('8a85ed55-6a9c-4af7-aba1-a3c0f8281453', 'isDownloadable', 356, '2013-06-17 11:22:36', NULL, NULL, 0, 1, 0, '2013-06-21 12:12:47', 'isDownloadable', 1, 1, 2, NULL, 0, 0);
INSERT INTO #__sdi_searchcriteria (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, issystem, criteriatype_id, rendertype_id, relation_id, access, asset_id) VALUES ('f80fcf1c-84df-4202-8838-6bbcb273a68d', 'isFree', 356, '2013-06-17 11:22:36', NULL, NULL, 0, 1, 0, '2013-06-21 12:12:47', 'isFree', 1, 1, 2, NULL, 0, 0);
INSERT INTO #__sdi_searchcriteria (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, issystem, criteriatype_id, rendertype_id, relation_id, access, asset_id) VALUES ('a9a44261-05da-4ee8-a3f2-4ec1c53bcb00', 'isOrderable', 356, '2013-06-17 11:22:36', NULL, NULL, 0, 1, 0, '2013-06-21 12:12:47', 'isOrderable', 1, 1, 2, NULL, 0, 0);
INSERT INTO #__sdi_searchcriteria (guid, alias, created_by, created, modified_by, modified, ordering, state, checked_out, checked_out_time, name, issystem, criteriatype_id, rendertype_id, relation_id, access, asset_id) VALUES ('a9a44261-05da-4ee8-a3f2-4ec1c53bcb00', 'isViewable', 356, '2013-06-17 11:22:36', NULL, NULL, 0, 1, 0, '2013-06-21 12:12:47', 'isViewable', 1, 1, 2, NULL, 0, 0);

INSERT INTO #__sdi_sys_accessscope (ordering, state, value) VALUES (1, 1, 'public');
INSERT INTO #__sdi_sys_accessscope (ordering, state, value) VALUES (3, 1, 'organism');
INSERT INTO #__sdi_sys_accessscope (ordering, state, value) VALUES (4, 1, 'user');
INSERT INTO #__sdi_sys_accessscope (ordering, state, `value`) VALUES (2, 1, 'category');

INSERT INTO #__sdi_sys_addresstype (ordering, state, value) VALUES (1, 1, 'contact');
INSERT INTO #__sdi_sys_addresstype (ordering, state, value) VALUES (2, 1, 'billing');
INSERT INTO #__sdi_sys_addresstype (ordering, state, value) VALUES (3, 1, 'delivry');

INSERT INTO #__sdi_sys_authenticationconnector (ordering, state, authenticationlevel_id, value) VALUES (1, 1, 1, 'HTTPBasic');
INSERT INTO #__sdi_sys_authenticationconnector (ordering, state, authenticationlevel_id, value) VALUES (2, 1, 2, 'Geonetwork');

INSERT INTO #__sdi_sys_authenticationlevel (ordering, state, value) VALUES (1, 1, 'resource');
INSERT INTO #__sdi_sys_authenticationlevel (ordering, state, value) VALUES (2, 1, 'service');

INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (1, 1, 'Afghanistan', 'AF', 'AFG');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (2, 1, 'Åland Islands', 'AX', 'ALA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (3, 1, 'Albania', 'AL', 'ALB');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (4, 1, 'Algeria (El Djazaïr)', 'DZ', 'DZA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (5, 1, 'American Samoa', 'AS', 'ASM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (6, 1, 'Andorra', 'AD', 'AND');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (7, 1, 'Angola', 'AO', 'AGO');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (8, 1, 'Anguilla', 'AI', 'AIA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (9, 1, 'Antarctica', 'AQ', 'ATA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (10, 1, 'Antigua and Barbuda', 'AG', 'ATG');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (11, 1, 'Argentina', 'AR', 'ARG');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (12, 1, 'Armenia', 'AM', 'ARM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (13, 1, 'Aruba', 'AW', 'ABW');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (14, 1, 'Australia', 'AU', 'AUS');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (15, 1, 'Austria', 'AT', 'AUT');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (16, 1, 'Azerbaijan', 'AZ', 'AZE');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (17, 1, 'Bahamas', 'BS', 'BHS');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (18, 1, 'Bahrain', 'BH', 'BHR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (19, 1, 'Bangladesh', 'BD', 'BGD');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (20, 1, 'Barbados', 'BB', 'BRB');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (21, 1, 'Belarus', 'BY', 'BLR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (22, 1, 'Belgium', 'BE', 'BEL');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (23, 1, 'Belize', 'BZ', 'BLZ');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (24, 1, 'Benin', 'BJ', 'BEN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (25, 1, 'Bermuda', 'BM', 'BMU');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (26, 1, 'Bhutan', 'BT', 'BTN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (27, 1, 'Bolivia', 'BO', 'BOL');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (28, 1, 'Bosnia and Herzegovina', 'BA', 'BIH');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (29, 1, 'Botswana', 'BW', 'BWA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (30, 1, 'Bouvet Island', 'BV', 'BVT');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (31, 1, 'Brazil', 'BR', 'BRA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (32, 1, 'British Indian Ocean Territory', 'IO', 'IOT');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (33, 1, 'Brunei Darussalam', 'BN', 'BRN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (34, 1, 'Bulgaria', 'BG', 'BGR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (35, 1, 'Burkina Faso', 'BF', 'BFA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (36, 1, 'Burundi', 'BI', 'BDI');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (37, 1, 'Cambodia', 'KH', 'KHM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (38, 1, 'Cameroon', 'CM', 'CMR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (39, 1, 'Canada', 'CA', 'CAN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (40, 1, 'Cape Verde', 'CV', 'CPV');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (41, 1, 'Cayman Islands', 'KY', 'CYM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (42, 1, 'Central African Republic', 'CF', 'CAF');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (43, 1, 'Chad (T''Chad)', 'TD', 'TCD');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (44, 1, 'Chile', 'CL', 'CHL');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (45, 1, 'China', 'CN', 'CHN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (46, 1, 'Christmas Island', 'CX', 'CXR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (47, 1, 'Cocos (Keeling) Islands', 'CC', 'CCK');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (48, 1, 'Colombia', 'CO', 'COL');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (49, 1, 'Comoros', 'KM', 'COM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (50, 1, 'Congo, Republic Of', 'CG', 'COG');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (51, 1, 'Congo, The Democratic Republic of the (formerly Zaire)', 'CD', 'COD');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (52, 1, 'Cook Islands', 'CK', 'COK');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (53, 1, 'Costa Rica', 'CR', 'CRI');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (54, 1, 'CÔte D''Ivoire (Ivory Coast)', 'CI', 'CIV');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (55, 1, 'Croatia (hrvatska)', 'HR', 'HRV');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (56, 1, 'Cuba', 'CU', 'CUB');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (57, 1, 'Cyprus', 'CY', 'CYP');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (58, 1, 'Czech Republic', 'CZ', 'CZE');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (59, 1, 'Denmark', 'DK', 'DNK');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (60, 1, 'Djibouti', 'DJ', 'DJI');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (61, 1, 'Dominica', 'DM', 'DMA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (62, 1, 'Dominican Republic', 'DO', 'DOM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (63, 1, 'Ecuador', 'EC', 'ECU');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (64, 1, 'Egypt', 'EG', 'EGY');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (65, 1, 'El Salvador', 'SV', 'SLV');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (66, 1, 'Equatorial Guinea', 'GQ', 'GNQ');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (67, 1, 'Eritrea', 'ER', 'ERI');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (68, 1, 'Estonia', 'EE', 'EST');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (69, 1, 'Ethiopia', 'ET', 'ETH');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (70, 1, 'Faeroe Islands', 'FO', 'FRO');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (71, 1, 'Falkland Islands (Malvinas)', 'FK', 'FLK');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (72, 1, 'Fiji', 'FJ', 'FJI');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (73, 1, 'Finland', 'FI', 'FIN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (74, 1, 'France', 'FR', 'FRA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (75, 1, 'French Guiana', 'GF', 'GUF');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (76, 1, 'French Polynesia', 'PF', 'PYF');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (77, 1, 'French Southern Territories', 'TF', 'ATF');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (78, 1, 'Gabon', 'GA', 'GAB');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (79, 1, 'Gambia, The', 'GM', 'GMB');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (80, 1, 'Georgia', 'GE', 'GEO');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (81, 1, 'Germany (Deutschland)', 'DE', 'DEU');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (82, 1, 'Ghana', 'GH', 'GHA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (83, 1, 'Gibraltar', 'GI', 'GIB');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (84, 1, 'Great Britain', 'GB', 'GBR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (85, 1, 'Greece', 'GR', 'GRC');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (86, 1, 'Greenland', 'GL', 'GRL');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (87, 1, 'Grenada', 'GD', 'GRD');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (88, 1, 'Guadeloupe', 'GP', 'GLP');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (89, 1, 'Guam', 'GU', 'GUM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (90, 1, 'Guatemala', 'GT', 'GTM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (91, 1, 'Guinea', 'GN', 'GIN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (92, 1, 'Guinea-bissau', 'GW', 'GNB');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (93, 1, 'Guyana', 'GY', 'GUY');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (94, 1, 'Haiti', 'HT', 'HTI');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (95, 1, 'Heard Island and Mcdonald Islands', 'HM', 'HMD');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (96, 1, 'Honduras', 'HN', 'HND');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (97, 1, 'Hong Kong (Special Administrative Region of China)', 'HK', 'HKG');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (98, 1, 'Hungary', 'HU', 'HUN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (99, 1, 'Iceland', 'IS', 'ISL');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (100, 1, 'India', 'IN', 'IND');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (101, 1, 'Indonesia', 'ID', 'IDN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (102, 1, 'Iran (Islamic Republic of Iran)', 'IR', 'IRN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (103, 1, 'Iraq', 'IQ', 'IRQ');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (104, 1, 'Ireland', 'IE', 'IRL');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (105, 1, 'Israel', 'IL', 'ISR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (106, 1, 'Italy', 'IT', 'ITA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (107, 1, 'Jamaica', 'JM', 'JAM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (108, 1, 'Japan', 'JP', 'JPN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (109, 1, 'Jordan (Hashemite Kingdom of Jordan)', 'JO', 'JOR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (110, 1, 'Kazakhstan', 'KZ', 'KAZ');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (111, 1, 'Kenya', 'KE', 'KEN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (112, 1, 'Kiribati', 'KI', 'KIR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (113, 1, 'Korea (Democratic Peoples Republic pf [North] Korea)', 'KP', 'PRK');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (114, 1, 'Korea (Republic of [South] Korea)', 'KR', 'KOR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (115, 1, 'Kuwait', 'KW', 'KWT');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (116, 1, 'Kyrgyzstan', 'KG', 'KGZ');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (117, 1, 'Lao People''s Democratic Republic', 'LA', 'LAO');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (118, 1, 'Latvia', 'LV', 'LVA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (119, 1, 'Lebanon', 'LB', 'LBN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (120, 1, 'Lesotho', 'LS', 'LSO');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (121, 1, 'Liberia', 'LR', 'LBR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (122, 1, 'Libya (Libyan Arab Jamahirya)', 'LY', 'LBY');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (123, 1, 'Liechtenstein (Fürstentum Liechtenstein)', 'LI', 'LIE');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (124, 1, 'Lithuania', 'LT', 'LTU');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (125, 1, 'Luxembourg', 'LU', 'LUX');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (126, 1, 'Macao (Special Administrative Region of China)', 'MO', 'MAC');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (127, 1, 'Macedonia (Former Yugoslav Republic of Macedonia)', 'MK', 'MKD');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (128, 1, 'Madagascar', 'MG', 'MDG');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (129, 1, 'Malawi', 'MW', 'MWI');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (130, 1, 'Malaysia', 'MY', 'MYS');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (131, 1, 'Maldives', 'MV', 'MDV');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (132, 1, 'Mali', 'ML', 'MLI');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (133, 1, 'Malta', 'MT', 'MLT');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (134, 1, 'Marshall Islands', 'MH', 'MHL');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (135, 1, 'Martinique', 'MQ', 'MTQ');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (136, 1, 'Mauritania', 'MR', 'MRT');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (137, 1, 'Mauritius', 'MU', 'MUS');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (138, 1, 'Mayotte', 'YT', 'MYT');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (139, 1, 'Mexico', 'MX', 'MEX');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (140, 1, 'Micronesia (Federated States of Micronesia)', 'FM', 'FSM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (141, 1, 'Moldova', 'MD', 'MDA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (142, 1, 'Monaco', 'MC', 'MCO');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (143, 1, 'Mongolia', 'MN', 'MNG');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (144, 1, 'Montserrat', 'MS', 'MSR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (145, 1, 'Morocco', 'MA', 'MAR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (146, 1, 'Mozambique (Moçambique)', 'MZ', 'MOZ');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (147, 1, 'Myanmar (formerly Burma)', 'MM', 'MMR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (148, 1, 'Namibia', 'NA', 'NAM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (149, 1, 'Nauru', 'NR', 'NRU');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (150, 1, 'Nepal', 'NP', 'NPL');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (151, 1, 'Netherlands', 'NL', 'NLD');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (152, 1, 'Netherlands Antilles', 'AN', 'ANT');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (153, 1, 'New Caledonia', 'NC', 'NCL');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (154, 1, 'New Zealand', 'NZ', 'NZL');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (155, 1, 'Nicaragua', 'NI', 'NIC');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (156, 1, 'Niger', 'NE', 'NER');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (157, 1, 'Nigeria', 'NG', 'NGA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (158, 1, 'Niue', 'NU', 'NIU');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (159, 1, 'Norfolk Island', 'NF', 'NFK');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (160, 1, 'Northern Mariana Islands', 'MP', 'MNP');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (161, 1, 'Norway', 'NO', 'NOR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (162, 1, 'Oman', 'OM', 'OMN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (163, 1, 'Pakistan', 'PK', 'PAK');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (164, 1, 'Palau', 'PW', 'PLW');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (165, 1, 'Palestinian Territories', 'PS', 'PSE');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (166, 1, 'Panama', 'PA', 'PAN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (167, 1, 'Papua New Guinea', 'PG', 'PNG');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (168, 1, 'Paraguay', 'PY', 'PRY');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (169, 1, 'Peru', 'PE', 'PER');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (170, 1, 'Philippines', 'PH', 'PHL');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (171, 1, 'Pitcairn', 'PN', 'PCN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (172, 1, 'Poland', 'PL', 'POL');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (173, 1, 'Portugal', 'PT', 'PRT');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (174, 1, 'Puerto Rico', 'PR', 'PRI');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (175, 1, 'Qatar', 'QA', 'QAT');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (176, 1, 'RÉunion', 'RE', 'REU');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (177, 1, 'Romania', 'RO', 'ROU');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (178, 1, 'Russian Federation', 'RU', 'RUS');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (179, 1, 'Rwanda', 'RW', 'RWA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (180, 1, 'Saint Helena', 'SH', 'SHN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (181, 1, 'Saint Kitts and Nevis', 'KN', 'KNA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (182, 1, 'Saint Lucia', 'LC', 'LCA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (183, 1, 'Saint Pierre and Miquelon', 'PM', 'SPM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (184, 1, 'Saint Vincent and the Grenadines', 'VC', 'VCT');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (185, 1, 'Samoa (formerly Western Samoa)', 'WS', 'WSM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (186, 1, 'San Marino (Republic of)', 'SM', 'SMR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (187, 1, 'Sao Tome and Principe', 'ST', 'STP');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (188, 1, 'Saudi Arabia (Kingdom of Saudi Arabia)', 'SA', 'SAU');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (189, 1, 'Senegal', 'SN', 'SEN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (190, 1, 'Serbia and Montenegro (formerly Yugoslavia)', 'CS', 'SCG');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (191, 1, 'Seychelles', 'SC', 'SYC');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (192, 1, 'Sierra Leone', 'SL', 'SLE');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (193, 1, 'Singapore', 'SG', 'SGP');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (194, 1, 'Slovakia (Slovak Republic)', 'SK', 'SVK');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (195, 1, 'Slovenia', 'SI', 'SVN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (196, 1, 'Solomon Islands', 'SB', 'SLB');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (197, 1, 'Somalia', 'SO', 'SOM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (198, 1, 'South Africa (zuid Afrika)', 'ZA', 'ZAF');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (199, 1, 'South Georgia and the South Sandwich Islands', 'GS', 'SGS');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (200, 1, 'Spain (españa)', 'ES', 'ESP');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (201, 1, 'Sri Lanka', 'LK', 'LKA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (202, 1, 'Sudan', 'SD', 'SDN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (203, 1, 'Suriname', 'SR', 'SUR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (204, 1, 'Svalbard and Jan Mayen', 'SJ', 'SJM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (205, 1, 'Swaziland', 'SZ', 'SWZ');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (206, 1, 'Sweden', 'SE', 'SWE');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (207, 1, 'Switzerland (Confederation of Helvetia)', 'CH', 'CHE');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (208, 1, 'Syrian Arab Republic', 'SY', 'SYR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (209, 1, 'Taiwan ("Chinese Taipei" for IOC)', 'TW', 'TWN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (210, 1, 'Tajikistan', 'TJ', 'TJK');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (211, 1, 'Tanzania', 'TZ', 'TZA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (212, 1, 'Thailand', 'TH', 'THA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (213, 1, 'Timor-Leste (formerly East Timor)', 'TL', 'TLS');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (214, 1, 'Togo', 'TG', 'TGO');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (215, 1, 'Tokelau', 'TK', 'TKL');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (216, 1, 'Tonga', 'TO', 'TON');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (217, 1, 'Trinidad and Tobago', 'TT', 'TTO');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (218, 1, 'Tunisia', 'TN', 'TUN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (219, 1, 'Turkey', 'TR', 'TUR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (220, 1, 'Turkmenistan', 'TM', 'TKM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (221, 1, 'Turks and Caicos Islands', 'TC', 'TCA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (222, 1, 'Tuvalu', 'TV', 'TUV');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (223, 1, 'Uganda', 'UG', 'UGA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (224, 1, 'Ukraine', 'UA', 'UKR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (225, 1, 'United Arab Emirates', 'AE', 'ARE');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (226, 1, 'United Kingdom (Great Britain)', 'GB', 'GBR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (227, 1, 'United States', 'US', 'USA');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (228, 1, 'United States Minor Outlying Islands', 'UM', 'UMI');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (229, 1, 'Uruguay', 'UY', 'URY');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (230, 1, 'Uzbekistan', 'UZ', 'UZB');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (231, 1, 'Vanuatu', 'VU', 'VUT');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (232, 1, 'Vatican City (Holy See)', 'VA', 'VAT');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (233, 1, 'Venezuela', 'VE', 'VEN');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (234, 1, 'Viet Nam', 'VN', 'VNM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (235, 1, 'Virgin Islands, British', 'VG', 'VGB');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (236, 1, 'Virgin Islands, U.S.', 'VI', 'VIR');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (237, 1, 'Wallis and Futuna', 'WF', 'WLF');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (238, 1, 'Western Sahara (formerly Spanish Sahara)', 'EH', 'ESH');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (239, 1, 'Yemen (Arab Republic)', 'YE', 'YEM');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (240, 1, 'Zambia', 'ZM', 'ZMB');
INSERT INTO #__sdi_sys_country (ordering, state, name, iso2, iso3) VALUES (241, 1, 'Zimbabwe', 'ZW', 'ZWE');

INSERT INTO #__sdi_sys_criteriatype (ordering, state, value) VALUES (1, 1, 'system');
INSERT INTO #__sdi_sys_criteriatype (ordering, state, value) VALUES (2, 1, 'relation');
INSERT INTO #__sdi_sys_criteriatype (ordering, state, value) VALUES (3, 1, 'csw');

INSERT INTO #__sdi_sys_entity (ordering, state, value) VALUES (1, 1, 'attribute');
INSERT INTO #__sdi_sys_entity (ordering, state, value) VALUES (2, 1, 'class');

INSERT INTO #__sdi_sys_exceptionlevel (ordering, state, value) VALUES (1, 1, 'permissive');
INSERT INTO #__sdi_sys_exceptionlevel (ordering, state, value) VALUES (2, 1, 'restrictive');

INSERT INTO #__sdi_sys_importtype (ordering, state, value) VALUES (1, 1, 'replace');
INSERT INTO #__sdi_sys_importtype (ordering, state, value) VALUES (2, 1, 'merge');

INSERT INTO #__sdi_sys_isolanguage (ordering, state, value) VALUES (1, 1, 'iso639-1');
INSERT INTO #__sdi_sys_isolanguage (ordering, state, value) VALUES (2, 1, 'iso639-2B');
INSERT INTO #__sdi_sys_isolanguage (ordering, state, value) VALUES (3, 1, 'iso639-2T');

INSERT INTO #__sdi_sys_loglevel (ordering, state, value) VALUES (1, 1, 'off');
INSERT INTO #__sdi_sys_loglevel (ordering, state, value) VALUES (2, 1, 'fatal');
INSERT INTO #__sdi_sys_loglevel (ordering, state, value) VALUES (3, 1, 'error');
INSERT INTO #__sdi_sys_loglevel (ordering, state, value) VALUES (4, 1, 'warning');
INSERT INTO #__sdi_sys_loglevel (ordering, state, value) VALUES (5, 1, 'info');
INSERT INTO #__sdi_sys_loglevel (ordering, state, value) VALUES (6, 1, 'debug');
INSERT INTO #__sdi_sys_loglevel (ordering, state, value) VALUES (7, 1, 'trace');
INSERT INTO #__sdi_sys_loglevel (ordering, state, value) VALUES (8, 1, 'All');

INSERT INTO #__sdi_sys_logroll (ordering, state, value) VALUES (1, 1, 'daily');
INSERT INTO #__sdi_sys_logroll (ordering, state, value) VALUES (2, 1, 'weekly');
INSERT INTO #__sdi_sys_logroll (ordering, state, value) VALUES (3, 1, 'monthly');
INSERT INTO #__sdi_sys_logroll (ordering, state, value) VALUES (4, 1, 'annually');

INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('googleearth', 1, 1, 'Google Earth');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('navigation', 2, 1, 'Navigation');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('zoom', 3, 1, 'Zoom');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('navigationhistory', 4, 1, 'Navigation history');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('zoomtoextent', 5, 1, 'Zoom to extent');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('measure', 6, 1, 'Measure');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('googlegeocoder', 7, 1, 'Google Geocoder');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('print', 8, 1, 'Print');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('addlayer', 9, 1, 'Add layer');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('removelayer', 10, 1, 'Remove layer');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('layerproperties', 11, 1, 'Layer properties');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('getfeatureinfo', 12, 1, 'Get feature info');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('layertree', 13, 1, 'Layer tree');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('scaleline', 14, 1, 'Scale line');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('mouseposition', 15, 1, 'Mouse position');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('wfslocator', 16, 1, 'Wfs locator');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('searchcatalog', 17, 1, 'Catalog search');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('layerdetailsheet', 18, 1, 'Layer detail sheet');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('layerdownload', 19, 1, 'Layer download');
INSERT INTO #__sdi_sys_maptool (alias, ordering, state, name) VALUES ('layerorder', 20, 1, 'Layer order');

INSERT INTO #__sdi_sys_metadatastate (ordering, state, value) VALUES (1, 1, 'inprogress');
INSERT INTO #__sdi_sys_metadatastate (ordering, state, value) VALUES (2, 1, 'validated');
INSERT INTO #__sdi_sys_metadatastate (ordering, state, value) VALUES (3, 1, 'published');
INSERT INTO #__sdi_sys_metadatastate (ordering, state, value) VALUES (4, 1, 'archived');
INSERT INTO #__sdi_sys_metadatastate (ordering, state, value) VALUES (5, 1, 'trashed');

INSERT INTO #__sdi_sys_metadataversion (ordering, state, value) VALUES (1, 1, 'all');
INSERT INTO #__sdi_sys_metadataversion (ordering, state, value) VALUES (2, 1, 'last');

INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (1, 1, 1, 1, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (2, 1, 1, 2, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (3, 1, 1, 3, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (4, 1, 1, 4, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (5, 1, 1, 5, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (6, 1, 1, 6, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (7, 1, 1, 7, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (8, 1, 1, 8, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (9, 1, 1, 9, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (10, 1, 1, 10, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (11, 1, 2, 1, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (12, 1, 2, 2, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (13, 1, 2, 3, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (14, 1, 2, 4, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (15, 1, 2, 5, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (16, 1, 2, 6, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (17, 1, 2, 7, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (18, 1, 2, 8, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (19, 1, 2, 9, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (20, 1, 2, 10, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (21, 1, 6, 1, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (22, 1, 6, 11, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (23, 1, 6, 12, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (24, 1, 7, 13, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (25, 1, 7, 14, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (26, 1, 7, 15, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (27, 1, 7, 1, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (28, 1, 7, 16, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (29, 1, 3, 17, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (30, 1, 3, 18, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (31, 1, 3, 19, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (32, 1, 3, 20, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (33, 1, 3, 21, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (34, 1, 3, 1, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (35, 1, 4, 17, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (36, 1, 4, 18, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (37, 1, 4, 19, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (38, 1, 4, 20, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (39, 1, 4, 21, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (40, 1, 4, 1, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (41, 1, 5, 17, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (42, 1, 5, 18, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (43, 1, 5, 19, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (44, 1, 5, 20, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (45, 1, 5, 21, 0);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (46, 1, 5, 1, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (47, 1, 3, 12, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (48, 1, 4, 12, 1);
INSERT INTO #__sdi_sys_operationcompliance (ordering, state, servicecompliance_id, serviceoperation_id, implemented) VALUES (49, 1, 5, 12, 1);

INSERT INTO #__sdi_sys_orderstate (ordering, state, value) VALUES (1, 1, 'archived');
INSERT INTO #__sdi_sys_orderstate (ordering, state, value) VALUES (2, 1, 'historized');
INSERT INTO #__sdi_sys_orderstate (ordering, state, value) VALUES (3, 1, 'finish');
INSERT INTO #__sdi_sys_orderstate (ordering, state, value) VALUES (4, 1, 'await');
INSERT INTO #__sdi_sys_orderstate (ordering, state, value) VALUES (5, 1, 'progress');
INSERT INTO #__sdi_sys_orderstate (ordering, state, value) VALUES (6, 1, 'sent');
INSERT INTO #__sdi_sys_orderstate (ordering, state, value) VALUES (7, 1, 'saved');

INSERT INTO #__sdi_sys_ordertype (ordering, state, value) VALUES (1, 1, 'order');
INSERT INTO #__sdi_sys_ordertype (ordering, state, value) VALUES (2, 1, 'estimate');
INSERT INTO #__sdi_sys_ordertype (ordering, state, value) VALUES (3, 1, 'draft');

INSERT INTO #__sdi_sys_perimetertype (ordering, state, value) VALUES (1, 1, 'extraction');
INSERT INTO #__sdi_sys_perimetertype (ordering, state, value) VALUES (2, 1, 'download');
INSERT INTO #__sdi_sys_perimetertype (ordering, state, value) VALUES (3, 1, 'both');

INSERT INTO #__sdi_sys_pricing (ordering, state, value) VALUES (1, 1, 'free');
INSERT INTO #__sdi_sys_pricing (ordering, state, value) VALUES (2, 1, 'fee');

INSERT INTO #__sdi_sys_productmining (ordering, state, value) VALUES (1, 1, 'automatic');
INSERT INTO #__sdi_sys_productmining (ordering, state, value) VALUES (2, 1, 'manual');

INSERT INTO #__sdi_sys_productstate (ordering, state, value) VALUES (1, 1, 'available');
INSERT INTO #__sdi_sys_productstate (ordering, state, value) VALUES (2, 1, 'await');
INSERT INTO #__sdi_sys_productstate (ordering, state, value) VALUES (3, 1, 'sent');

INSERT INTO #__sdi_sys_productstorage (ordering, state, value) VALUES (1, 1, 'upload');
INSERT INTO #__sdi_sys_productstorage (ordering, state, value) VALUES (2, 1, 'url');
INSERT INTO #__sdi_sys_productstorage (ordering, state, value) VALUES (3, 1, 'zoning');

INSERT INTO #__sdi_sys_propertytype (ordering, state, value) VALUES (1, 1, 'list');
INSERT INTO #__sdi_sys_propertytype (ordering, state, value) VALUES (2, 1, 'multiplelist');
INSERT INTO #__sdi_sys_propertytype (ordering, state, value) VALUES (3, 1, 'checkbox');
INSERT INTO #__sdi_sys_propertytype (ordering, state, value) VALUES (4, 1, 'text');
INSERT INTO #__sdi_sys_propertytype (ordering, state, value) VALUES (5, 1, 'textarea');
INSERT INTO #__sdi_sys_propertytype (ordering, state, value) VALUES (6, 1, 'message');

INSERT INTO #__sdi_sys_proxytype (ordering, state, value) VALUES (1, 1, 'harvest');
INSERT INTO #__sdi_sys_proxytype (ordering, state, value) VALUES (2, 1, 'relay');
INSERT INTO #__sdi_sys_proxytype (ordering, state, value) VALUES (3, 1, 'aggregate');

INSERT INTO #__sdi_sys_relationscope (ordering, state, value) VALUES (1, 1, 'editable');
INSERT INTO #__sdi_sys_relationscope (ordering, state, value) VALUES (2, 1, 'visible');
INSERT INTO #__sdi_sys_relationscope (ordering, state, value) VALUES (3, 1, 'hidden');

INSERT INTO #__sdi_sys_relationtype (ordering, state, value) VALUES (1, 1, 'association');
INSERT INTO #__sdi_sys_relationtype (ordering, state, value) VALUES (2, 1, 'aggregation');
INSERT INTO #__sdi_sys_relationtype (ordering, state, value) VALUES (3, 1, 'composition');
INSERT INTO #__sdi_sys_relationtype (ordering, state, value) VALUES (4, 1, 'generalization');

INSERT INTO #__sdi_sys_rendertype (ordering, state, value) VALUES (1, 1, 'textarea');
INSERT INTO #__sdi_sys_rendertype (ordering, state, value) VALUES (2, 1, 'checkbox');
INSERT INTO #__sdi_sys_rendertype (ordering, state, value) VALUES (3, 1, 'radiobutton');
INSERT INTO #__sdi_sys_rendertype (ordering, state, value) VALUES (4, 1, 'list');
INSERT INTO #__sdi_sys_rendertype (ordering, state, value) VALUES (5, 1, 'textbox');
INSERT INTO #__sdi_sys_rendertype (ordering, state, value) VALUES (6, 1, 'date');

INSERT INTO #__sdi_sys_rendertype_criteriatype (criteriatype_id, rendertype_id) VALUES (3, 5);
INSERT INTO #__sdi_sys_rendertype_criteriatype (criteriatype_id, rendertype_id) VALUES (3, 6);

INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (1, 5);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (2, 1);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (2, 5);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (3, 1);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (3, 5);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (4, 1);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (4, 5);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (5, 6);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (6, 2);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (6, 3);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (6, 4);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (7, 1);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (7, 5);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (8, 6);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (9, 4);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (10, 4);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (12, 5);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (13, 5);
INSERT INTO #__sdi_sys_rendertype_stereotype (stereotype_id, rendertype_id) VALUES (14, 5);

INSERT INTO #__sdi_sys_role (ordering, state, value) VALUES (1, 1, 'member');
INSERT INTO #__sdi_sys_role (ordering, state, value) VALUES (2, 1, 'resourcemanager');
INSERT INTO #__sdi_sys_role (ordering, state, value) VALUES (3, 1, 'metadataresponsible');
INSERT INTO #__sdi_sys_role (ordering, state, value) VALUES (4, 1, 'metadataeditor');
INSERT INTO #__sdi_sys_role (ordering, state, value) VALUES (5, 1, 'diffusionmanager');
INSERT INTO #__sdi_sys_role (ordering, state, value) VALUES (6, 1, 'previewmanager');
INSERT INTO #__sdi_sys_role (ordering, state, value) VALUES (7, 1, 'extractionresponsible');

INSERT INTO #__sdi_sys_searchtab (ordering, state, value) VALUES (1, 1, 'simple');
INSERT INTO #__sdi_sys_searchtab (ordering, state, value) VALUES (2, 1, 'advanced');
INSERT INTO #__sdi_sys_searchtab (ordering, state, value) VALUES (3, 1, 'hidden');
INSERT INTO #__sdi_sys_searchtab (ordering, state, value) VALUES (4, 1, 'none');

INSERT INTO #__sdi_sys_servicecompliance (ordering, state, serviceconnector_id, serviceversion_id, implemented, relayable, aggregatable, harvestable) VALUES (1, 1, 1, 7, 1, 1, 0, 1);
INSERT INTO #__sdi_sys_servicecompliance (ordering, state, serviceconnector_id, serviceversion_id, implemented, relayable, aggregatable, harvestable) VALUES (2, 1, 1, 8, 1, 1, 0, 1);
INSERT INTO #__sdi_sys_servicecompliance (ordering, state, serviceconnector_id, serviceversion_id, implemented, relayable, aggregatable, harvestable) VALUES (3, 1, 2, 2, 1, 1, 1, 0);
INSERT INTO #__sdi_sys_servicecompliance (ordering, state, serviceconnector_id, serviceversion_id, implemented, relayable, aggregatable, harvestable) VALUES (4, 1, 2, 3, 1, 1, 1, 0);
INSERT INTO #__sdi_sys_servicecompliance (ordering, state, serviceconnector_id, serviceversion_id, implemented, relayable, aggregatable, harvestable) VALUES (5, 1, 2, 4, 1, 1, 1, 0);
INSERT INTO #__sdi_sys_servicecompliance (ordering, state, serviceconnector_id, serviceversion_id, implemented, relayable, aggregatable, harvestable) VALUES (6, 1, 3, 1, 1, 1, 0, 0);
INSERT INTO #__sdi_sys_servicecompliance (ordering, state, serviceconnector_id, serviceversion_id, implemented, relayable, aggregatable, harvestable) VALUES (7, 1, 4, 1, 1, 1, 1, 0);
INSERT INTO #__sdi_sys_servicecompliance (ordering, state, serviceconnector_id, serviceversion_id, implemented, relayable, aggregatable, harvestable) VALUES (8, 1, 11, 2, 1, 1, 1, 0);
INSERT INTO #__sdi_sys_servicecompliance (ordering, state, serviceconnector_id, serviceversion_id, implemented, relayable, aggregatable, harvestable) VALUES (9, 1, 11, 3, 1, 1, 1, 0);
INSERT INTO #__sdi_sys_servicecompliance (ordering, state, serviceconnector_id, serviceversion_id, implemented, relayable, aggregatable, harvestable) VALUES (10, 1, 11, 4, 1, 1, 1, 0);

INSERT INTO #__sdi_sys_servicecon_authenticationcon (serviceconnector_id, authenticationconnector_id) VALUES (1, 1);
INSERT INTO #__sdi_sys_servicecon_authenticationcon (serviceconnector_id, authenticationconnector_id) VALUES (1, 2);
INSERT INTO #__sdi_sys_servicecon_authenticationcon (serviceconnector_id, authenticationconnector_id) VALUES (2, 1);
INSERT INTO #__sdi_sys_servicecon_authenticationcon (serviceconnector_id, authenticationconnector_id) VALUES (3, 1);
INSERT INTO #__sdi_sys_servicecon_authenticationcon (serviceconnector_id, authenticationconnector_id) VALUES (4, 1);
INSERT INTO #__sdi_sys_servicecon_authenticationcon (serviceconnector_id, authenticationconnector_id) VALUES (5, 1);
INSERT INTO #__sdi_sys_servicecon_authenticationcon (serviceconnector_id, authenticationconnector_id) VALUES (6, 1);
INSERT INTO #__sdi_sys_servicecon_authenticationcon (serviceconnector_id, authenticationconnector_id) VALUES (7, 1);
INSERT INTO #__sdi_sys_servicecon_authenticationcon (serviceconnector_id, authenticationconnector_id) VALUES (8, 1);
INSERT INTO #__sdi_sys_servicecon_authenticationcon (serviceconnector_id, authenticationconnector_id) VALUES (9, 1);
INSERT INTO #__sdi_sys_servicecon_authenticationcon (serviceconnector_id, authenticationconnector_id) VALUES (10, 1);

INSERT INTO #__sdi_sys_serviceconnector (ordering, state, value) VALUES (1, 1, 'CSW');
INSERT INTO #__sdi_sys_serviceconnector (ordering, state, value) VALUES (2, 1, 'WMS');
INSERT INTO #__sdi_sys_serviceconnector (ordering, state, value) VALUES (3, 1, 'WMTS');
INSERT INTO #__sdi_sys_serviceconnector (ordering, state, value) VALUES (4, 1, 'WFS');
INSERT INTO #__sdi_sys_serviceconnector (ordering, state, value) VALUES (5, 0, 'WCS');
INSERT INTO #__sdi_sys_serviceconnector (ordering, state, value) VALUES (6, 0, 'WCPS');
INSERT INTO #__sdi_sys_serviceconnector (ordering, state, value) VALUES (7, 0, 'SOS');
INSERT INTO #__sdi_sys_serviceconnector (ordering, state, value) VALUES (8, 0, 'SPS');
INSERT INTO #__sdi_sys_serviceconnector (ordering, state, value) VALUES (9, 0, 'WPS');
INSERT INTO #__sdi_sys_serviceconnector (ordering, state, value) VALUES (10, 0, 'OLS');
INSERT INTO #__sdi_sys_serviceconnector (ordering, state, value) VALUES (11, 1, 'WMSC');
INSERT INTO #__sdi_sys_serviceconnector (ordering, state, value) VALUES (12, 0, 'Bing');
INSERT INTO #__sdi_sys_serviceconnector (ordering, state, value) VALUES (13, 0, 'Google');
INSERT INTO #__sdi_sys_serviceconnector (ordering, state, value) VALUES (14, 0, 'OSM');

INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (1, 1, 'GetCapabilities');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (2, 1, 'GetRecords');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (3, 1, 'GetRecordById');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (4, 1, 'DescribeRecord');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (5, 1, 'TransactionInsert');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (6, 1, 'TransactionUpdate');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (7, 1, 'TransactionReplace');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (8, 1, 'TransactionDelete');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (9, 1, 'GetDomain');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (10, 1, 'Harvest');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (11, 1, 'GetTile');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (12, 1, 'GetFeatureInfo');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (13, 1, 'DescribeFeatureType');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (14, 1, 'GetFeature');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (15, 1, 'LockFeature');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (16, 1, 'GetFeatureWithLock');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (17, 1, 'GetMap');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (18, 1, 'GetLegendGraphic');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (19, 1, 'DescribeLayer');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (20, 1, 'GetStyles');
INSERT INTO #__sdi_sys_serviceoperation (ordering, state, value) VALUES (21, 1, 'PutStyles');

INSERT INTO #__sdi_sys_servicescope (ordering, state, value) VALUES (1, 1, 'all');
INSERT INTO #__sdi_sys_servicescope (ordering, state, value) VALUES (2, 1, 'organism');
INSERT INTO #__sdi_sys_servicescope (ordering, state, value) VALUES (3, 1, 'none');

INSERT INTO #__sdi_sys_servicetype (ordering, state, value) VALUES (1, 1, 'physical');
INSERT INTO #__sdi_sys_servicetype (ordering, state, value) VALUES (2, 1, 'virtual');

INSERT INTO #__sdi_sys_serviceversion (ordering, state, value) VALUES (1, 1, '1.0.0');
INSERT INTO #__sdi_sys_serviceversion (ordering, state, value) VALUES (2, 1, '1.1.0');
INSERT INTO #__sdi_sys_serviceversion (ordering, state, value) VALUES (3, 1, '1.1.1');
INSERT INTO #__sdi_sys_serviceversion (ordering, state, value) VALUES (4, 1, '1.3.0');
INSERT INTO #__sdi_sys_serviceversion (ordering, state, value) VALUES (5, 1, '2.0');
INSERT INTO #__sdi_sys_serviceversion (ordering, state, value) VALUES (6, 1, '2.0.0');
INSERT INTO #__sdi_sys_serviceversion (ordering, state, value) VALUES (7, 1, '2.0.1');
INSERT INTO #__sdi_sys_serviceversion (ordering, state, value) VALUES (8, 1, '2.0.2');

INSERT INTO #__sdi_sys_spatialoperator (ordering, state, value) VALUES (1, 1, 'within');
INSERT INTO #__sdi_sys_spatialoperator (ordering, state, value) VALUES (3, 1, 'touch');

INSERT INTO #__sdi_sys_stereotype (ordering, state, value, defaultpattern, isocode, namespace_id, entity_id) VALUES (1, 1, 'guid', '([A-Z0-9]{8}|-|[A-Z0-9]{4}|-|[A-Z0-9]{4}|-|[A-Z0-9]{4}|-|[A-Z0-9]{12})', 'CharacterString', 2, 1);
INSERT INTO #__sdi_sys_stereotype (ordering, state, value, defaultpattern, isocode, namespace_id, entity_id) VALUES (2, 1, 'text', '', 'CharacterString', 2, 1);
INSERT INTO #__sdi_sys_stereotype (ordering, state, value, defaultpattern, isocode, namespace_id, entity_id) VALUES (3, 1, 'locale', '', NULL, NULL, 1);
INSERT INTO #__sdi_sys_stereotype (ordering, state, value, defaultpattern, isocode, namespace_id, entity_id) VALUES (4, 1, 'number', '[0-9.-]', 'Decimal', 2, 1);
INSERT INTO #__sdi_sys_stereotype (ordering, state, value, defaultpattern, isocode, namespace_id, entity_id) VALUES (5, 1, 'date', '([0-9]{4}-[0-9]{2}-[0-9]{2})', 'Date', 2, 1);
INSERT INTO #__sdi_sys_stereotype (ordering, state, value, defaultpattern, isocode, namespace_id, entity_id) VALUES (6, 1, 'list', '', NULL, NULL, 1);
INSERT INTO #__sdi_sys_stereotype (ordering, state, value, defaultpattern, isocode, namespace_id, entity_id) VALUES (7, 1, 'link', '((https?://)?([w.-]+).([a-z.]{2,6})([/w .#:+?%=&;,]*)*/?)', 'URL', 1, 1);
INSERT INTO #__sdi_sys_stereotype (ordering, state, value, defaultpattern, isocode, namespace_id, entity_id) VALUES (8, 1, 'datetime', '([0-9]{4}-[0-9]{2}-[0-9]{2})', 'DateTime', 2, 1);
INSERT INTO #__sdi_sys_stereotype (ordering, state, value, defaultpattern, isocode, namespace_id, entity_id) VALUES (9, 1, 'textchoice', '', 'CharacterString', 2, 1);
INSERT INTO #__sdi_sys_stereotype (ordering, state, value, defaultpattern, isocode, namespace_id, entity_id) VALUES (10, 1, 'localechoice', '', NULL, NULL, 1);
INSERT INTO #__sdi_sys_stereotype (ordering, state, value, defaultpattern, isocode, namespace_id, entity_id) VALUES (11, 1, 'gemet', NULL, NULL, NULL, 1);
INSERT INTO #__sdi_sys_stereotype (ordering, state, value, defaultpattern, isocode, namespace_id, entity_id) VALUES (12, 1, 'distance', '[0-9.-]', 'Distance', 2, 1);
INSERT INTO #__sdi_sys_stereotype (ordering, state, value, defaultpattern, isocode, namespace_id, entity_id) VALUES (13, 1, 'integer', '[0-9.-]', 'Integer', 2, 1);
INSERT INTO #__sdi_sys_stereotype (ordering, state, value, defaultpattern, isocode, namespace_id, entity_id) VALUES (14, 1, 'file', '', 'CharacterString', 2, 1);
INSERT INTO #__sdi_sys_stereotype (ordering, state, value, defaultpattern, isocode, namespace_id, entity_id) VALUES (15, 1, 'geographicextent', NULL, NULL, NULL, 2);

INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (1, 1, 'farming');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (2, 1, 'biota');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (3, 1, 'bounderies');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (4, 1, 'climatologyMeteorologyAtmosphere');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (5, 1, 'economy');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (6, 1, 'elevation');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (7, 1, 'environment');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (8, 1, 'geoscientificinformation');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (9, 1, 'health');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (10, 1, 'imageryBaseMapsEarthCover');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (11, 1, 'intelligenceMilitary');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (12, 1, 'inlandWaters');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (13, 1, 'location');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (14, 1, 'oceans');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (15, 1, 'planningCadastre');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (16, 1, 'society');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (17, 1, 'structure');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (18, 1, 'transportation');
INSERT INTO #__sdi_sys_topiccategory (ordering, state, value) VALUES (19, 1, 'utilitiesCommunication');

INSERT INTO #__sdi_sys_unit (ordering, state, alias, name) VALUES (1, 1, 'm', 'meter');
INSERT INTO #__sdi_sys_unit (ordering, state, alias, name) VALUES (2, 1, 'dd', 'degree');

INSERT INTO #__sdi_sys_versiontype (ordering, state, value) VALUES (1, 1, 'all');
INSERT INTO #__sdi_sys_versiontype (ordering, state, value) VALUES (2, 1, 'lastPublishedVersion');

INSERT INTO action_types ("ID_ACTION_TYPE", "NAME") VALUES (1, 'E-MAIL');
INSERT INTO action_types ("ID_ACTION_TYPE", "NAME") VALUES (2, 'RSS');

INSERT INTO http_methods ("ID_HTTP_METHOD", "NAME") VALUES (1, 'GET');
INSERT INTO http_methods ("ID_HTTP_METHOD", "NAME") VALUES (2, 'POST');

INSERT INTO job_defaults ("ID_PARAM", "COLUMN_NAME", "STRING_VALUE", "VALUE_TYPE") VALUES (1, 'IS_PUBLIC', 'false', 'bool');
INSERT INTO job_defaults ("ID_PARAM", "COLUMN_NAME", "STRING_VALUE", "VALUE_TYPE") VALUES (2, 'IS_AUTOMATIC', 'false', 'bool');
INSERT INTO job_defaults ("ID_PARAM", "COLUMN_NAME", "STRING_VALUE", "VALUE_TYPE") VALUES (3, 'ALLOWS_REALTIME', 'true', 'bool');
INSERT INTO job_defaults ("ID_PARAM", "COLUMN_NAME", "STRING_VALUE", "VALUE_TYPE") VALUES (4, 'TRIGGERS_ALERTS', 'false', 'bool');
INSERT INTO job_defaults ("ID_PARAM", "COLUMN_NAME", "STRING_VALUE", "VALUE_TYPE") VALUES (5, 'TEST_INTERVAL', '3600', 'int');
INSERT INTO job_defaults ("ID_PARAM", "COLUMN_NAME", "STRING_VALUE", "VALUE_TYPE") VALUES (6, 'TIMEOUT', '30', 'int');
INSERT INTO job_defaults ("ID_PARAM", "COLUMN_NAME", "STRING_VALUE", "VALUE_TYPE") VALUES (7, 'BUSINESS_ERRORS', 'true', 'bool');
INSERT INTO job_defaults ("ID_PARAM", "COLUMN_NAME", "STRING_VALUE", "VALUE_TYPE") VALUES (8, 'HTTP_ERRORS', 'true', 'bool');
INSERT INTO job_defaults ("ID_PARAM", "COLUMN_NAME", "STRING_VALUE", "VALUE_TYPE") VALUES (9, 'SLA_START_TIME', '08:00:00', 'time');
INSERT INTO job_defaults ("ID_PARAM", "COLUMN_NAME", "STRING_VALUE", "VALUE_TYPE") VALUES (10, 'SLA_END_TIME', '18:00:00', 'time');
INSERT INTO job_defaults ("ID_PARAM", "COLUMN_NAME", "STRING_VALUE", "VALUE_TYPE") VALUES (11, 'RUN_SIMULATANEOUS', 'false', 'bool');
INSERT INTO job_defaults ("ID_PARAM", "COLUMN_NAME", "STRING_VALUE", "VALUE_TYPE") VALUES (12, 'SAVE_RESPONSE', 'false', 'bool');

INSERT INTO last_ids ("TABLE_NAME", "LAST_ID") VALUES ('ACTIONS', 2);
INSERT INTO last_ids ("TABLE_NAME", "LAST_ID") VALUES ('ALERTS', 161);
INSERT INTO last_ids ("TABLE_NAME", "LAST_ID") VALUES ('HTTP_METHODS', 3);
INSERT INTO last_ids ("TABLE_NAME", "LAST_ID") VALUES ('JOBS', 45);
INSERT INTO last_ids ("TABLE_NAME", "LAST_ID") VALUES ('JOB_DEFAULTS', 11);
INSERT INTO last_ids ("TABLE_NAME", "LAST_ID") VALUES ('LAST_QUERY_RESULTS', 39);
INSERT INTO last_ids ("TABLE_NAME", "LAST_ID") VALUES ('LOG_ENTRIES', 1046);
INSERT INTO last_ids ("TABLE_NAME", "LAST_ID") VALUES ('OVERVIEW_PAGE', 18);
INSERT INTO last_ids ("TABLE_NAME", "LAST_ID") VALUES ('OVERVIEW_QUERIES', 8);
INSERT INTO last_ids ("TABLE_NAME", "LAST_ID") VALUES ('QUERIES', 94);
INSERT INTO last_ids ("TABLE_NAME", "LAST_ID") VALUES ('QUERY_VALIDATION_RESULTS', 12);
INSERT INTO last_ids ("TABLE_NAME", "LAST_ID") VALUES ('QUERY_VALIDATION_SETTINGS', 48);
INSERT INTO last_ids ("TABLE_NAME", "LAST_ID") VALUES ('SERVICE_METHODS', 10);
INSERT INTO last_ids ("TABLE_NAME", "LAST_ID") VALUES ('SERVICE_TYPES', 8);
INSERT INTO last_ids ("TABLE_NAME", "LAST_ID") VALUES ('STATUSES', 5);

INSERT INTO roles ("ID_ROLE", "NAME", "RANK") VALUES (1, 'ROLE_ADMIN', 1);
INSERT INTO roles ("ID_ROLE", "NAME", "RANK") VALUES (2, 'ROLE_USER', 3);

INSERT INTO service_methods ("ID_SERVICE_METHOD", "NAME") VALUES (1, 'GetCapabilities');
INSERT INTO service_methods ("ID_SERVICE_METHOD", "NAME") VALUES (2, 'GetMap');
INSERT INTO service_methods ("ID_SERVICE_METHOD", "NAME") VALUES (3, 'GetFeature');
INSERT INTO service_methods ("ID_SERVICE_METHOD", "NAME") VALUES (4, 'GetRecordById');
INSERT INTO service_methods ("ID_SERVICE_METHOD", "NAME") VALUES (5, 'GetTile');
INSERT INTO service_methods ("ID_SERVICE_METHOD", "NAME") VALUES (6, 'GetRecords');
INSERT INTO service_methods ("ID_SERVICE_METHOD", "NAME") VALUES (7, 'GetCoverage');
INSERT INTO service_methods ("ID_SERVICE_METHOD", "NAME") VALUES (8, 'DescribeSensor');
INSERT INTO service_methods ("ID_SERVICE_METHOD", "NAME") VALUES (9, 'SOAP 1.1');
INSERT INTO service_methods ("ID_SERVICE_METHOD", "NAME") VALUES (10, 'SOAP 1.2');
INSERT INTO service_methods ("ID_SERVICE_METHOD", "NAME") VALUES (11, 'HTTP POST');
INSERT INTO service_methods ("ID_SERVICE_METHOD", "NAME") VALUES (12, 'HTTP GET');

INSERT INTO service_types ("ID_SERVICE_TYPE", "NAME", "VERSION") VALUES (1, 'WMS', '1.1.1');
INSERT INTO service_types ("ID_SERVICE_TYPE", "NAME", "VERSION") VALUES (2, 'WFS', '1.1.0');
INSERT INTO service_types ("ID_SERVICE_TYPE", "NAME", "VERSION") VALUES (4, 'WMTS', '1.0.0');
INSERT INTO service_types ("ID_SERVICE_TYPE", "NAME", "VERSION") VALUES (5, 'CSW', '2.0.2');
INSERT INTO service_types ("ID_SERVICE_TYPE", "NAME", "VERSION") VALUES (6, 'SOS', '1.0.0');
INSERT INTO service_types ("ID_SERVICE_TYPE", "NAME", "VERSION") VALUES (7, 'WCS', '1.0.0');
INSERT INTO service_types ("ID_SERVICE_TYPE", "NAME", "VERSION") VALUES (8, 'ALL', '0');


INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (1, 1);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (2, 1);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (4, 1);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (5, 1);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (6, 1);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (7, 1);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (8, 1);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (1, 2);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (8, 2);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (2, 3);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (8, 3);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (5, 4);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (8, 4);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (4, 5);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (8, 5);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (5, 6);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (8, 6);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (7, 7);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (8, 7);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (6, 8);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (8, 8);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (8, 9);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (8, 10);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (8, 11);
INSERT INTO service_types_methods ("ID_SERVICE_TYPE", "ID_SERVICE_METHOD") VALUES (8, 12);

INSERT INTO statuses ("ID_STATUS", "NAME") VALUES (1, 'AVAILABLE');
INSERT INTO statuses ("ID_STATUS", "NAME") VALUES (2, 'OUT_OF_ORDER');
INSERT INTO statuses ("ID_STATUS", "NAME") VALUES (3, 'UNAVAILABLE');
INSERT INTO statuses ("ID_STATUS", "NAME") VALUES (4, 'NOT_TESTED');

INSERT INTO users ("LOGIN", "PASSWORD", "ID_ROLE", "EXPIRATION", "ENABLED", "LOCKED") VALUES ('Admin', 'adm', 1, NULL, 1, 0);
INSERT INTO users ("LOGIN", "PASSWORD", "ID_ROLE", "EXPIRATION", "ENABLED", "LOCKED") VALUES ('user', 'usr', 2, NULL, 1, 0);
