package org.easysdi.proxy.domaintransitoire;

// Generated Oct 3, 2013 2:18:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cache;

/**
 * Gh0jlSdiResourcetype generated by hbm2java
 */
@Entity
@Cache
public class Gh0jlSdiResourcetype implements java.io.Serializable {

	private Integer Id;
	private Gh0jlSdiSysAccessscope gh0jlSdiSysAccessscope;
	private Gh0jlSdiProfile gh0jlSdiProfile;
	private Gh0jlSdiNamespace gh0jlSdiNamespace;
	private String Guid;
	private String Alias;
	private int Created_by;
	private Date Created;
	private int Modified_by;
	private Date Modified;
	private int Ordering;
	private boolean State;
	private int Checked_out;
	private Date Checked_out_time;
	private String Name;
	private String Description;
	private String Logo;
	private boolean Meta;
	private boolean Diffusion;
	private boolean View;
	private boolean Monitoring;
	private boolean Predefined;
	private boolean Versioning;
	private String Fragment;
	private String Sitemapparams;
	private int Access;
	private int Asset_id;
	private Set<Gh0jlSdiResourcetypelink> gh0jlSdiResourcetypelinksForParentId = new HashSet<Gh0jlSdiResourcetypelink>(
			0);
	private Set<Gh0jlSdiResourcetypelink> gh0jlSdiResourcetypelinksForChildId = new HashSet<Gh0jlSdiResourcetypelink>(
			0);
	private Set<Gh0jlSdiPolicyResourcetype> gh0jlSdiPolicyResourcetypes = new HashSet<Gh0jlSdiPolicyResourcetype>(
			0);
	private Set<Gh0jlSdiCatalogResourcetype> gh0jlSdiCatalogResourcetypes = new HashSet<Gh0jlSdiCatalogResourcetype>(
			0);
	private Set<SdiResource> gh0jlSdiResources = new HashSet<SdiResource>(
			0);
	private Set<Gh0jlSdiRelation> gh0jlSdiRelations = new HashSet<Gh0jlSdiRelation>(
			0);

	public Gh0jlSdiResourcetype() {
	}

	public Gh0jlSdiResourcetype(Gh0jlSdiSysAccessscope gh0jlSdiSysAccessscope,
			Gh0jlSdiProfile gh0jlSdiProfile, String Guid, String Alias,
			int Created_by, Date Created, int Modified_by, Date Modified,
			int Ordering, boolean State, int Checked_out,
			Date Checked_out_time, String Name, String Description,
			String Logo, boolean Meta, boolean Diffusion, boolean View,
			boolean Monitoring, boolean Predefined, boolean Versioning,
			int Access, int Asset_id) {
		this.gh0jlSdiSysAccessscope = gh0jlSdiSysAccessscope;
		this.gh0jlSdiProfile = gh0jlSdiProfile;
		this.Guid = Guid;
		this.Alias = Alias;
		this.Created_by = Created_by;
		this.Created = Created;
		this.Modified_by = Modified_by;
		this.Modified = Modified;
		this.Ordering = Ordering;
		this.State = State;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Name = Name;
		this.Description = Description;
		this.Logo = Logo;
		this.Meta = Meta;
		this.Diffusion = Diffusion;
		this.View = View;
		this.Monitoring = Monitoring;
		this.Predefined = Predefined;
		this.Versioning = Versioning;
		this.Access = Access;
		this.Asset_id = Asset_id;
	}

	public Gh0jlSdiResourcetype(Gh0jlSdiSysAccessscope gh0jlSdiSysAccessscope,
			Gh0jlSdiProfile gh0jlSdiProfile,
			Gh0jlSdiNamespace gh0jlSdiNamespace, String Guid, String Alias,
			int Created_by, Date Created, int Modified_by, Date Modified,
			int Ordering, boolean State, int Checked_out,
			Date Checked_out_time, String Name, String Description,
			String Logo, boolean Meta, boolean Diffusion, boolean View,
			boolean Monitoring, boolean Predefined, boolean Versioning,
			String Fragment, String Sitemapparams, int Access, int Asset_id,
			Set<Gh0jlSdiResourcetypelink> gh0jlSdiResourcetypelinksForParentId,
			Set<Gh0jlSdiResourcetypelink> gh0jlSdiResourcetypelinksForChildId,
			Set<Gh0jlSdiPolicyResourcetype> gh0jlSdiPolicyResourcetypes,
			Set<Gh0jlSdiCatalogResourcetype> gh0jlSdiCatalogResourcetypes,
			Set<SdiResource> gh0jlSdiResources,
			Set<Gh0jlSdiRelation> gh0jlSdiRelations) {
		this.gh0jlSdiSysAccessscope = gh0jlSdiSysAccessscope;
		this.gh0jlSdiProfile = gh0jlSdiProfile;
		this.gh0jlSdiNamespace = gh0jlSdiNamespace;
		this.Guid = Guid;
		this.Alias = Alias;
		this.Created_by = Created_by;
		this.Created = Created;
		this.Modified_by = Modified_by;
		this.Modified = Modified;
		this.Ordering = Ordering;
		this.State = State;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Name = Name;
		this.Description = Description;
		this.Logo = Logo;
		this.Meta = Meta;
		this.Diffusion = Diffusion;
		this.View = View;
		this.Monitoring = Monitoring;
		this.Predefined = Predefined;
		this.Versioning = Versioning;
		this.Fragment = Fragment;
		this.Sitemapparams = Sitemapparams;
		this.Access = Access;
		this.Asset_id = Asset_id;
		this.gh0jlSdiResourcetypelinksForParentId = gh0jlSdiResourcetypelinksForParentId;
		this.gh0jlSdiResourcetypelinksForChildId = gh0jlSdiResourcetypelinksForChildId;
		this.gh0jlSdiPolicyResourcetypes = gh0jlSdiPolicyResourcetypes;
		this.gh0jlSdiCatalogResourcetypes = gh0jlSdiCatalogResourcetypes;
		this.gh0jlSdiResources = gh0jlSdiResources;
		this.gh0jlSdiRelations = gh0jlSdiRelations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accessscope_id", nullable = false)
	public Gh0jlSdiSysAccessscope getGh0jlSdiSysAccessscope() {
		return this.gh0jlSdiSysAccessscope;
	}

	public void setGh0jlSdiSysAccessscope(
			Gh0jlSdiSysAccessscope gh0jlSdiSysAccessscope) {
		this.gh0jlSdiSysAccessscope = gh0jlSdiSysAccessscope;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profile_id", nullable = false)
	public Gh0jlSdiProfile getGh0jlSdiProfile() {
		return this.gh0jlSdiProfile;
	}

	public void setGh0jlSdiProfile(Gh0jlSdiProfile gh0jlSdiProfile) {
		this.gh0jlSdiProfile = gh0jlSdiProfile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fragmentnamespace_id")
	public Gh0jlSdiNamespace getGh0jlSdiNamespace() {
		return this.gh0jlSdiNamespace;
	}

	public void setGh0jlSdiNamespace(Gh0jlSdiNamespace gh0jlSdiNamespace) {
		this.gh0jlSdiNamespace = gh0jlSdiNamespace;
	}

	@Column(name = "guid", nullable = false, length = 36)
	public String getGuid() {
		return this.Guid;
	}

	public void setGuid(String Guid) {
		this.Guid = Guid;
	}

	@Column(name = "alias", nullable = false, length = 50)
	public String getAlias() {
		return this.Alias;
	}

	public void setAlias(String Alias) {
		this.Alias = Alias;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreated_by() {
		return this.Created_by;
	}

	public void setCreated_by(int Created_by) {
		this.Created_by = Created_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.Created;
	}

	public void setCreated(Date Created) {
		this.Created = Created;
	}

	@Column(name = "modified_by", nullable = false)
	public int getModified_by() {
		return this.Modified_by;
	}

	public void setModified_by(int Modified_by) {
		this.Modified_by = Modified_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", nullable = false, length = 19)
	public Date getModified() {
		return this.Modified;
	}

	public void setModified(Date Modified) {
		this.Modified = Modified;
	}

	@Column(name = "ordering", nullable = false)
	public int getOrdering() {
		return this.Ordering;
	}

	public void setOrdering(int Ordering) {
		this.Ordering = Ordering;
	}

	@Column(name = "state", nullable = false)
	public boolean isState() {
		return this.State;
	}

	public void setState(boolean State) {
		this.State = State;
	}

	@Column(name = "checked_out", nullable = false)
	public int getChecked_out() {
		return this.Checked_out;
	}

	public void setChecked_out(int Checked_out) {
		this.Checked_out = Checked_out;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checked_out_time", nullable = false, length = 19)
	public Date getChecked_out_time() {
		return this.Checked_out_time;
	}

	public void setChecked_out_time(Date Checked_out_time) {
		this.Checked_out_time = Checked_out_time;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}

	@Column(name = "description", nullable = false, length = 500)
	public String getDescription() {
		return this.Description;
	}

	public void setDescription(String Description) {
		this.Description = Description;
	}

	@Column(name = "logo", nullable = false)
	public String getLogo() {
		return this.Logo;
	}

	public void setLogo(String Logo) {
		this.Logo = Logo;
	}

	@Column(name = "meta", nullable = false)
	public boolean isMeta() {
		return this.Meta;
	}

	public void setMeta(boolean Meta) {
		this.Meta = Meta;
	}

	@Column(name = "diffusion", nullable = false)
	public boolean isDiffusion() {
		return this.Diffusion;
	}

	public void setDiffusion(boolean Diffusion) {
		this.Diffusion = Diffusion;
	}

	@Column(name = "view", nullable = false)
	public boolean isView() {
		return this.View;
	}

	public void setView(boolean View) {
		this.View = View;
	}

	@Column(name = "monitoring", nullable = false)
	public boolean isMonitoring() {
		return this.Monitoring;
	}

	public void setMonitoring(boolean Monitoring) {
		this.Monitoring = Monitoring;
	}

	@Column(name = "predefined", nullable = false)
	public boolean isPredefined() {
		return this.Predefined;
	}

	public void setPredefined(boolean Predefined) {
		this.Predefined = Predefined;
	}

	@Column(name = "versioning", nullable = false)
	public boolean isVersioning() {
		return this.Versioning;
	}

	public void setVersioning(boolean Versioning) {
		this.Versioning = Versioning;
	}

	@Column(name = "fragment")
	public String getFragment() {
		return this.Fragment;
	}

	public void setFragment(String Fragment) {
		this.Fragment = Fragment;
	}

	@Column(name = "sitemapparams", length = 1000)
	public String getSitemapparams() {
		return this.Sitemapparams;
	}

	public void setSitemapparams(String Sitemapparams) {
		this.Sitemapparams = Sitemapparams;
	}

	@Column(name = "access", nullable = false)
	public int getAccess() {
		return this.Access;
	}

	public void setAccess(int Access) {
		this.Access = Access;
	}

	@Column(name = "asset_id", nullable = false)
	public int getAsset_id() {
		return this.Asset_id;
	}

	public void setAsset_id(int Asset_id) {
		this.Asset_id = Asset_id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gh0jlSdiResourcetypeByParentId")
	public Set<Gh0jlSdiResourcetypelink> getGh0jlSdiResourcetypelinksForParentId() {
		return this.gh0jlSdiResourcetypelinksForParentId;
	}

	public void setGh0jlSdiResourcetypelinksForParentId(
			Set<Gh0jlSdiResourcetypelink> gh0jlSdiResourcetypelinksForParentId) {
		this.gh0jlSdiResourcetypelinksForParentId = gh0jlSdiResourcetypelinksForParentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gh0jlSdiResourcetypeByChildId")
	public Set<Gh0jlSdiResourcetypelink> getGh0jlSdiResourcetypelinksForChildId() {
		return this.gh0jlSdiResourcetypelinksForChildId;
	}

	public void setGh0jlSdiResourcetypelinksForChildId(
			Set<Gh0jlSdiResourcetypelink> gh0jlSdiResourcetypelinksForChildId) {
		this.gh0jlSdiResourcetypelinksForChildId = gh0jlSdiResourcetypelinksForChildId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gh0jlSdiResourcetype")
	public Set<Gh0jlSdiPolicyResourcetype> getGh0jlSdiPolicyResourcetypes() {
		return this.gh0jlSdiPolicyResourcetypes;
	}

	public void setGh0jlSdiPolicyResourcetypes(
			Set<Gh0jlSdiPolicyResourcetype> gh0jlSdiPolicyResourcetypes) {
		this.gh0jlSdiPolicyResourcetypes = gh0jlSdiPolicyResourcetypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gh0jlSdiResourcetype")
	public Set<Gh0jlSdiCatalogResourcetype> getGh0jlSdiCatalogResourcetypes() {
		return this.gh0jlSdiCatalogResourcetypes;
	}

	public void setGh0jlSdiCatalogResourcetypes(
			Set<Gh0jlSdiCatalogResourcetype> gh0jlSdiCatalogResourcetypes) {
		this.gh0jlSdiCatalogResourcetypes = gh0jlSdiCatalogResourcetypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gh0jlSdiResourcetype")
	public Set<SdiResource> getGh0jlSdiResources() {
		return this.gh0jlSdiResources;
	}

	public void setGh0jlSdiResources(Set<SdiResource> gh0jlSdiResources) {
		this.gh0jlSdiResources = gh0jlSdiResources;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gh0jlSdiResourcetype")
	public Set<Gh0jlSdiRelation> getGh0jlSdiRelations() {
		return this.gh0jlSdiRelations;
	}

	public void setGh0jlSdiRelations(Set<Gh0jlSdiRelation> gh0jlSdiRelations) {
		this.gh0jlSdiRelations = gh0jlSdiRelations;
	}

}
