package org.easysdi.proxy.domain;

// Generated Oct 3, 2013 1:38:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;

/**
 * SdiResourcetype generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
@FilterDef(name="entityState")
@Filter(name = "entityState",condition="state = 1")
public class SdiResourcetype implements java.io.Serializable {

	private Integer Id;
	private SdiSysAccessscope sdiSysAccessscope;
	private SdiProfile sdiProfile;
	private SdiNamespace sdiNamespace;
	private String Guid;
	private String Alias;
	private int Created_by;
	private Date Created;
	private int Modified_by;
	private Date Modified;
	private int Ordering;
	private boolean State;
	private int Checked_out;
	private Date Checked_out_time;
	private String Name;
	private String Description;
	private String Logo;
	private boolean Application;
	private boolean Diffusion;
	private boolean View;
	private boolean Monitoring;
	private boolean Predefined;
	private boolean Versioning;
	private String Fragment;
	private String Sitemapparams;
	private int Access;
	private int Asset_id;
	

	public SdiResourcetype() {
	}

	public SdiResourcetype(SdiSysAccessscope sdiSysAccessscope,
			SdiProfile sdiProfile, String Guid, String Alias,
			int Created_by, Date Created, int Modified_by, Date Modified,
			int Ordering, boolean State, int Checked_out,
			Date Checked_out_time, String Name, String Description,
			String Logo, boolean Application, boolean Diffusion, boolean View,
			boolean Monitoring, boolean Predefined, boolean Versioning,
			int Access, int Asset_id) {
		this.sdiSysAccessscope = sdiSysAccessscope;
		this.sdiProfile = sdiProfile;
		this.Guid = Guid;
		this.Alias = Alias;
		this.Created_by = Created_by;
		this.Created = Created;
		this.Modified_by = Modified_by;
		this.Modified = Modified;
		this.Ordering = Ordering;
		this.State = State;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Name = Name;
		this.Description = Description;
		this.Logo = Logo;
		this.Application = Application;
		this.Diffusion = Diffusion;
		this.View = View;
		this.Monitoring = Monitoring;
		this.Predefined = Predefined;
		this.Versioning = Versioning;
		this.Access = Access;
		this.Asset_id = Asset_id;
	}

	public SdiResourcetype(SdiSysAccessscope sdiSysAccessscope,
			SdiProfile sdiProfile,
			SdiNamespace sdiNamespace, String Guid, String Alias,
			int Created_by, Date Created, int Modified_by, Date Modified,
			int Ordering, boolean State, int Checked_out,
			Date Checked_out_time, String Name, String Description,
			String Logo, boolean Application, boolean Diffusion, boolean View,
			boolean Monitoring, boolean Predefined, boolean Versioning,
			String Fragment, String Sitemapparams, int Access, int Asset_id) {
		this.sdiSysAccessscope = sdiSysAccessscope;
		this.sdiProfile = sdiProfile;
		this.sdiNamespace = sdiNamespace;
		this.Guid = Guid;
		this.Alias = Alias;
		this.Created_by = Created_by;
		this.Created = Created;
		this.Modified_by = Modified_by;
		this.Modified = Modified;
		this.Ordering = Ordering;
		this.State = State;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Name = Name;
		this.Description = Description;
		this.Logo = Logo;
		this.Application = Application;
		this.Diffusion = Diffusion;
		this.View = View;
		this.Monitoring = Monitoring;
		this.Predefined = Predefined;
		this.Versioning = Versioning;
		this.Fragment = Fragment;
		this.Sitemapparams = Sitemapparams;
		this.Access = Access;
		this.Asset_id = Asset_id;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accessscope_id", nullable = false)
	public SdiSysAccessscope getSdiSysAccessscope() {
		return this.sdiSysAccessscope;
	}

	public void setSdiSysAccessscope(
			SdiSysAccessscope sdiSysAccessscope) {
		this.sdiSysAccessscope = sdiSysAccessscope;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profile_id", nullable = false)
	public SdiProfile getSdiProfile() {
		return this.sdiProfile;
	}

	public void setSdiProfile(SdiProfile sdiProfile) {
		this.sdiProfile = sdiProfile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fragmentnamespace_id")
	public SdiNamespace getSdiNamespace() {
		return this.sdiNamespace;
	}

	public void setSdiNamespace(SdiNamespace sdiNamespace) {
		this.sdiNamespace = sdiNamespace;
	}

	@Column(name = "guid", nullable = false, length = 36)
	public String getGuid() {
		return this.Guid;
	}

	public void setGuid(String Guid) {
		this.Guid = Guid;
	}

	@Column(name = "alias", nullable = false, length = 50)
	public String getAlias() {
		return this.Alias;
	}

	public void setAlias(String Alias) {
		this.Alias = Alias;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreated_by() {
		return this.Created_by;
	}

	public void setCreated_by(int Created_by) {
		this.Created_by = Created_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.Created;
	}

	public void setCreated(Date Created) {
		this.Created = Created;
	}

	@Column(name = "modified_by", nullable = false)
	public int getModified_by() {
		return this.Modified_by;
	}

	public void setModified_by(int Modified_by) {
		this.Modified_by = Modified_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", nullable = false, length = 19)
	public Date getModified() {
		return this.Modified;
	}

	public void setModified(Date Modified) {
		this.Modified = Modified;
	}

	@Column(name = "ordering", nullable = false)
	public int getOrdering() {
		return this.Ordering;
	}

	public void setOrdering(int Ordering) {
		this.Ordering = Ordering;
	}

	@Column(name = "state", nullable = false)
	public boolean isState() {
		return this.State;
	}

	public void setState(boolean State) {
		this.State = State;
	}

	@Column(name = "checked_out", nullable = false)
	public int getChecked_out() {
		return this.Checked_out;
	}

	public void setChecked_out(int Checked_out) {
		this.Checked_out = Checked_out;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checked_out_time", nullable = false, length = 19)
	public Date getChecked_out_time() {
		return this.Checked_out_time;
	}

	public void setChecked_out_time(Date Checked_out_time) {
		this.Checked_out_time = Checked_out_time;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}

	@Column(name = "description", nullable = false, length = 500)
	public String getDescription() {
		return this.Description;
	}

	public void setDescription(String Description) {
		this.Description = Description;
	}

	@Column(name = "logo", nullable = false)
	public String getLogo() {
		return this.Logo;
	}

	public void setLogo(String Logo) {
		this.Logo = Logo;
	}

	@Column(name = "application", nullable = false)
	public boolean isApplication() {
		return this.Application;
	}

	public void setApplication(boolean Application) {
		this.Application = Application;
	}

	@Column(name = "diffusion", nullable = false)
	public boolean isDiffusion() {
		return this.Diffusion;
	}

	public void setDiffusion(boolean Diffusion) {
		this.Diffusion = Diffusion;
	}

	@Column(name = "view", nullable = false)
	public boolean isView() {
		return this.View;
	}

	public void setView(boolean View) {
		this.View = View;
	}

	@Column(name = "monitoring", nullable = false)
	public boolean isMonitoring() {
		return this.Monitoring;
	}

	public void setMonitoring(boolean Monitoring) {
		this.Monitoring = Monitoring;
	}

	@Column(name = "predefined", nullable = false)
	public boolean isPredefined() {
		return this.Predefined;
	}

	public void setPredefined(boolean Predefined) {
		this.Predefined = Predefined;
	}

	@Column(name = "versioning", nullable = false)
	public boolean isVersioning() {
		return this.Versioning;
	}

	public void setVersioning(boolean Versioning) {
		this.Versioning = Versioning;
	}

	@Column(name = "fragment")
	public String getFragment() {
		return this.Fragment;
	}

	public void setFragment(String Fragment) {
		this.Fragment = Fragment;
	}

	@Column(name = "sitemapparams", length = 1000)
	public String getSitemapparams() {
		return this.Sitemapparams;
	}

	public void setSitemapparams(String Sitemapparams) {
		this.Sitemapparams = Sitemapparams;
	}

	@Column(name = "access", nullable = false)
	public int getAccess() {
		return this.Access;
	}

	public void setAccess(int Access) {
		this.Access = Access;
	}

	@Column(name = "asset_id", nullable = false)
	public int getAsset_id() {
		return this.Asset_id;
	}

	public void setAsset_id(int Asset_id) {
		this.Asset_id = Asset_id;
	}

}
