package org.easysdi.proxy.domain;

// Generated Oct 3, 2013 2:18:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SdiMetadata generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
public class SdiMetadata implements java.io.Serializable {

	private Integer Id;
	private SdiSysMetadatastate sdiSysMetadatastate;
	private SdiVersion sdiVersion;
	private SdiSysAccessscope sdiSysAccessscope;
	private String Guid;
	private int Created_by;
	private Date Created;
	private Integer Modified_by;
	private Date Modified;
	private Integer Ordering;
	private int Checked_out;
	private Date Checked_out_time;
	private Date Published;
	private Date Archived;
	private Date Lastsynchronization;
	private Integer Synchronized_by;
	private boolean Notification;
	private int Access;
	private int Asset_id;

	public SdiMetadata() {
	}

	public SdiMetadata(SdiSysMetadatastate sdiSysMetadatastate,
			SdiVersion sdiVersion,
			SdiSysAccessscope sdiSysAccessscope, String Guid,
			int Created_by, Date Created, int Checked_out,
			Date Checked_out_time, boolean Notification, int Access,
			int Asset_id) {
		this.sdiSysMetadatastate = sdiSysMetadatastate;
		this.sdiVersion = sdiVersion;
		this.sdiSysAccessscope = sdiSysAccessscope;
		this.Guid = Guid;
		this.Created_by = Created_by;
		this.Created = Created;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Notification = Notification;
		this.Access = Access;
		this.Asset_id = Asset_id;
	}

	public SdiMetadata(SdiSysMetadatastate sdiSysMetadatastate,
			SdiVersion sdiVersion,
			SdiSysAccessscope sdiSysAccessscope, String Guid,
			int Created_by, Date Created, Integer Modified_by, Date Modified,
			Integer Ordering, int Checked_out, Date Checked_out_time,
			Date Published, Date Archived, Date Lastsynchronization,
			Integer Synchronized_by, boolean Notification, int Access,
			int Asset_id) {
		this.sdiSysMetadatastate = sdiSysMetadatastate;
		this.sdiVersion = sdiVersion;
		this.sdiSysAccessscope = sdiSysAccessscope;
		this.Guid = Guid;
		this.Created_by = Created_by;
		this.Created = Created;
		this.Modified_by = Modified_by;
		this.Modified = Modified;
		this.Ordering = Ordering;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Published = Published;
		this.Archived = Archived;
		this.Lastsynchronization = Lastsynchronization;
		this.Synchronized_by = Synchronized_by;
		this.Notification = Notification;
		this.Access = Access;
		this.Asset_id = Asset_id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "metadatastate_id", nullable = false)
	public SdiSysMetadatastate getSdiSysMetadatastate() {
		return this.sdiSysMetadatastate;
	}

	public void setSdiSysMetadatastate(
			SdiSysMetadatastate sdiSysMetadatastate) {
		this.sdiSysMetadatastate = sdiSysMetadatastate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "version_id", nullable = false)
	public SdiVersion getSdiVersion() {
		return this.sdiVersion;
	}

	public void setSdiVersion(SdiVersion sdiVersion) {
		this.sdiVersion = sdiVersion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accessscope_id", nullable = false)
	public SdiSysAccessscope getSdiSysAccessscope() {
		return this.sdiSysAccessscope;
	}

	public void setSdiSysAccessscope(
			SdiSysAccessscope sdiSysAccessscope) {
		this.sdiSysAccessscope = sdiSysAccessscope;
	}

	@Column(name = "guid", nullable = false, length = 36)
	public String getGuid() {
		return this.Guid;
	}

	public void setGuid(String Guid) {
		this.Guid = Guid;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreated_by() {
		return this.Created_by;
	}

	public void setCreated_by(int Created_by) {
		this.Created_by = Created_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.Created;
	}

	public void setCreated(Date Created) {
		this.Created = Created;
	}

	@Column(name = "modified_by")
	public Integer getModified_by() {
		return this.Modified_by;
	}

	public void setModified_by(Integer Modified_by) {
		this.Modified_by = Modified_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 19)
	public Date getModified() {
		return this.Modified;
	}

	public void setModified(Date Modified) {
		this.Modified = Modified;
	}

	@Column(name = "ordering")
	public Integer getOrdering() {
		return this.Ordering;
	}

	public void setOrdering(Integer Ordering) {
		this.Ordering = Ordering;
	}

	@Column(name = "checked_out", nullable = false)
	public int getChecked_out() {
		return this.Checked_out;
	}

	public void setChecked_out(int Checked_out) {
		this.Checked_out = Checked_out;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checked_out_time", nullable = false, length = 19)
	public Date getChecked_out_time() {
		return this.Checked_out_time;
	}

	public void setChecked_out_time(Date Checked_out_time) {
		this.Checked_out_time = Checked_out_time;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "published", length = 19)
	public Date getPublished() {
		return this.Published;
	}

	public void setPublished(Date Published) {
		this.Published = Published;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "archived", length = 19)
	public Date getArchived() {
		return this.Archived;
	}

	public void setArchived(Date Archived) {
		this.Archived = Archived;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastsynchronization", length = 19)
	public Date getLastsynchronization() {
		return this.Lastsynchronization;
	}

	public void setLastsynchronization(Date Lastsynchronization) {
		this.Lastsynchronization = Lastsynchronization;
	}

	@Column(name = "synchronized_by")
	public Integer getSynchronized_by() {
		return this.Synchronized_by;
	}

	public void setSynchronized_by(Integer Synchronized_by) {
		this.Synchronized_by = Synchronized_by;
	}

	@Column(name = "notification", nullable = false)
	public boolean isNotification() {
		return this.Notification;
	}

	public void setNotification(boolean Notification) {
		this.Notification = Notification;
	}

	@Column(name = "access", nullable = false)
	public int getAccess() {
		return this.Access;
	}

	public void setAccess(int Access) {
		this.Access = Access;
	}

	@Column(name = "asset_id", nullable = false)
	public int getAsset_id() {
		return this.Asset_id;
	}

	public void setAsset_id(int Asset_id) {
		this.Asset_id = Asset_id;
	}

}
