package org.easysdi.proxy.domain;

// Generated Apr 9, 2013 11:54:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;

/**
 * SdiSysMetadatastate generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
@FilterDef(name="entityState")
@Filter(name = "entityState",condition="state = 1")
public class SdiSysMetadatastate implements java.io.Serializable {

	private static final long serialVersionUID = 3308366926335622982L;
	private Integer Id;
	private int Ordering;
	private int State;
	private String Value;
	private Set<SdiPolicyMetadatastate> sdiPolicyMetadatastates = new HashSet<SdiPolicyMetadatastate>(
			0);

	public SdiSysMetadatastate() {
	}

	public SdiSysMetadatastate(int Ordering, int State, String Value) {
		this.Ordering = Ordering;
		this.State = State;
		this.Value = Value;
	}

	public SdiSysMetadatastate(int Ordering, int State, String Value,
			Set<SdiPolicyMetadatastate> sdiPolicyMetadatastates) {
		this.Ordering = Ordering;
		this.State = State;
		this.Value = Value;
		this.sdiPolicyMetadatastates = sdiPolicyMetadatastates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "ordering", nullable = false)
	public int getOrdering() {
		return this.Ordering;
	}

	public void setOrdering(int Ordering) {
		this.Ordering = Ordering;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.State;
	}

	public void setState(int State) {
		this.State = State;
	}

	@Column(name = "value", nullable = false, length = 150)
	public String getValue() {
		return this.Value;
	}

	public void setValue(String Value) {
		this.Value = Value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiSysMetadatastate")
	public Set<SdiPolicyMetadatastate> getSdiPolicyMetadatastates() {
		return this.sdiPolicyMetadatastates;
	}

	public void setSdiPolicyMetadatastates(
			Set<SdiPolicyMetadatastate> sdiPolicyMetadatastates) {
		this.sdiPolicyMetadatastates = sdiPolicyMetadatastates;
	}

}
