//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.13 at 04:39:39 PM CET 
//


package ch.interlis.interlis2.GM03V18;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Entries complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Entries">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="TAGENTRY" type="{http://www.interlis.ch/INTERLIS2.2}Tagentry"/>
 *           &lt;element name="VALENTRY" type="{http://www.interlis.ch/INTERLIS2.2}Valentry"/>
 *           &lt;element name="DELENTRY" type="{http://www.interlis.ch/INTERLIS2.2}Delentry"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="FOR" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Entries", propOrder = {
    "tagentryOrVALENTRYOrDELENTRY"
})
public class Entries {

    @XmlElements({
        @XmlElement(name = "VALENTRY", type = Valentry.class),
        @XmlElement(name = "DELENTRY", type = Delentry.class),
        @XmlElement(name = "TAGENTRY", type = Tagentry.class)
    })
    protected List<Object> tagentryOrVALENTRYOrDELENTRY;
    @XmlAttribute(name = "FOR", required = true)
    protected String _for;

    /**
     * Gets the value of the tagentryOrVALENTRYOrDELENTRY property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tagentryOrVALENTRYOrDELENTRY property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTAGENTRYOrVALENTRYOrDELENTRY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Valentry }
     * {@link Delentry }
     * {@link Tagentry }
     * 
     * 
     */
    public List<Object> getTAGENTRYOrVALENTRYOrDELENTRY() {
        if (tagentryOrVALENTRYOrDELENTRY == null) {
            tagentryOrVALENTRYOrDELENTRY = new ArrayList<Object>();
        }
        return this.tagentryOrVALENTRYOrDELENTRY;
    }

    /**
     * Gets the value of the for property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOR() {
        return _for;
    }

    /**
     * Sets the value of the for property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOR(String value) {
        this._for = value;
    }

}
