package org.easysdi.proxy.domain;

// Generated Mar 15, 2013 2:35:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SdiAddress generated by hbm2java
 */
@Entity
@Table(name = "proxy_sdi_address", catalog = "proxy330")
public class SdiAddress implements java.io.Serializable {

	private Integer id;
	private SdiUser sdiUser;
	private SdiSysAddresstype sdiSysAddresstype;
	private SdiOrganism sdiOrganism;
	private SdiSysCountry sdiSysCountry;
	private String guid;
	private String alias;
	private int createdBy;
	private Date created;
	private Integer modifiedBy;
	private Date modified;
	private Integer ordering;
	private boolean state;
	private int checkedOut;
	private Date checkedOutTime;
	private String civility;
	private String firstname;
	private String lastname;
	private String function;
	private String address;
	private String addresscomplement;
	private String postalcode;
	private String postalbox;
	private String locality;
	private String phone;
	private String mobile;
	private String fax;
	private String email;
	private boolean sameascontact;

	public SdiAddress() {
	}

	public SdiAddress(SdiSysAddresstype sdiSysAddresstype, String guid,
			int createdBy, Date created, boolean state, int checkedOut,
			Date checkedOutTime, boolean sameascontact) {
		this.sdiSysAddresstype = sdiSysAddresstype;
		this.guid = guid;
		this.createdBy = createdBy;
		this.created = created;
		this.state = state;
		this.checkedOut = checkedOut;
		this.checkedOutTime = checkedOutTime;
		this.sameascontact = sameascontact;
	}

	public SdiAddress(SdiUser sdiUser, SdiSysAddresstype sdiSysAddresstype,
			SdiOrganism sdiOrganism, SdiSysCountry sdiSysCountry, String guid,
			String alias, int createdBy, Date created, Integer modifiedBy,
			Date modified, Integer ordering, boolean state, int checkedOut,
			Date checkedOutTime, String civility, String firstname,
			String lastname, String function, String address,
			String addresscomplement, String postalcode, String postalbox,
			String locality, String phone, String mobile, String fax,
			String email, boolean sameascontact) {
		this.sdiUser = sdiUser;
		this.sdiSysAddresstype = sdiSysAddresstype;
		this.sdiOrganism = sdiOrganism;
		this.sdiSysCountry = sdiSysCountry;
		this.guid = guid;
		this.alias = alias;
		this.createdBy = createdBy;
		this.created = created;
		this.modifiedBy = modifiedBy;
		this.modified = modified;
		this.ordering = ordering;
		this.state = state;
		this.checkedOut = checkedOut;
		this.checkedOutTime = checkedOutTime;
		this.civility = civility;
		this.firstname = firstname;
		this.lastname = lastname;
		this.function = function;
		this.address = address;
		this.addresscomplement = addresscomplement;
		this.postalcode = postalcode;
		this.postalbox = postalbox;
		this.locality = locality;
		this.phone = phone;
		this.mobile = mobile;
		this.fax = fax;
		this.email = email;
		this.sameascontact = sameascontact;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public SdiUser getSdiUser() {
		return this.sdiUser;
	}

	public void setSdiUser(SdiUser sdiUser) {
		this.sdiUser = sdiUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "addresstype_id", nullable = false)
	public SdiSysAddresstype getSdiSysAddresstype() {
		return this.sdiSysAddresstype;
	}

	public void setSdiSysAddresstype(SdiSysAddresstype sdiSysAddresstype) {
		this.sdiSysAddresstype = sdiSysAddresstype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organism_id")
	public SdiOrganism getSdiOrganism() {
		return this.sdiOrganism;
	}

	public void setSdiOrganism(SdiOrganism sdiOrganism) {
		this.sdiOrganism = sdiOrganism;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_id")
	public SdiSysCountry getSdiSysCountry() {
		return this.sdiSysCountry;
	}

	public void setSdiSysCountry(SdiSysCountry sdiSysCountry) {
		this.sdiSysCountry = sdiSysCountry;
	}

	@Column(name = "guid", nullable = false, length = 36)
	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	@Column(name = "alias", length = 20)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "modified_by")
	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 19)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Column(name = "ordering")
	public Integer getOrdering() {
		return this.ordering;
	}

	public void setOrdering(Integer ordering) {
		this.ordering = ordering;
	}

	@Column(name = "state", nullable = false)
	public boolean isState() {
		return this.state;
	}

	public void setState(boolean state) {
		this.state = state;
	}

	@Column(name = "checked_out", nullable = false)
	public int getCheckedOut() {
		return this.checkedOut;
	}

	public void setCheckedOut(int checkedOut) {
		this.checkedOut = checkedOut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checked_out_time", nullable = false, length = 19)
	public Date getCheckedOutTime() {
		return this.checkedOutTime;
	}

	public void setCheckedOutTime(Date checkedOutTime) {
		this.checkedOutTime = checkedOutTime;
	}

	@Column(name = "civility", length = 100)
	public String getCivility() {
		return this.civility;
	}

	public void setCivility(String civility) {
		this.civility = civility;
	}

	@Column(name = "firstname", length = 100)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 100)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "function", length = 100)
	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "addresscomplement", length = 100)
	public String getAddresscomplement() {
		return this.addresscomplement;
	}

	public void setAddresscomplement(String addresscomplement) {
		this.addresscomplement = addresscomplement;
	}

	@Column(name = "postalcode", length = 10)
	public String getPostalcode() {
		return this.postalcode;
	}

	public void setPostalcode(String postalcode) {
		this.postalcode = postalcode;
	}

	@Column(name = "postalbox", length = 10)
	public String getPostalbox() {
		return this.postalbox;
	}

	public void setPostalbox(String postalbox) {
		this.postalbox = postalbox;
	}

	@Column(name = "locality", length = 100)
	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "mobile", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "fax", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "sameascontact", nullable = false)
	public boolean isSameascontact() {
		return this.sameascontact;
	}

	public void setSameascontact(boolean sameascontact) {
		this.sameascontact = sameascontact;
	}

}
