package org.easysdi.proxy.domain;

// Generated Apr 9, 2013 11:54:41 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SdiCswSpatialpolicy generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
public class SdiCswSpatialpolicy implements java.io.Serializable {

	private Integer Id;
	private BigDecimal Eastboundlongitude;
	private BigDecimal Westboundlongitude;
	private BigDecimal Northboundlatitude;
	private BigDecimal Southboundlatitude;
	private BigDecimal Maxx;
	private BigDecimal Maxy;
	private BigDecimal Minx;
	private BigDecimal Miny;
	private String Srssource;
	private Set<SdiPolicy> sdiPolicies = new HashSet<SdiPolicy>(0);
	private Set<SdiPhysicalservicePolicy> sdiPhysicalservicePolicies = new HashSet<SdiPhysicalservicePolicy>(
			0);

	public SdiCswSpatialpolicy() {
	}

	public SdiCswSpatialpolicy(BigDecimal Eastboundlongitude,
			BigDecimal Westboundlongitude, BigDecimal Northboundlatitude,
			BigDecimal Southboundlatitude, BigDecimal Maxx, BigDecimal Maxy,
			BigDecimal Minx, BigDecimal Miny, String Srssource,
			Set<SdiPolicy> sdiPolicies,
			Set<SdiPhysicalservicePolicy> sdiPhysicalservicePolicies) {
		this.Eastboundlongitude = Eastboundlongitude;
		this.Westboundlongitude = Westboundlongitude;
		this.Northboundlatitude = Northboundlatitude;
		this.Southboundlatitude = Southboundlatitude;
		this.Maxx = Maxx;
		this.Maxy = Maxy;
		this.Minx = Minx;
		this.Miny = Miny;
		this.Srssource = Srssource;
		this.sdiPolicies = sdiPolicies;
		this.sdiPhysicalservicePolicies = sdiPhysicalservicePolicies;
	}

	@Transient
	public Boolean isValid() {
		if(this.Eastboundlongitude != null 
			&& this.Westboundlongitude != null
			&& this.Northboundlatitude != null
			&& this.Southboundlatitude != null)
			return true;
		return false;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "eastboundlongitude", precision = 10, scale = 6)
	public BigDecimal getEastboundlongitude() {
		return this.Eastboundlongitude;
	}

	public void setEastboundlongitude(BigDecimal Eastboundlongitude) {
		this.Eastboundlongitude = Eastboundlongitude;
	}

	@Column(name = "westboundlongitude", precision = 10, scale = 6)
	public BigDecimal getWestboundlongitude() {
		return this.Westboundlongitude;
	}

	public void setWestboundlongitude(BigDecimal Westboundlongitude) {
		this.Westboundlongitude = Westboundlongitude;
	}

	@Column(name = "northboundlatitude", precision = 10, scale = 6)
	public BigDecimal getNorthboundlatitude() {
		return this.Northboundlatitude;
	}

	public void setNorthboundlatitude(BigDecimal Northboundlatitude) {
		this.Northboundlatitude = Northboundlatitude;
	}

	@Column(name = "southboundlatitude", precision = 10, scale = 6)
	public BigDecimal getSouthboundlatitude() {
		return this.Southboundlatitude;
	}

	public void setSouthboundlatitude(BigDecimal Southboundlatitude) {
		this.Southboundlatitude = Southboundlatitude;
	}

	@Column(name = "maxx", precision = 18, scale = 6)
	public BigDecimal getMaxx() {
		return this.Maxx;
	}

	public void setMaxx(BigDecimal Maxx) {
		this.Maxx = Maxx;
	}

	@Column(name = "maxy", precision = 18, scale = 6)
	public BigDecimal getMaxy() {
		return this.Maxy;
	}

	public void setMaxy(BigDecimal Maxy) {
		this.Maxy = Maxy;
	}

	@Column(name = "minx", precision = 18, scale = 6)
	public BigDecimal getMinx() {
		return this.Minx;
	}

	public void setMinx(BigDecimal Minx) {
		this.Minx = Minx;
	}

	@Column(name = "miny", precision = 18, scale = 6)
	public BigDecimal getMiny() {
		return this.Miny;
	}

	public void setMiny(BigDecimal Miny) {
		this.Miny = Miny;
	}

	@Column(name = "srssource")
	public String getSrssource() {
		return this.Srssource;
	}

	public void setSrssource(String Srssource) {
		this.Srssource = Srssource;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiCswSpatialpolicy")
	public Set<SdiPolicy> getSdiPolicies() {
		return this.sdiPolicies;
	}

	public void setSdiPolicies(Set<SdiPolicy> sdiPolicies) {
		this.sdiPolicies = sdiPolicies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiCswSpatialpolicy")
	public Set<SdiPhysicalservicePolicy> getSdiPhysicalservicePolicies() {
		return this.sdiPhysicalservicePolicies;
	}

	public void setSdiPhysicalservicePolicies(
			Set<SdiPhysicalservicePolicy> sdiPhysicalservicePolicies) {
		this.sdiPhysicalservicePolicies = sdiPhysicalservicePolicies;
	}

}
