package org.easysdi.proxy.domain;

// Generated Mar 28, 2013 4:35:10 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;

/**
 * SdiCswSpatialpolicy generated by hbm2java
 */
@Entity
public class SdiCswSpatialpolicy implements java.io.Serializable {

	private Integer Id;
	private BigDecimal Eastboundlongitude;
	private BigDecimal Westboundlongitude;
	private BigDecimal Northboundlatitude;
	private BigDecimal Southboundlatitude;
	private BigDecimal Maxx;
	private BigDecimal Maxy;
	private BigDecimal Minx;
	private BigDecimal Miny;
	private String Srssource;

	public SdiCswSpatialpolicy() {
	}

	public SdiCswSpatialpolicy(BigDecimal Eastboundlongitude,
			BigDecimal Westboundlongitude, BigDecimal Northboundlatitude,
			BigDecimal Southboundlatitude, BigDecimal Maxx, BigDecimal Maxy,
			BigDecimal Minx, BigDecimal Miny, String Srssource) {
		this.Eastboundlongitude = Eastboundlongitude;
		this.Westboundlongitude = Westboundlongitude;
		this.Northboundlatitude = Northboundlatitude;
		this.Southboundlatitude = Southboundlatitude;
		this.Maxx = Maxx;
		this.Maxy = Maxy;
		this.Minx = Minx;
		this.Miny = Miny;
		this.Srssource = Srssource;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "eastboundlongitude", precision = 10, scale = 6)
	public BigDecimal getEastboundlongitude() {
		return this.Eastboundlongitude;
	}

	public void setEastboundlongitude(BigDecimal Eastboundlongitude) {
		this.Eastboundlongitude = Eastboundlongitude;
	}

	@Column(name = "westboundlongitude", precision = 10, scale = 6)
	public BigDecimal getWestboundlongitude() {
		return this.Westboundlongitude;
	}

	public void setWestboundlongitude(BigDecimal Westboundlongitude) {
		this.Westboundlongitude = Westboundlongitude;
	}

	@Column(name = "northboundlatitude", precision = 10, scale = 6)
	public BigDecimal getNorthboundlatitude() {
		return this.Northboundlatitude;
	}

	public void setNorthboundlatitude(BigDecimal Northboundlatitude) {
		this.Northboundlatitude = Northboundlatitude;
	}

	@Column(name = "southboundlatitude", precision = 10, scale = 6)
	public BigDecimal getSouthboundlatitude() {
		return this.Southboundlatitude;
	}

	public void setSouthboundlatitude(BigDecimal Southboundlatitude) {
		this.Southboundlatitude = Southboundlatitude;
	}

	@Column(name = "maxx", precision = 18, scale = 6)
	public BigDecimal getMaxx() {
		return this.Maxx;
	}

	public void setMaxx(BigDecimal Maxx) {
		this.Maxx = Maxx;
	}

	@Column(name = "maxy", precision = 18, scale = 6)
	public BigDecimal getMaxy() {
		return this.Maxy;
	}

	public void setMaxy(BigDecimal Maxy) {
		this.Maxy = Maxy;
	}

	@Column(name = "minx", precision = 18, scale = 6)
	public BigDecimal getMinx() {
		return this.Minx;
	}

	public void setMinx(BigDecimal Minx) {
		this.Minx = Minx;
	}

	@Column(name = "miny", precision = 18, scale = 6)
	public BigDecimal getMiny() {
		return this.Miny;
	}

	public void setMiny(BigDecimal Miny) {
		this.Miny = Miny;
	}

	@Column(name = "srssource")
	public String getSrssource() {
		return this.Srssource;
	}

	public void setSrssource(String Srssource) {
		this.Srssource = Srssource;
	}

}
