package org.easysdi.proxy.domain;

// Generated Mar 28, 2013 4:35:10 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;

/**
 * SdiExcludedattribute generated by hbm2java
 */
@Entity
public class SdiExcludedattribute implements java.io.Serializable {

	private Integer Id;
	private String Path;
	private int Policy_id;

	public SdiExcludedattribute() {
	}

	public SdiExcludedattribute(String Path, int Policy_id) {
		this.Path = Path;
		this.Policy_id = Policy_id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "path", nullable = false, length = 500)
	public String getPath() {
		return this.Path;
	}

	public void setPath(String Path) {
		this.Path = Path;
	}

	@Column(name = "policy_id", nullable = false)
	public int getPolicy_id() {
		return this.Policy_id;
	}

	public void setPolicy_id(int Policy_id) {
		this.Policy_id = Policy_id;
	}

}
