package org.easysdi.proxy.domain;

// Generated Apr 9, 2013 11:54:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SdiFeaturetypePolicy generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
public class SdiFeaturetypePolicy implements java.io.Serializable {

	private Integer Id;
	private SdiWfsSpatialpolicy sdiWfsSpatialpolicy;
	private SdiPhysicalservicePolicy sdiPhysicalservicePolicy;
	private String Name;
	private String Description;
	private boolean Enabled;
	private boolean Inheritedspatialpolicy;
	private Set<SdiIncludedattribute> sdiIncludedattributes = new HashSet<SdiIncludedattribute>(
			0);

	public SdiFeaturetypePolicy() {
	}

	public SdiFeaturetypePolicy(
			SdiPhysicalservicePolicy sdiPhysicalservicePolicy, String Name,
			boolean Enabled, boolean Inheritedspatialpolicy) {
		this.sdiPhysicalservicePolicy = sdiPhysicalservicePolicy;
		this.Name = Name;
		this.Enabled = Enabled;
		this.Inheritedspatialpolicy = Inheritedspatialpolicy;
	}

	public SdiFeaturetypePolicy(SdiWfsSpatialpolicy sdiWfsSpatialpolicy,
			SdiPhysicalservicePolicy sdiPhysicalservicePolicy, String Name,
			String Description, boolean Enabled,
			boolean Inheritedspatialpolicy,
			Set<SdiIncludedattribute> sdiIncludedattributes) {
		this.sdiWfsSpatialpolicy = sdiWfsSpatialpolicy;
		this.sdiPhysicalservicePolicy = sdiPhysicalservicePolicy;
		this.Name = Name;
		this.Description = Description;
		this.Enabled = Enabled;
		this.Inheritedspatialpolicy = Inheritedspatialpolicy;
		this.sdiIncludedattributes = sdiIncludedattributes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "spatialpolicy_id")
	public SdiWfsSpatialpolicy getSdiWfsSpatialpolicy() {
		return this.sdiWfsSpatialpolicy;
	}

	public void setSdiWfsSpatialpolicy(SdiWfsSpatialpolicy sdiWfsSpatialpolicy) {
		this.sdiWfsSpatialpolicy = sdiWfsSpatialpolicy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "physicalservicepolicy_id", nullable = false)
	public SdiPhysicalservicePolicy getSdiPhysicalservicePolicy() {
		return this.sdiPhysicalservicePolicy;
	}

	public void setSdiPhysicalservicePolicy(
			SdiPhysicalservicePolicy sdiPhysicalservicePolicy) {
		this.sdiPhysicalservicePolicy = sdiPhysicalservicePolicy;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.Description;
	}

	public void setDescription(String Description) {
		this.Description = Description;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.Enabled;
	}

	public void setEnabled(boolean Enabled) {
		this.Enabled = Enabled;
	}

	@Column(name = "inheritedspatialpolicy", nullable = false)
	public boolean isInheritedspatialpolicy() {
		return this.Inheritedspatialpolicy;
	}

	public void setInheritedspatialpolicy(boolean Inheritedspatialpolicy) {
		this.Inheritedspatialpolicy = Inheritedspatialpolicy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiFeaturetypePolicy")
	public Set<SdiIncludedattribute> getSdiIncludedattributes() {
		return this.sdiIncludedattributes;
	}

	public void setSdiIncludedattributes(
			Set<SdiIncludedattribute> sdiIncludedattributes) {
		this.sdiIncludedattributes = sdiIncludedattributes;
	}

}
