package org.easysdi.proxy.domain;

// Generated Apr 9, 2013 11:54:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SdiOrganism generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
public class SdiOrganism implements java.io.Serializable {

	private Integer Id;
	private String Guid;
	private int Created_by;
	private Date Created;
	private Integer Modified_by;
	private Date Modified;
	private int Ordering;
	private int State;
	private int Checked_out;
	private Date Checked_out_time;
	private String Acronym;
	private String Description;
	private String Logo;
	private String Name;
	private String Website;
	private int Access;
	private int Asset_id;
	private Set<SdiPolicyOrganism> sdiPolicyOrganisms = new HashSet<SdiPolicyOrganism>(
			0);
	private Set<SdiVirtualserviceOrganism> sdiVirtualserviceOrganisms = new HashSet<SdiVirtualserviceOrganism>(
			0);
	private Set<SdiUserRoleOrganism> sdiUserRoleOrganisms = new HashSet<SdiUserRoleOrganism>(
			0);
	private Set<SdiPhysicalserviceOrganism> sdiPhysicalserviceOrganisms = new HashSet<SdiPhysicalserviceOrganism>(
			0);

	public SdiOrganism() {
	}

	public SdiOrganism(String Guid, int Created_by, Date Created, int Ordering,
			int State, int Checked_out, Date Checked_out_time, String Name,
			int Access, int Asset_id) {
		this.Guid = Guid;
		this.Created_by = Created_by;
		this.Created = Created;
		this.Ordering = Ordering;
		this.State = State;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Name = Name;
		this.Access = Access;
		this.Asset_id = Asset_id;
	}

	public SdiOrganism(String Guid, int Created_by, Date Created,
			Integer Modified_by, Date Modified, int Ordering, int State,
			int Checked_out, Date Checked_out_time, String Acronym,
			String Description, String Logo, String Name, String Website,
			int Access, int Asset_id,
			Set<SdiPolicyOrganism> sdiPolicyOrganisms,
			Set<SdiVirtualserviceOrganism> sdiVirtualserviceOrganisms,
			Set<SdiUserRoleOrganism> sdiUserRoleOrganisms,
			Set<SdiPhysicalserviceOrganism> sdiPhysicalserviceOrganisms) {
		this.Guid = Guid;
		this.Created_by = Created_by;
		this.Created = Created;
		this.Modified_by = Modified_by;
		this.Modified = Modified;
		this.Ordering = Ordering;
		this.State = State;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Acronym = Acronym;
		this.Description = Description;
		this.Logo = Logo;
		this.Name = Name;
		this.Website = Website;
		this.Access = Access;
		this.Asset_id = Asset_id;
		this.sdiPolicyOrganisms = sdiPolicyOrganisms;
		this.sdiVirtualserviceOrganisms = sdiVirtualserviceOrganisms;
		this.sdiUserRoleOrganisms = sdiUserRoleOrganisms;
		this.sdiPhysicalserviceOrganisms = sdiPhysicalserviceOrganisms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "guid", nullable = false, length = 36)
	public String getGuid() {
		return this.Guid;
	}

	public void setGuid(String Guid) {
		this.Guid = Guid;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreated_by() {
		return this.Created_by;
	}

	public void setCreated_by(int Created_by) {
		this.Created_by = Created_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.Created;
	}

	public void setCreated(Date Created) {
		this.Created = Created;
	}

	@Column(name = "modified_by")
	public Integer getModified_by() {
		return this.Modified_by;
	}

	public void setModified_by(Integer Modified_by) {
		this.Modified_by = Modified_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 19)
	public Date getModified() {
		return this.Modified;
	}

	public void setModified(Date Modified) {
		this.Modified = Modified;
	}

	@Column(name = "ordering", nullable = false)
	public int getOrdering() {
		return this.Ordering;
	}

	public void setOrdering(int Ordering) {
		this.Ordering = Ordering;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.State;
	}

	public void setState(int State) {
		this.State = State;
	}

	@Column(name = "checked_out", nullable = false)
	public int getChecked_out() {
		return this.Checked_out;
	}

	public void setChecked_out(int Checked_out) {
		this.Checked_out = Checked_out;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checked_out_time", nullable = false, length = 19)
	public Date getChecked_out_time() {
		return this.Checked_out_time;
	}

	public void setChecked_out_time(Date Checked_out_time) {
		this.Checked_out_time = Checked_out_time;
	}

	@Column(name = "acronym", length = 150)
	public String getAcronym() {
		return this.Acronym;
	}

	public void setAcronym(String Acronym) {
		this.Acronym = Acronym;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.Description;
	}

	public void setDescription(String Description) {
		this.Description = Description;
	}

	@Column(name = "logo", length = 500)
	public String getLogo() {
		return this.Logo;
	}

	public void setLogo(String Logo) {
		this.Logo = Logo;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}

	@Column(name = "website", length = 500)
	public String getWebsite() {
		return this.Website;
	}

	public void setWebsite(String Website) {
		this.Website = Website;
	}

	@Column(name = "access", nullable = false)
	public int getAccess() {
		return this.Access;
	}

	public void setAccess(int Access) {
		this.Access = Access;
	}

	@Column(name = "asset_id", nullable = false)
	public int getAsset_id() {
		return this.Asset_id;
	}

	public void setAsset_id(int Asset_id) {
		this.Asset_id = Asset_id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiOrganism")
	public Set<SdiPolicyOrganism> getSdiPolicyOrganisms() {
		return this.sdiPolicyOrganisms;
	}

	public void setSdiPolicyOrganisms(Set<SdiPolicyOrganism> sdiPolicyOrganisms) {
		this.sdiPolicyOrganisms = sdiPolicyOrganisms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiOrganism")
	public Set<SdiVirtualserviceOrganism> getSdiVirtualserviceOrganisms() {
		return this.sdiVirtualserviceOrganisms;
	}

	public void setSdiVirtualserviceOrganisms(
			Set<SdiVirtualserviceOrganism> sdiVirtualserviceOrganisms) {
		this.sdiVirtualserviceOrganisms = sdiVirtualserviceOrganisms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiOrganism")
	public Set<SdiUserRoleOrganism> getSdiUserRoleOrganisms() {
		return this.sdiUserRoleOrganisms;
	}

	public void setSdiUserRoleOrganisms(
			Set<SdiUserRoleOrganism> sdiUserRoleOrganisms) {
		this.sdiUserRoleOrganisms = sdiUserRoleOrganisms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiOrganism")
	public Set<SdiPhysicalserviceOrganism> getSdiPhysicalserviceOrganisms() {
		return this.sdiPhysicalserviceOrganisms;
	}

	public void setSdiPhysicalserviceOrganisms(
			Set<SdiPhysicalserviceOrganism> sdiPhysicalserviceOrganisms) {
		this.sdiPhysicalserviceOrganisms = sdiPhysicalserviceOrganisms;
	}

}
