package org.easysdi.proxy.domain;

// Generated Mar 28, 2013 6:08:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * SdiPhysicalservicePolicy generated by hbm2java
 */
@Entity
public class SdiPhysicalservicePolicy implements java.io.Serializable {

	private Integer Id;
	private SdiWmsSpatialpolicy sdiWmsSpatialpolicy;
	private SdiPhysicalservice sdiPhysicalservice;
	private SdiPolicy sdiPolicy;
	private SdiWmtsSpatialpolicy sdiWmtsSpatialpolicy;
	private SdiCswSpatialpolicy sdiCswSpatialpolicy;
	private SdiWfsSpatialpolicy sdiWfsSpatialpolicy;
	private String Prefix;
	private String Namespace;
	private boolean Anyitem;
	private boolean Inheritedspatialpolicy;
	private Set<SdiWmslayerPolicy> sdiWmslayerPolicies = new HashSet<SdiWmslayerPolicy>(
			0);
	private Set<SdiFeaturetypePolicy> sdiFeaturetypePolicies = new HashSet<SdiFeaturetypePolicy>(
			0);
	private Set<SdiWmtslayerPolicy> sdiWmtslayerPolicies = new HashSet<SdiWmtslayerPolicy>(
			0);

	public SdiPhysicalservicePolicy() {
	}

	public SdiPhysicalservicePolicy(SdiPhysicalservice sdiPhysicalservice,
			SdiPolicy sdiPolicy, boolean Anyitem, boolean Inheritedspatialpolicy) {
		this.sdiPhysicalservice = sdiPhysicalservice;
		this.sdiPolicy = sdiPolicy;
		this.Anyitem = Anyitem;
		this.Inheritedspatialpolicy = Inheritedspatialpolicy;
	}

	public SdiPhysicalservicePolicy(SdiWmsSpatialpolicy sdiWmsSpatialpolicy,
			SdiPhysicalservice sdiPhysicalservice, SdiPolicy sdiPolicy,
			SdiWmtsSpatialpolicy sdiWmtsSpatialpolicy,
			SdiCswSpatialpolicy sdiCswSpatialpolicy,
			SdiWfsSpatialpolicy sdiWfsSpatialpolicy, String Prefix,
			String Namespace, boolean Anyitem, boolean Inheritedspatialpolicy,
			Set<SdiWmslayerPolicy> sdiWmslayerPolicies,
			Set<SdiFeaturetypePolicy> sdiFeaturetypePolicies,
			Set<SdiWmtslayerPolicy> sdiWmtslayerPolicies) {
		this.sdiWmsSpatialpolicy = sdiWmsSpatialpolicy;
		this.sdiPhysicalservice = sdiPhysicalservice;
		this.sdiPolicy = sdiPolicy;
		this.sdiWmtsSpatialpolicy = sdiWmtsSpatialpolicy;
		this.sdiCswSpatialpolicy = sdiCswSpatialpolicy;
		this.sdiWfsSpatialpolicy = sdiWfsSpatialpolicy;
		this.Prefix = Prefix;
		this.Namespace = Namespace;
		this.Anyitem = Anyitem;
		this.Inheritedspatialpolicy = Inheritedspatialpolicy;
		this.sdiWmslayerPolicies = sdiWmslayerPolicies;
		this.sdiFeaturetypePolicies = sdiFeaturetypePolicies;
		this.sdiWmtslayerPolicies = sdiWmtslayerPolicies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "wms_spatialpolicy_id")
	public SdiWmsSpatialpolicy getSdiWmsSpatialpolicy() {
		return this.sdiWmsSpatialpolicy;
	}

	public void setSdiWmsSpatialpolicy(SdiWmsSpatialpolicy sdiWmsSpatialpolicy) {
		this.sdiWmsSpatialpolicy = sdiWmsSpatialpolicy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "physicalservice_id", nullable = false)
	public SdiPhysicalservice getSdiPhysicalservice() {
		return this.sdiPhysicalservice;
	}

	public void setSdiPhysicalservice(SdiPhysicalservice sdiPhysicalservice) {
		this.sdiPhysicalservice = sdiPhysicalservice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "policy_id", nullable = false)
	public SdiPolicy getSdiPolicy() {
		return this.sdiPolicy;
	}

	public void setSdiPolicy(SdiPolicy sdiPolicy) {
		this.sdiPolicy = sdiPolicy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "wmts_spatialpolicy_id")
	public SdiWmtsSpatialpolicy getSdiWmtsSpatialpolicy() {
		return this.sdiWmtsSpatialpolicy;
	}

	public void setSdiWmtsSpatialpolicy(
			SdiWmtsSpatialpolicy sdiWmtsSpatialpolicy) {
		this.sdiWmtsSpatialpolicy = sdiWmtsSpatialpolicy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "csw_spatialpolicy_id")
	public SdiCswSpatialpolicy getSdiCswSpatialpolicy() {
		return this.sdiCswSpatialpolicy;
	}

	public void setSdiCswSpatialpolicy(SdiCswSpatialpolicy sdiCswSpatialpolicy) {
		this.sdiCswSpatialpolicy = sdiCswSpatialpolicy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "wfs_spatialpolicy_id")
	public SdiWfsSpatialpolicy getSdiWfsSpatialpolicy() {
		return this.sdiWfsSpatialpolicy;
	}

	public void setSdiWfsSpatialpolicy(SdiWfsSpatialpolicy sdiWfsSpatialpolicy) {
		this.sdiWfsSpatialpolicy = sdiWfsSpatialpolicy;
	}

	@Column(name = "prefix")
	public String getPrefix() {
		return this.Prefix;
	}

	public void setPrefix(String Prefix) {
		this.Prefix = Prefix;
	}

	@Column(name = "namespace")
	public String getNamespace() {
		return this.Namespace;
	}

	public void setNamespace(String Namespace) {
		this.Namespace = Namespace;
	}

	@Column(name = "anyitem", nullable = false)
	public boolean isAnyitem() {
		return this.Anyitem;
	}

	public void setAnyitem(boolean Anyitem) {
		this.Anyitem = Anyitem;
	}

	@Column(name = "inheritedspatialpolicy", nullable = false)
	public boolean isInheritedspatialpolicy() {
		return this.Inheritedspatialpolicy;
	}

	public void setInheritedspatialpolicy(boolean Inheritedspatialpolicy) {
		this.Inheritedspatialpolicy = Inheritedspatialpolicy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiPhysicalservicePolicy")
	public Set<SdiWmslayerPolicy> getSdiWmslayerPolicies() {
		return this.sdiWmslayerPolicies;
	}

	public void setSdiWmslayerPolicies(
			Set<SdiWmslayerPolicy> sdiWmslayerPolicies) {
		this.sdiWmslayerPolicies = sdiWmslayerPolicies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiPhysicalservicePolicy")
	public Set<SdiFeaturetypePolicy> getSdiFeaturetypePolicies() {
		return this.sdiFeaturetypePolicies;
	}

	public void setSdiFeaturetypePolicies(
			Set<SdiFeaturetypePolicy> sdiFeaturetypePolicies) {
		this.sdiFeaturetypePolicies = sdiFeaturetypePolicies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiPhysicalservicePolicy")
	public Set<SdiWmtslayerPolicy> getSdiWmtslayerPolicies() {
		return this.sdiWmtslayerPolicies;
	}

	public void setSdiWmtslayerPolicies(
			Set<SdiWmtslayerPolicy> sdiWmtslayerPolicies) {
		this.sdiWmtslayerPolicies = sdiWmtslayerPolicies;
	}

}
