package org.easysdi.proxy.domain;

// Generated Mar 28, 2013 4:35:10 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;

/**
 * SdiPhysicalserviceServicecompliance generated by hbm2java
 */
@Entity
public class SdiPhysicalserviceServicecompliance implements
		java.io.Serializable {

	private Integer Id;
	private int Service_id;
	private int Servicecompliance_id;
	private String Capabilities;

	public SdiPhysicalserviceServicecompliance() {
	}

	public SdiPhysicalserviceServicecompliance(int Service_id,
			int Servicecompliance_id) {
		this.Service_id = Service_id;
		this.Servicecompliance_id = Servicecompliance_id;
	}

	public SdiPhysicalserviceServicecompliance(int Service_id,
			int Servicecompliance_id, String Capabilities) {
		this.Service_id = Service_id;
		this.Servicecompliance_id = Servicecompliance_id;
		this.Capabilities = Capabilities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "service_id", nullable = false)
	public int getService_id() {
		return this.Service_id;
	}

	public void setService_id(int Service_id) {
		this.Service_id = Service_id;
	}

	@Column(name = "servicecompliance_id", nullable = false)
	public int getServicecompliance_id() {
		return this.Servicecompliance_id;
	}

	public void setServicecompliance_id(int Servicecompliance_id) {
		this.Servicecompliance_id = Servicecompliance_id;
	}

	@Column(name = "capabilities", length = 65535)
	public String getCapabilities() {
		return this.Capabilities;
	}

	public void setCapabilities(String Capabilities) {
		this.Capabilities = Capabilities;
	}

}
