package org.easysdi.proxy.domain;

// Generated Mar 28, 2013 4:35:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SdiPhysicalservice generated by hbm2java
 */
@Entity
public class SdiPhysicalservice implements java.io.Serializable {

	private Integer Id;
	private String Guid;
	private String Alias;
	private int Created_by;
	private Date Created;
	private Integer Modified_by;
	private Date Modified;
	private Integer Ordering;
	private int State;
	private int Checked_out;
	private Date Checked_out_time;
	private String Name;
	private int Servicescope_id;
	private int Serviceconnector_id;
	private Integer Resourceauthentication_id;
	private String Resourceurl;
	private String Resourceusername;
	private String Resourcepassword;
	private Integer Serviceauthentication_id;
	private String Serviceurl;
	private String Serviceusername;
	private String Servicepassword;
	private int Catid;
	private String Params;
	private int Access;
	private Integer Asset_id;

	public SdiPhysicalservice() {
	}

	public SdiPhysicalservice(String Guid, String Alias, int Created_by,
			Date Created, int State, int Checked_out, Date Checked_out_time,
			int Servicescope_id, int Serviceconnector_id, int Catid, int Access) {
		this.Guid = Guid;
		this.Alias = Alias;
		this.Created_by = Created_by;
		this.Created = Created;
		this.State = State;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Servicescope_id = Servicescope_id;
		this.Serviceconnector_id = Serviceconnector_id;
		this.Catid = Catid;
		this.Access = Access;
	}

	public SdiPhysicalservice(String Guid, String Alias, int Created_by,
			Date Created, Integer Modified_by, Date Modified, Integer Ordering,
			int State, int Checked_out, Date Checked_out_time, String Name,
			int Servicescope_id, int Serviceconnector_id,
			Integer Resourceauthentication_id, String Resourceurl,
			String Resourceusername, String Resourcepassword,
			Integer Serviceauthentication_id, String Serviceurl,
			String Serviceusername, String Servicepassword, int Catid,
			String Params, int Access, Integer Asset_id) {
		this.Guid = Guid;
		this.Alias = Alias;
		this.Created_by = Created_by;
		this.Created = Created;
		this.Modified_by = Modified_by;
		this.Modified = Modified;
		this.Ordering = Ordering;
		this.State = State;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Name = Name;
		this.Servicescope_id = Servicescope_id;
		this.Serviceconnector_id = Serviceconnector_id;
		this.Resourceauthentication_id = Resourceauthentication_id;
		this.Resourceurl = Resourceurl;
		this.Resourceusername = Resourceusername;
		this.Resourcepassword = Resourcepassword;
		this.Serviceauthentication_id = Serviceauthentication_id;
		this.Serviceurl = Serviceurl;
		this.Serviceusername = Serviceusername;
		this.Servicepassword = Servicepassword;
		this.Catid = Catid;
		this.Params = Params;
		this.Access = Access;
		this.Asset_id = Asset_id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "guid", nullable = false, length = 36)
	public String getGuid() {
		return this.Guid;
	}

	public void setGuid(String Guid) {
		this.Guid = Guid;
	}

	@Column(name = "alias", nullable = false, length = 20)
	public String getAlias() {
		return this.Alias;
	}

	public void setAlias(String Alias) {
		this.Alias = Alias;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreated_by() {
		return this.Created_by;
	}

	public void setCreated_by(int Created_by) {
		this.Created_by = Created_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.Created;
	}

	public void setCreated(Date Created) {
		this.Created = Created;
	}

	@Column(name = "modified_by")
	public Integer getModified_by() {
		return this.Modified_by;
	}

	public void setModified_by(Integer Modified_by) {
		this.Modified_by = Modified_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 19)
	public Date getModified() {
		return this.Modified;
	}

	public void setModified(Date Modified) {
		this.Modified = Modified;
	}

	@Column(name = "ordering")
	public Integer getOrdering() {
		return this.Ordering;
	}

	public void setOrdering(Integer Ordering) {
		this.Ordering = Ordering;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.State;
	}

	public void setState(int State) {
		this.State = State;
	}

	@Column(name = "checked_out", nullable = false)
	public int getChecked_out() {
		return this.Checked_out;
	}

	public void setChecked_out(int Checked_out) {
		this.Checked_out = Checked_out;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checked_out_time", nullable = false, length = 19)
	public Date getChecked_out_time() {
		return this.Checked_out_time;
	}

	public void setChecked_out_time(Date Checked_out_time) {
		this.Checked_out_time = Checked_out_time;
	}

	@Column(name = "name", unique = true)
	public String getName() {
		return this.Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}

	@Column(name = "servicescope_id", nullable = false)
	public int getServicescope_id() {
		return this.Servicescope_id;
	}

	public void setServicescope_id(int Servicescope_id) {
		this.Servicescope_id = Servicescope_id;
	}

	@Column(name = "serviceconnector_id", nullable = false)
	public int getServiceconnector_id() {
		return this.Serviceconnector_id;
	}

	public void setServiceconnector_id(int Serviceconnector_id) {
		this.Serviceconnector_id = Serviceconnector_id;
	}

	@Column(name = "resourceauthentication_id")
	public Integer getResourceauthentication_id() {
		return this.Resourceauthentication_id;
	}

	public void setResourceauthentication_id(Integer Resourceauthentication_id) {
		this.Resourceauthentication_id = Resourceauthentication_id;
	}

	@Column(name = "resourceurl", length = 500)
	public String getResourceurl() {
		return this.Resourceurl;
	}

	public void setResourceurl(String Resourceurl) {
		this.Resourceurl = Resourceurl;
	}

	@Column(name = "resourceusername", length = 150)
	public String getResourceusername() {
		return this.Resourceusername;
	}

	public void setResourceusername(String Resourceusername) {
		this.Resourceusername = Resourceusername;
	}

	@Column(name = "resourcepassword", length = 150)
	public String getResourcepassword() {
		return this.Resourcepassword;
	}

	public void setResourcepassword(String Resourcepassword) {
		this.Resourcepassword = Resourcepassword;
	}

	@Column(name = "serviceauthentication_id")
	public Integer getServiceauthentication_id() {
		return this.Serviceauthentication_id;
	}

	public void setServiceauthentication_id(Integer Serviceauthentication_id) {
		this.Serviceauthentication_id = Serviceauthentication_id;
	}

	@Column(name = "serviceurl", length = 500)
	public String getServiceurl() {
		return this.Serviceurl;
	}

	public void setServiceurl(String Serviceurl) {
		this.Serviceurl = Serviceurl;
	}

	@Column(name = "serviceusername", length = 150)
	public String getServiceusername() {
		return this.Serviceusername;
	}

	public void setServiceusername(String Serviceusername) {
		this.Serviceusername = Serviceusername;
	}

	@Column(name = "servicepassword", length = 150)
	public String getServicepassword() {
		return this.Servicepassword;
	}

	public void setServicepassword(String Servicepassword) {
		this.Servicepassword = Servicepassword;
	}

	@Column(name = "catid", nullable = false)
	public int getCatid() {
		return this.Catid;
	}

	public void setCatid(int Catid) {
		this.Catid = Catid;
	}

	@Column(name = "params", length = 1024)
	public String getParams() {
		return this.Params;
	}

	public void setParams(String Params) {
		this.Params = Params;
	}

	@Column(name = "access", nullable = false)
	public int getAccess() {
		return this.Access;
	}

	public void setAccess(int Access) {
		this.Access = Access;
	}

	@Column(name = "asset_id")
	public Integer getAsset_id() {
		return this.Asset_id;
	}

	public void setAsset_id(Integer Asset_id) {
		this.Asset_id = Asset_id;
	}

}
