package org.easysdi.proxy.domain;

// Generated Mar 28, 2013 4:35:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SdiPolicy generated by hbm2java
 */
@Entity
public class SdiPolicy implements java.io.Serializable {

	private Integer Id;
	private String Guid;
	private int Ordering;
	private int State;
	private int Checked_out;
	private Date Checked_out_time;
	private int Created_by;
	private Date Created;
	private Integer Modified_by;
	private Date Modified;
	private String Name;
	private String Alias;
	private Date Allowfrom;
	private Date Allowto;
	private boolean Anyoperation;
	private boolean Anyservice;
	private int Accessscope_id;
	private int Virtualservice_id;
	private Integer Csw_spatialpolicy_id;
	private Integer Wms_spatialpolicy_id;
	private Integer Wmts_spatialpolicy_id;
	private Integer Wfs_spatialpolicy_id;
	private int Csw_version_id;
	private boolean Csw_anyattribute;
	private boolean Csw_anycontext;
	private boolean Csw_anystate;
	private boolean Csw_anyvisibility;
	private Integer Wms_minimumwidth;
	private Integer Wms_minimumheight;
	private Integer Wms_maximumwidth;
	private Integer Wms_maximumheight;
	private String Params;
	private int Access;
	private Integer Asset_id;

	public SdiPolicy() {
	}

	public SdiPolicy(String Guid, int Ordering, int State, int Checked_out,
			Date Checked_out_time, int Created_by, Date Created, String Name,
			String Alias, Date Allowfrom, Date Allowto, boolean Anyoperation,
			boolean Anyservice, int Accessscope_id, int Virtualservice_id,
			int Csw_version_id, boolean Csw_anyattribute,
			boolean Csw_anycontext, boolean Csw_anystate,
			boolean Csw_anyvisibility, int Access) {
		this.Guid = Guid;
		this.Ordering = Ordering;
		this.State = State;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Created_by = Created_by;
		this.Created = Created;
		this.Name = Name;
		this.Alias = Alias;
		this.Allowfrom = Allowfrom;
		this.Allowto = Allowto;
		this.Anyoperation = Anyoperation;
		this.Anyservice = Anyservice;
		this.Accessscope_id = Accessscope_id;
		this.Virtualservice_id = Virtualservice_id;
		this.Csw_version_id = Csw_version_id;
		this.Csw_anyattribute = Csw_anyattribute;
		this.Csw_anycontext = Csw_anycontext;
		this.Csw_anystate = Csw_anystate;
		this.Csw_anyvisibility = Csw_anyvisibility;
		this.Access = Access;
	}

	public SdiPolicy(String Guid, int Ordering, int State, int Checked_out,
			Date Checked_out_time, int Created_by, Date Created,
			Integer Modified_by, Date Modified, String Name, String Alias,
			Date Allowfrom, Date Allowto, boolean Anyoperation,
			boolean Anyservice, int Accessscope_id, int Virtualservice_id,
			Integer Csw_spatialpolicy_id, Integer Wms_spatialpolicy_id,
			Integer Wmts_spatialpolicy_id, Integer Wfs_spatialpolicy_id,
			int Csw_version_id, boolean Csw_anyattribute,
			boolean Csw_anycontext, boolean Csw_anystate,
			boolean Csw_anyvisibility, Integer Wms_minimumwidth,
			Integer Wms_minimumheight, Integer Wms_maximumwidth,
			Integer Wms_maximumheight, String Params, int Access,
			Integer Asset_id) {
		this.Guid = Guid;
		this.Ordering = Ordering;
		this.State = State;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Created_by = Created_by;
		this.Created = Created;
		this.Modified_by = Modified_by;
		this.Modified = Modified;
		this.Name = Name;
		this.Alias = Alias;
		this.Allowfrom = Allowfrom;
		this.Allowto = Allowto;
		this.Anyoperation = Anyoperation;
		this.Anyservice = Anyservice;
		this.Accessscope_id = Accessscope_id;
		this.Virtualservice_id = Virtualservice_id;
		this.Csw_spatialpolicy_id = Csw_spatialpolicy_id;
		this.Wms_spatialpolicy_id = Wms_spatialpolicy_id;
		this.Wmts_spatialpolicy_id = Wmts_spatialpolicy_id;
		this.Wfs_spatialpolicy_id = Wfs_spatialpolicy_id;
		this.Csw_version_id = Csw_version_id;
		this.Csw_anyattribute = Csw_anyattribute;
		this.Csw_anycontext = Csw_anycontext;
		this.Csw_anystate = Csw_anystate;
		this.Csw_anyvisibility = Csw_anyvisibility;
		this.Wms_minimumwidth = Wms_minimumwidth;
		this.Wms_minimumheight = Wms_minimumheight;
		this.Wms_maximumwidth = Wms_maximumwidth;
		this.Wms_maximumheight = Wms_maximumheight;
		this.Params = Params;
		this.Access = Access;
		this.Asset_id = Asset_id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "guid", nullable = false, length = 36)
	public String getGuid() {
		return this.Guid;
	}

	public void setGuid(String Guid) {
		this.Guid = Guid;
	}

	@Column(name = "ordering", nullable = false)
	public int getOrdering() {
		return this.Ordering;
	}

	public void setOrdering(int Ordering) {
		this.Ordering = Ordering;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.State;
	}

	public void setState(int State) {
		this.State = State;
	}

	@Column(name = "checked_out", nullable = false)
	public int getChecked_out() {
		return this.Checked_out;
	}

	public void setChecked_out(int Checked_out) {
		this.Checked_out = Checked_out;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checked_out_time", nullable = false, length = 19)
	public Date getChecked_out_time() {
		return this.Checked_out_time;
	}

	public void setChecked_out_time(Date Checked_out_time) {
		this.Checked_out_time = Checked_out_time;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreated_by() {
		return this.Created_by;
	}

	public void setCreated_by(int Created_by) {
		this.Created_by = Created_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.Created;
	}

	public void setCreated(Date Created) {
		this.Created = Created;
	}

	@Column(name = "modified_by")
	public Integer getModified_by() {
		return this.Modified_by;
	}

	public void setModified_by(Integer Modified_by) {
		this.Modified_by = Modified_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 19)
	public Date getModified() {
		return this.Modified;
	}

	public void setModified(Date Modified) {
		this.Modified = Modified;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}

	@Column(name = "alias", nullable = false, length = 20)
	public String getAlias() {
		return this.Alias;
	}

	public void setAlias(String Alias) {
		this.Alias = Alias;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "allowfrom", nullable = false, length = 10)
	public Date getAllowfrom() {
		return this.Allowfrom;
	}

	public void setAllowfrom(Date Allowfrom) {
		this.Allowfrom = Allowfrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "allowto", nullable = false, length = 10)
	public Date getAllowto() {
		return this.Allowto;
	}

	public void setAllowto(Date Allowto) {
		this.Allowto = Allowto;
	}

	@Column(name = "anyoperation", nullable = false)
	public boolean isAnyoperation() {
		return this.Anyoperation;
	}

	public void setAnyoperation(boolean Anyoperation) {
		this.Anyoperation = Anyoperation;
	}

	@Column(name = "anyservice", nullable = false)
	public boolean isAnyservice() {
		return this.Anyservice;
	}

	public void setAnyservice(boolean Anyservice) {
		this.Anyservice = Anyservice;
	}

	@Column(name = "accessscope_id", nullable = false)
	public int getAccessscope_id() {
		return this.Accessscope_id;
	}

	public void setAccessscope_id(int Accessscope_id) {
		this.Accessscope_id = Accessscope_id;
	}

	@Column(name = "virtualservice_id", nullable = false)
	public int getVirtualservice_id() {
		return this.Virtualservice_id;
	}

	public void setVirtualservice_id(int Virtualservice_id) {
		this.Virtualservice_id = Virtualservice_id;
	}

	@Column(name = "csw_spatialpolicy_id")
	public Integer getCsw_spatialpolicy_id() {
		return this.Csw_spatialpolicy_id;
	}

	public void setCsw_spatialpolicy_id(Integer Csw_spatialpolicy_id) {
		this.Csw_spatialpolicy_id = Csw_spatialpolicy_id;
	}

	@Column(name = "wms_spatialpolicy_id")
	public Integer getWms_spatialpolicy_id() {
		return this.Wms_spatialpolicy_id;
	}

	public void setWms_spatialpolicy_id(Integer Wms_spatialpolicy_id) {
		this.Wms_spatialpolicy_id = Wms_spatialpolicy_id;
	}

	@Column(name = "wmts_spatialpolicy_id")
	public Integer getWmts_spatialpolicy_id() {
		return this.Wmts_spatialpolicy_id;
	}

	public void setWmts_spatialpolicy_id(Integer Wmts_spatialpolicy_id) {
		this.Wmts_spatialpolicy_id = Wmts_spatialpolicy_id;
	}

	@Column(name = "wfs_spatialpolicy_id")
	public Integer getWfs_spatialpolicy_id() {
		return this.Wfs_spatialpolicy_id;
	}

	public void setWfs_spatialpolicy_id(Integer Wfs_spatialpolicy_id) {
		this.Wfs_spatialpolicy_id = Wfs_spatialpolicy_id;
	}

	@Column(name = "csw_version_id", nullable = false)
	public int getCsw_version_id() {
		return this.Csw_version_id;
	}

	public void setCsw_version_id(int Csw_version_id) {
		this.Csw_version_id = Csw_version_id;
	}

	@Column(name = "csw_anyattribute", nullable = false)
	public boolean isCsw_anyattribute() {
		return this.Csw_anyattribute;
	}

	public void setCsw_anyattribute(boolean Csw_anyattribute) {
		this.Csw_anyattribute = Csw_anyattribute;
	}

	@Column(name = "csw_anycontext", nullable = false)
	public boolean isCsw_anycontext() {
		return this.Csw_anycontext;
	}

	public void setCsw_anycontext(boolean Csw_anycontext) {
		this.Csw_anycontext = Csw_anycontext;
	}

	@Column(name = "csw_anystate", nullable = false)
	public boolean isCsw_anystate() {
		return this.Csw_anystate;
	}

	public void setCsw_anystate(boolean Csw_anystate) {
		this.Csw_anystate = Csw_anystate;
	}

	@Column(name = "csw_anyvisibility", nullable = false)
	public boolean isCsw_anyvisibility() {
		return this.Csw_anyvisibility;
	}

	public void setCsw_anyvisibility(boolean Csw_anyvisibility) {
		this.Csw_anyvisibility = Csw_anyvisibility;
	}

	@Column(name = "wms_minimumwidth")
	public Integer getWms_minimumwidth() {
		return this.Wms_minimumwidth;
	}

	public void setWms_minimumwidth(Integer Wms_minimumwidth) {
		this.Wms_minimumwidth = Wms_minimumwidth;
	}

	@Column(name = "wms_minimumheight")
	public Integer getWms_minimumheight() {
		return this.Wms_minimumheight;
	}

	public void setWms_minimumheight(Integer Wms_minimumheight) {
		this.Wms_minimumheight = Wms_minimumheight;
	}

	@Column(name = "wms_maximumwidth")
	public Integer getWms_maximumwidth() {
		return this.Wms_maximumwidth;
	}

	public void setWms_maximumwidth(Integer Wms_maximumwidth) {
		this.Wms_maximumwidth = Wms_maximumwidth;
	}

	@Column(name = "wms_maximumheight")
	public Integer getWms_maximumheight() {
		return this.Wms_maximumheight;
	}

	public void setWms_maximumheight(Integer Wms_maximumheight) {
		this.Wms_maximumheight = Wms_maximumheight;
	}

	@Column(name = "params", length = 1024)
	public String getParams() {
		return this.Params;
	}

	public void setParams(String Params) {
		this.Params = Params;
	}

	@Column(name = "access", nullable = false)
	public int getAccess() {
		return this.Access;
	}

	public void setAccess(int Access) {
		this.Access = Access;
	}

	@Column(name = "asset_id")
	public Integer getAsset_id() {
		return this.Asset_id;
	}

	public void setAsset_id(Integer Asset_id) {
		this.Asset_id = Asset_id;
	}

}
