package org.easysdi.proxy.domain;

// Generated Apr 9, 2013 11:54:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SdiSysServicecompliance generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
public class SdiSysServicecompliance implements java.io.Serializable {

	private Integer Id;
	private SdiSysServiceversion sdiSysServiceversion;
	private SdiSysServiceconnector sdiSysServiceconnector;
	private Integer Ordering;
	private int State;
	private boolean Implemented;
	private boolean Relayable;
	private boolean Aggregatable;
	private boolean Harvestable;
	private Set<SdiPhysicalserviceServicecompliance> sdiPhysicalserviceServicecompliances = new HashSet<SdiPhysicalserviceServicecompliance>(
			0);
	private Set<SdiVirtualserviceServicecompliance> sdiVirtualserviceServicecompliances = new HashSet<SdiVirtualserviceServicecompliance>(
			0);
	private Set<SdiSysOperationcompliance> sdiSysOperationcompliances = new HashSet<SdiSysOperationcompliance>(
			0);

	public SdiSysServicecompliance() {
	}

	public SdiSysServicecompliance(SdiSysServiceversion sdiSysServiceversion,
			SdiSysServiceconnector sdiSysServiceconnector, int State,
			boolean Implemented, boolean Relayable, boolean Aggregatable,
			boolean Harvestable) {
		this.sdiSysServiceversion = sdiSysServiceversion;
		this.sdiSysServiceconnector = sdiSysServiceconnector;
		this.State = State;
		this.Implemented = Implemented;
		this.Relayable = Relayable;
		this.Aggregatable = Aggregatable;
		this.Harvestable = Harvestable;
	}

	public SdiSysServicecompliance(
			SdiSysServiceversion sdiSysServiceversion,
			SdiSysServiceconnector sdiSysServiceconnector,
			Integer Ordering,
			int State,
			boolean Implemented,
			boolean Relayable,
			boolean Aggregatable,
			boolean Harvestable,
			Set<SdiPhysicalserviceServicecompliance> sdiPhysicalserviceServicecompliances,
			Set<SdiVirtualserviceServicecompliance> sdiVirtualserviceServicecompliances,
			Set<SdiSysOperationcompliance> sdiSysOperationcompliances) {
		this.sdiSysServiceversion = sdiSysServiceversion;
		this.sdiSysServiceconnector = sdiSysServiceconnector;
		this.Ordering = Ordering;
		this.State = State;
		this.Implemented = Implemented;
		this.Relayable = Relayable;
		this.Aggregatable = Aggregatable;
		this.Harvestable = Harvestable;
		this.sdiPhysicalserviceServicecompliances = sdiPhysicalserviceServicecompliances;
		this.sdiVirtualserviceServicecompliances = sdiVirtualserviceServicecompliances;
		this.sdiSysOperationcompliances = sdiSysOperationcompliances;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceversion_id", nullable = false)
	public SdiSysServiceversion getSdiSysServiceversion() {
		return this.sdiSysServiceversion;
	}

	public void setSdiSysServiceversion(
			SdiSysServiceversion sdiSysServiceversion) {
		this.sdiSysServiceversion = sdiSysServiceversion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceconnector_id", nullable = false)
	public SdiSysServiceconnector getSdiSysServiceconnector() {
		return this.sdiSysServiceconnector;
	}

	public void setSdiSysServiceconnector(
			SdiSysServiceconnector sdiSysServiceconnector) {
		this.sdiSysServiceconnector = sdiSysServiceconnector;
	}

	@Column(name = "ordering")
	public Integer getOrdering() {
		return this.Ordering;
	}

	public void setOrdering(Integer Ordering) {
		this.Ordering = Ordering;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.State;
	}

	public void setState(int State) {
		this.State = State;
	}

	@Column(name = "implemented", nullable = false)
	public boolean isImplemented() {
		return this.Implemented;
	}

	public void setImplemented(boolean Implemented) {
		this.Implemented = Implemented;
	}

	@Column(name = "relayable", nullable = false)
	public boolean isRelayable() {
		return this.Relayable;
	}

	public void setRelayable(boolean Relayable) {
		this.Relayable = Relayable;
	}

	@Column(name = "aggregatable", nullable = false)
	public boolean isAggregatable() {
		return this.Aggregatable;
	}

	public void setAggregatable(boolean Aggregatable) {
		this.Aggregatable = Aggregatable;
	}

	@Column(name = "harvestable", nullable = false)
	public boolean isHarvestable() {
		return this.Harvestable;
	}

	public void setHarvestable(boolean Harvestable) {
		this.Harvestable = Harvestable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiSysServicecompliance")
	public Set<SdiPhysicalserviceServicecompliance> getSdiPhysicalserviceServicecompliances() {
		return this.sdiPhysicalserviceServicecompliances;
	}

	public void setSdiPhysicalserviceServicecompliances(
			Set<SdiPhysicalserviceServicecompliance> sdiPhysicalserviceServicecompliances) {
		this.sdiPhysicalserviceServicecompliances = sdiPhysicalserviceServicecompliances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiSysServicecompliance")
	public Set<SdiVirtualserviceServicecompliance> getSdiVirtualserviceServicecompliances() {
		return this.sdiVirtualserviceServicecompliances;
	}

	public void setSdiVirtualserviceServicecompliances(
			Set<SdiVirtualserviceServicecompliance> sdiVirtualserviceServicecompliances) {
		this.sdiVirtualserviceServicecompliances = sdiVirtualserviceServicecompliances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiSysServicecompliance")
	public Set<SdiSysOperationcompliance> getSdiSysOperationcompliances() {
		return this.sdiSysOperationcompliances;
	}

	public void setSdiSysOperationcompliances(
			Set<SdiSysOperationcompliance> sdiSysOperationcompliances) {
		this.sdiSysOperationcompliances = sdiSysOperationcompliances;
	}

}
