package org.easysdi.proxy.domain;

// Generated Apr 4, 2013 10:31:47 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;

/**
 * SdiSysMaptool generated by hbm2java
 */
@Entity
public class SdiSysMaptool implements java.io.Serializable {

	private Integer Id;
	private String Alias;
	private Integer Ordering;
	private int State;
	private String Name;

	public SdiSysMaptool() {
	}

	public SdiSysMaptool(String Alias, int State, String Name) {
		this.Alias = Alias;
		this.State = State;
		this.Name = Name;
	}

	public SdiSysMaptool(String Alias, Integer Ordering, int State, String Name) {
		this.Alias = Alias;
		this.Ordering = Ordering;
		this.State = State;
		this.Name = Name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "alias", nullable = false, length = 20)
	public String getAlias() {
		return this.Alias;
	}

	public void setAlias(String Alias) {
		this.Alias = Alias;
	}

	@Column(name = "ordering")
	public Integer getOrdering() {
		return this.Ordering;
	}

	public void setOrdering(Integer Ordering) {
		this.Ordering = Ordering;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.State;
	}

	public void setState(int State) {
		this.State = State;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}

}
