package org.easysdi.proxy.domain;

// Generated Mar 29, 2013 9:59:28 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * SdiSysOperationcompliance generated by hbm2java
 */
@Entity
public class SdiSysOperationcompliance implements java.io.Serializable {

	private Integer Id;
	private SdiSysServiceoperation sdiSysServiceoperation;
	private SdiSysServicecompliance sdiSysServicecompliance;
	private Integer Ordering;
	private int State;
	private boolean Implemented;

	public SdiSysOperationcompliance() {
	}

	public SdiSysOperationcompliance(
			SdiSysServiceoperation sdiSysServiceoperation,
			SdiSysServicecompliance sdiSysServicecompliance, int State,
			boolean Implemented) {
		this.sdiSysServiceoperation = sdiSysServiceoperation;
		this.sdiSysServicecompliance = sdiSysServicecompliance;
		this.State = State;
		this.Implemented = Implemented;
	}

	public SdiSysOperationcompliance(
			SdiSysServiceoperation sdiSysServiceoperation,
			SdiSysServicecompliance sdiSysServicecompliance, Integer Ordering,
			int State, boolean Implemented) {
		this.sdiSysServiceoperation = sdiSysServiceoperation;
		this.sdiSysServicecompliance = sdiSysServicecompliance;
		this.Ordering = Ordering;
		this.State = State;
		this.Implemented = Implemented;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceoperation_id", nullable = false)
	public SdiSysServiceoperation getSdiSysServiceoperation() {
		return this.sdiSysServiceoperation;
	}

	public void setSdiSysServiceoperation(
			SdiSysServiceoperation sdiSysServiceoperation) {
		this.sdiSysServiceoperation = sdiSysServiceoperation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "servicecompliance_id", nullable = false)
	public SdiSysServicecompliance getSdiSysServicecompliance() {
		return this.sdiSysServicecompliance;
	}

	public void setSdiSysServicecompliance(
			SdiSysServicecompliance sdiSysServicecompliance) {
		this.sdiSysServicecompliance = sdiSysServicecompliance;
	}

	@Column(name = "ordering")
	public Integer getOrdering() {
		return this.Ordering;
	}

	public void setOrdering(Integer Ordering) {
		this.Ordering = Ordering;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.State;
	}

	public void setState(int State) {
		this.State = State;
	}

	@Column(name = "implemented", nullable = false)
	public boolean isImplemented() {
		return this.Implemented;
	}

	public void setImplemented(boolean Implemented) {
		this.Implemented = Implemented;
	}

}
