package org.easysdi.proxy.domain;

// Generated Apr 9, 2013 11:54:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SdiSysAuthenticationconnector generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
public class SdiSysAuthenticationconnector implements java.io.Serializable {

	private Integer Id;
	private Integer Ordering;
	private int State;
	private int Authenticationlevel_id;
	private String Value;
	private Set<SdiPhysicalservice> sdiPhysicalservicesForServiceauthenticationId = new HashSet<SdiPhysicalservice>(
			0);
	private Set<SdiPhysicalservice> sdiPhysicalservicesForResourceauthenticationId = new HashSet<SdiPhysicalservice>(
			0);
	private Set<SdiSysServiceconAuthenticationcon> sdiSysServiceconAuthenticationcons = new HashSet<SdiSysServiceconAuthenticationcon>(
			0);

	public SdiSysAuthenticationconnector() {
	}

	public SdiSysAuthenticationconnector(int State, int Authenticationlevel_id,
			String Value) {
		this.State = State;
		this.Authenticationlevel_id = Authenticationlevel_id;
		this.Value = Value;
	}

	public SdiSysAuthenticationconnector(
			Integer Ordering,
			int State,
			int Authenticationlevel_id,
			String Value,
			Set<SdiPhysicalservice> sdiPhysicalservicesForServiceauthenticationId,
			Set<SdiPhysicalservice> sdiPhysicalservicesForResourceauthenticationId,
			Set<SdiSysServiceconAuthenticationcon> sdiSysServiceconAuthenticationcons) {
		this.Ordering = Ordering;
		this.State = State;
		this.Authenticationlevel_id = Authenticationlevel_id;
		this.Value = Value;
		this.sdiPhysicalservicesForServiceauthenticationId = sdiPhysicalservicesForServiceauthenticationId;
		this.sdiPhysicalservicesForResourceauthenticationId = sdiPhysicalservicesForResourceauthenticationId;
		this.sdiSysServiceconAuthenticationcons = sdiSysServiceconAuthenticationcons;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "ordering")
	public Integer getOrdering() {
		return this.Ordering;
	}

	public void setOrdering(Integer Ordering) {
		this.Ordering = Ordering;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.State;
	}

	public void setState(int State) {
		this.State = State;
	}

	@Column(name = "authenticationlevel_id", nullable = false)
	public int getAuthenticationlevel_id() {
		return this.Authenticationlevel_id;
	}

	public void setAuthenticationlevel_id(int Authenticationlevel_id) {
		this.Authenticationlevel_id = Authenticationlevel_id;
	}

	@Column(name = "value", nullable = false, length = 150)
	public String getValue() {
		return this.Value;
	}

	public void setValue(String Value) {
		this.Value = Value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiSysAuthenticationconnectorByServiceauthenticationId")
	public Set<SdiPhysicalservice> getSdiPhysicalservicesForServiceauthenticationId() {
		return this.sdiPhysicalservicesForServiceauthenticationId;
	}

	public void setSdiPhysicalservicesForServiceauthenticationId(
			Set<SdiPhysicalservice> sdiPhysicalservicesForServiceauthenticationId) {
		this.sdiPhysicalservicesForServiceauthenticationId = sdiPhysicalservicesForServiceauthenticationId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiSysAuthenticationconnectorByResourceauthenticationId")
	public Set<SdiPhysicalservice> getSdiPhysicalservicesForResourceauthenticationId() {
		return this.sdiPhysicalservicesForResourceauthenticationId;
	}

	public void setSdiPhysicalservicesForResourceauthenticationId(
			Set<SdiPhysicalservice> sdiPhysicalservicesForResourceauthenticationId) {
		this.sdiPhysicalservicesForResourceauthenticationId = sdiPhysicalservicesForResourceauthenticationId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiSysAuthenticationconnector")
	public Set<SdiSysServiceconAuthenticationcon> getSdiSysServiceconAuthenticationcons() {
		return this.sdiSysServiceconAuthenticationcons;
	}

	public void setSdiSysServiceconAuthenticationcons(
			Set<SdiSysServiceconAuthenticationcon> sdiSysServiceconAuthenticationcons) {
		this.sdiSysServiceconAuthenticationcons = sdiSysServiceconAuthenticationcons;
	}

}
