package org.easysdi.proxy.domain;

// Generated Apr 4, 2013 10:31:47 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SdiSysServicecompliance generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
public class SdiSysServicecompliance implements java.io.Serializable {

	private Integer Id;
	private Integer Ordering;
	private int State;
	private int Serviceconnector_id;
	private int Serviceversion_id;
	private boolean Implemented;
	private boolean Relayable;
	private boolean Aggregatable;
	private boolean Harvestable;
	private Set<SdiPhysicalserviceServicecompliance> sdiPhysicalserviceServicecompliances = new HashSet<SdiPhysicalserviceServicecompliance>(
			0);
	private Set<SdiVirtualserviceServicecompliance> sdiVirtualserviceServicecompliances = new HashSet<SdiVirtualserviceServicecompliance>(
			0);
	private Set<SdiSysOperationcompliance> sdiSysOperationcompliances = new HashSet<SdiSysOperationcompliance>(
			0);

	public SdiSysServicecompliance() {
	}

	public SdiSysServicecompliance(int State, int Serviceconnector_id,
			int Serviceversion_id, boolean Implemented, boolean Relayable,
			boolean Aggregatable, boolean Harvestable) {
		this.State = State;
		this.Serviceconnector_id = Serviceconnector_id;
		this.Serviceversion_id = Serviceversion_id;
		this.Implemented = Implemented;
		this.Relayable = Relayable;
		this.Aggregatable = Aggregatable;
		this.Harvestable = Harvestable;
	}

	public SdiSysServicecompliance(
			Integer Ordering,
			int State,
			int Serviceconnector_id,
			int Serviceversion_id,
			boolean Implemented,
			boolean Relayable,
			boolean Aggregatable,
			boolean Harvestable,
			Set<SdiPhysicalserviceServicecompliance> sdiPhysicalserviceServicecompliances,
			Set<SdiVirtualserviceServicecompliance> sdiVirtualserviceServicecompliances,
			Set<SdiSysOperationcompliance> sdiSysOperationcompliances) {
		this.Ordering = Ordering;
		this.State = State;
		this.Serviceconnector_id = Serviceconnector_id;
		this.Serviceversion_id = Serviceversion_id;
		this.Implemented = Implemented;
		this.Relayable = Relayable;
		this.Aggregatable = Aggregatable;
		this.Harvestable = Harvestable;
		this.sdiPhysicalserviceServicecompliances = sdiPhysicalserviceServicecompliances;
		this.sdiVirtualserviceServicecompliances = sdiVirtualserviceServicecompliances;
		this.sdiSysOperationcompliances = sdiSysOperationcompliances;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "ordering")
	public Integer getOrdering() {
		return this.Ordering;
	}

	public void setOrdering(Integer Ordering) {
		this.Ordering = Ordering;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.State;
	}

	public void setState(int State) {
		this.State = State;
	}

	@Column(name = "serviceconnector_id", nullable = false)
	public int getServiceconnector_id() {
		return this.Serviceconnector_id;
	}

	public void setServiceconnector_id(int Serviceconnector_id) {
		this.Serviceconnector_id = Serviceconnector_id;
	}

	@Column(name = "serviceversion_id", nullable = false)
	public int getServiceversion_id() {
		return this.Serviceversion_id;
	}

	public void setServiceversion_id(int Serviceversion_id) {
		this.Serviceversion_id = Serviceversion_id;
	}

	@Column(name = "implemented", nullable = false)
	public boolean isImplemented() {
		return this.Implemented;
	}

	public void setImplemented(boolean Implemented) {
		this.Implemented = Implemented;
	}

	@Column(name = "relayable", nullable = false)
	public boolean isRelayable() {
		return this.Relayable;
	}

	public void setRelayable(boolean Relayable) {
		this.Relayable = Relayable;
	}

	@Column(name = "aggregatable", nullable = false)
	public boolean isAggregatable() {
		return this.Aggregatable;
	}

	public void setAggregatable(boolean Aggregatable) {
		this.Aggregatable = Aggregatable;
	}

	@Column(name = "harvestable", nullable = false)
	public boolean isHarvestable() {
		return this.Harvestable;
	}

	public void setHarvestable(boolean Harvestable) {
		this.Harvestable = Harvestable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiSysServicecompliance")
	public Set<SdiPhysicalserviceServicecompliance> getSdiPhysicalserviceServicecompliances() {
		return this.sdiPhysicalserviceServicecompliances;
	}

	public void setSdiPhysicalserviceServicecompliances(
			Set<SdiPhysicalserviceServicecompliance> sdiPhysicalserviceServicecompliances) {
		this.sdiPhysicalserviceServicecompliances = sdiPhysicalserviceServicecompliances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiSysServicecompliance")
	public Set<SdiVirtualserviceServicecompliance> getSdiVirtualserviceServicecompliances() {
		return this.sdiVirtualserviceServicecompliances;
	}

	public void setSdiVirtualserviceServicecompliances(
			Set<SdiVirtualserviceServicecompliance> sdiVirtualserviceServicecompliances) {
		this.sdiVirtualserviceServicecompliances = sdiVirtualserviceServicecompliances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiSysServicecompliance")
	public Set<SdiSysOperationcompliance> getSdiSysOperationcompliances() {
		return this.sdiSysOperationcompliances;
	}

	public void setSdiSysOperationcompliances(
			Set<SdiSysOperationcompliance> sdiSysOperationcompliances) {
		this.sdiSysOperationcompliances = sdiSysOperationcompliances;
	}

}
