package org.easysdi.proxy.domain;

// Generated Mar 28, 2013 4:35:10 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;

/**
 * SdiSysServiceconAuthenticationcon generated by hbm2java
 */
@Entity
public class SdiSysServiceconAuthenticationcon implements java.io.Serializable {

	private Integer Id;
	private int Serviceconnector_id;
	private int Authenticationconnector_id;

	public SdiSysServiceconAuthenticationcon() {
	}

	public SdiSysServiceconAuthenticationcon(int Serviceconnector_id,
			int Authenticationconnector_id) {
		this.Serviceconnector_id = Serviceconnector_id;
		this.Authenticationconnector_id = Authenticationconnector_id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "serviceconnector_id", nullable = false)
	public int getServiceconnector_id() {
		return this.Serviceconnector_id;
	}

	public void setServiceconnector_id(int Serviceconnector_id) {
		this.Serviceconnector_id = Serviceconnector_id;
	}

	@Column(name = "authenticationconnector_id", nullable = false)
	public int getAuthenticationconnector_id() {
		return this.Authenticationconnector_id;
	}

	public void setAuthenticationconnector_id(int Authenticationconnector_id) {
		this.Authenticationconnector_id = Authenticationconnector_id;
	}

}
