package org.easysdi.proxy.domain;

// Generated Mar 28, 2013 6:08:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * SdiTilematrixsetPolicy generated by hbm2java
 */
@Entity
public class SdiTilematrixsetPolicy implements java.io.Serializable {

	private Integer Id;
	private SdiWmtslayerPolicy sdiWmtslayerPolicy;
	private String Identifier;
	private boolean Anytilematrix;
	private String Srssource;
	private Set<SdiTilematrixPolicy> sdiTilematrixPolicies = new HashSet<SdiTilematrixPolicy>(
			0);

	public SdiTilematrixsetPolicy() {
	}

	public SdiTilematrixsetPolicy(SdiWmtslayerPolicy sdiWmtslayerPolicy,
			String Identifier, boolean Anytilematrix) {
		this.sdiWmtslayerPolicy = sdiWmtslayerPolicy;
		this.Identifier = Identifier;
		this.Anytilematrix = Anytilematrix;
	}

	public SdiTilematrixsetPolicy(SdiWmtslayerPolicy sdiWmtslayerPolicy,
			String Identifier, boolean Anytilematrix, String Srssource,
			Set<SdiTilematrixPolicy> sdiTilematrixPolicies) {
		this.sdiWmtslayerPolicy = sdiWmtslayerPolicy;
		this.Identifier = Identifier;
		this.Anytilematrix = Anytilematrix;
		this.Srssource = Srssource;
		this.sdiTilematrixPolicies = sdiTilematrixPolicies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "wmtslayerpolicy_id", nullable = false)
	public SdiWmtslayerPolicy getSdiWmtslayerPolicy() {
		return this.sdiWmtslayerPolicy;
	}

	public void setSdiWmtslayerPolicy(SdiWmtslayerPolicy sdiWmtslayerPolicy) {
		this.sdiWmtslayerPolicy = sdiWmtslayerPolicy;
	}

	@Column(name = "identifier", nullable = false)
	public String getIdentifier() {
		return this.Identifier;
	}

	public void setIdentifier(String Identifier) {
		this.Identifier = Identifier;
	}

	@Column(name = "anytilematrix", nullable = false)
	public boolean isAnytilematrix() {
		return this.Anytilematrix;
	}

	public void setAnytilematrix(boolean Anytilematrix) {
		this.Anytilematrix = Anytilematrix;
	}

	@Column(name = "srssource")
	public String getSrssource() {
		return this.Srssource;
	}

	public void setSrssource(String Srssource) {
		this.Srssource = Srssource;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiTilematrixsetPolicy")
	public Set<SdiTilematrixPolicy> getSdiTilematrixPolicies() {
		return this.sdiTilematrixPolicies;
	}

	public void setSdiTilematrixPolicies(
			Set<SdiTilematrixPolicy> sdiTilematrixPolicies) {
		this.sdiTilematrixPolicies = sdiTilematrixPolicies;
	}

}
