package org.easysdi.proxy.domain;

// Generated Mar 28, 2013 6:08:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SdiUser generated by hbm2java
 */
@Entity
@Cache (usage=CacheConcurrencyStrategy.READ_WRITE)
public class SdiUser implements java.io.Serializable {

	private Integer Id;
	private Users users;
	private String Guid;
	private int Created_by;
	private Date Created;
	private Integer Modified_by;
	private Date Modified;
	private Integer Ordering;
	private int State;
	private int Checked_out;
	private Date Checked_out_time;
	private String Description;
	private boolean Notificationrequesttreatment;
	private Integer Catid;
	private String Params;
	private int Access;
	private Integer Asset_id;
	private Set<SdiUserRoleOrganism> sdiUserRoleOrganisms = new HashSet<SdiUserRoleOrganism>(
			0);
	private Set<SdiPolicyUser> sdiPolicyUsers = new HashSet<SdiPolicyUser>(0);

	public SdiUser() {
	}

	public SdiUser(Users users, String Guid, int Created_by, Date Created,
			int State, int Checked_out, Date Checked_out_time,
			boolean Notificationrequesttreatment, int Access) {
		this.users = users;
		this.Guid = Guid;
		this.Created_by = Created_by;
		this.Created = Created;
		this.State = State;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Notificationrequesttreatment = Notificationrequesttreatment;
		this.Access = Access;
	}

	public SdiUser(Users users, String Guid, int Created_by, Date Created,
			Integer Modified_by, Date Modified, Integer Ordering, int State,
			int Checked_out, Date Checked_out_time, String Description,
			boolean Notificationrequesttreatment, Integer Catid, String Params,
			int Access, Integer Asset_id,
			Set<SdiUserRoleOrganism> sdiUserRoleOrganisms,
			Set<SdiPolicyUser> sdiPolicyUsers) {
		this.users = users;
		this.Guid = Guid;
		this.Created_by = Created_by;
		this.Created = Created;
		this.Modified_by = Modified_by;
		this.Modified = Modified;
		this.Ordering = Ordering;
		this.State = State;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Description = Description;
		this.Notificationrequesttreatment = Notificationrequesttreatment;
		this.Catid = Catid;
		this.Params = Params;
		this.Access = Access;
		this.Asset_id = Asset_id;
		this.sdiUserRoleOrganisms = sdiUserRoleOrganisms;
		this.sdiPolicyUsers = sdiPolicyUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "guid", nullable = false, length = 36)
	public String getGuid() {
		return this.Guid;
	}

	public void setGuid(String Guid) {
		this.Guid = Guid;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreated_by() {
		return this.Created_by;
	}

	public void setCreated_by(int Created_by) {
		this.Created_by = Created_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.Created;
	}

	public void setCreated(Date Created) {
		this.Created = Created;
	}

	@Column(name = "modified_by")
	public Integer getModified_by() {
		return this.Modified_by;
	}

	public void setModified_by(Integer Modified_by) {
		this.Modified_by = Modified_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 19)
	public Date getModified() {
		return this.Modified;
	}

	public void setModified(Date Modified) {
		this.Modified = Modified;
	}

	@Column(name = "ordering")
	public Integer getOrdering() {
		return this.Ordering;
	}

	public void setOrdering(Integer Ordering) {
		this.Ordering = Ordering;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.State;
	}

	public void setState(int State) {
		this.State = State;
	}

	@Column(name = "checked_out", nullable = false)
	public int getChecked_out() {
		return this.Checked_out;
	}

	public void setChecked_out(int Checked_out) {
		this.Checked_out = Checked_out;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checked_out_time", nullable = false, length = 19)
	public Date getChecked_out_time() {
		return this.Checked_out_time;
	}

	public void setChecked_out_time(Date Checked_out_time) {
		this.Checked_out_time = Checked_out_time;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.Description;
	}

	public void setDescription(String Description) {
		this.Description = Description;
	}

	@Column(name = "notificationrequesttreatment", nullable = false)
	public boolean isNotificationrequesttreatment() {
		return this.Notificationrequesttreatment;
	}

	public void setNotificationrequesttreatment(
			boolean Notificationrequesttreatment) {
		this.Notificationrequesttreatment = Notificationrequesttreatment;
	}

	@Column(name = "catid")
	public Integer getCatid() {
		return this.Catid;
	}

	public void setCatid(Integer Catid) {
		this.Catid = Catid;
	}

	@Column(name = "params", length = 1024)
	public String getParams() {
		return this.Params;
	}

	public void setParams(String Params) {
		this.Params = Params;
	}

	@Column(name = "access", nullable = false)
	public int getAccess() {
		return this.Access;
	}

	public void setAccess(int Access) {
		this.Access = Access;
	}

	@Column(name = "asset_id")
	public Integer getAsset_id() {
		return this.Asset_id;
	}

	public void setAsset_id(Integer Asset_id) {
		this.Asset_id = Asset_id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiUser")
	public Set<SdiUserRoleOrganism> getSdiUserRoleOrganisms() {
		return this.sdiUserRoleOrganisms;
	}

	public void setSdiUserRoleOrganisms(
			Set<SdiUserRoleOrganism> sdiUserRoleOrganisms) {
		this.sdiUserRoleOrganisms = sdiUserRoleOrganisms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiUser")
	public Set<SdiPolicyUser> getSdiPolicyUsers() {
		return this.sdiPolicyUsers;
	}

	public void setSdiPolicyUsers(Set<SdiPolicyUser> sdiPolicyUsers) {
		this.sdiPolicyUsers = sdiPolicyUsers;
	}

}
