package org.easysdi.proxy.domain;

// Generated Mar 28, 2013 6:08:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SdiVirtualmetadata generated by hbm2java
 */
@Entity
public class SdiVirtualmetadata implements java.io.Serializable {

	private Integer Id;
	private SdiVirtualservice sdiVirtualservice;
	private SdiSysCountry sdiSysCountry;
	private String Guid;
	private int Ordering;
	private int State;
	private int Checked_out;
	private Date Checked_out_time;
	private int Created_by;
	private Date Created;
	private Integer Modified_by;
	private Date Modified;
	private String Title;
	private boolean Inheritedtitle;
	private String Summary;
	private boolean Inheritedsummary;
	private String Keyword;
	private boolean Inheritedkeyword;
	private String Fee;
	private boolean Inheritedfee;
	private String Accessconstraint;
	private boolean Inheritedaccessconstraint;
	private boolean Inheritedcontact;
	private String Contactorganization;
	private String Contactname;
	private String Contactposition;
	private String Contactadress;
	private String Contactpostalcode;
	private String Contactlocality;
	private String Contactstate;
	private String Contactphone;
	private String Contactfax;
	private String Contactemail;
	private String Contacturl;
	private String Contactavailability;
	private String Contactinstruction;

	public SdiVirtualmetadata() {
	}

	public SdiVirtualmetadata(SdiVirtualservice sdiVirtualservice, String Guid,
			int Ordering, int State, int Checked_out, Date Checked_out_time,
			int Created_by, Date Created, boolean Inheritedtitle,
			boolean Inheritedsummary, boolean Inheritedkeyword,
			boolean Inheritedfee, boolean Inheritedaccessconstraint,
			boolean Inheritedcontact) {
		this.sdiVirtualservice = sdiVirtualservice;
		this.Guid = Guid;
		this.Ordering = Ordering;
		this.State = State;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Created_by = Created_by;
		this.Created = Created;
		this.Inheritedtitle = Inheritedtitle;
		this.Inheritedsummary = Inheritedsummary;
		this.Inheritedkeyword = Inheritedkeyword;
		this.Inheritedfee = Inheritedfee;
		this.Inheritedaccessconstraint = Inheritedaccessconstraint;
		this.Inheritedcontact = Inheritedcontact;
	}

	public SdiVirtualmetadata(SdiVirtualservice sdiVirtualservice,
			SdiSysCountry sdiSysCountry, String Guid, int Ordering, int State,
			int Checked_out, Date Checked_out_time, int Created_by,
			Date Created, Integer Modified_by, Date Modified, String Title,
			boolean Inheritedtitle, String Summary, boolean Inheritedsummary,
			String Keyword, boolean Inheritedkeyword, String Fee,
			boolean Inheritedfee, String Accessconstraint,
			boolean Inheritedaccessconstraint, boolean Inheritedcontact,
			String Contactorganization, String Contactname,
			String Contactposition, String Contactadress,
			String Contactpostalcode, String Contactlocality,
			String Contactstate, String Contactphone, String Contactfax,
			String Contactemail, String Contacturl, String Contactavailability,
			String Contactinstruction) {
		this.sdiVirtualservice = sdiVirtualservice;
		this.sdiSysCountry = sdiSysCountry;
		this.Guid = Guid;
		this.Ordering = Ordering;
		this.State = State;
		this.Checked_out = Checked_out;
		this.Checked_out_time = Checked_out_time;
		this.Created_by = Created_by;
		this.Created = Created;
		this.Modified_by = Modified_by;
		this.Modified = Modified;
		this.Title = Title;
		this.Inheritedtitle = Inheritedtitle;
		this.Summary = Summary;
		this.Inheritedsummary = Inheritedsummary;
		this.Keyword = Keyword;
		this.Inheritedkeyword = Inheritedkeyword;
		this.Fee = Fee;
		this.Inheritedfee = Inheritedfee;
		this.Accessconstraint = Accessconstraint;
		this.Inheritedaccessconstraint = Inheritedaccessconstraint;
		this.Inheritedcontact = Inheritedcontact;
		this.Contactorganization = Contactorganization;
		this.Contactname = Contactname;
		this.Contactposition = Contactposition;
		this.Contactadress = Contactadress;
		this.Contactpostalcode = Contactpostalcode;
		this.Contactlocality = Contactlocality;
		this.Contactstate = Contactstate;
		this.Contactphone = Contactphone;
		this.Contactfax = Contactfax;
		this.Contactemail = Contactemail;
		this.Contacturl = Contacturl;
		this.Contactavailability = Contactavailability;
		this.Contactinstruction = Contactinstruction;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "virtualservice_id", nullable = false)
	public SdiVirtualservice getSdiVirtualservice() {
		return this.sdiVirtualservice;
	}

	public void setSdiVirtualservice(SdiVirtualservice sdiVirtualservice) {
		this.sdiVirtualservice = sdiVirtualservice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_id")
	public SdiSysCountry getSdiSysCountry() {
		return this.sdiSysCountry;
	}

	public void setSdiSysCountry(SdiSysCountry sdiSysCountry) {
		this.sdiSysCountry = sdiSysCountry;
	}

	@Column(name = "guid", nullable = false, length = 36)
	public String getGuid() {
		return this.Guid;
	}

	public void setGuid(String Guid) {
		this.Guid = Guid;
	}

	@Column(name = "ordering", nullable = false)
	public int getOrdering() {
		return this.Ordering;
	}

	public void setOrdering(int Ordering) {
		this.Ordering = Ordering;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.State;
	}

	public void setState(int State) {
		this.State = State;
	}

	@Column(name = "checked_out", nullable = false)
	public int getChecked_out() {
		return this.Checked_out;
	}

	public void setChecked_out(int Checked_out) {
		this.Checked_out = Checked_out;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checked_out_time", nullable = false, length = 19)
	public Date getChecked_out_time() {
		return this.Checked_out_time;
	}

	public void setChecked_out_time(Date Checked_out_time) {
		this.Checked_out_time = Checked_out_time;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreated_by() {
		return this.Created_by;
	}

	public void setCreated_by(int Created_by) {
		this.Created_by = Created_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.Created;
	}

	public void setCreated(Date Created) {
		this.Created = Created;
	}

	@Column(name = "modified_by")
	public Integer getModified_by() {
		return this.Modified_by;
	}

	public void setModified_by(Integer Modified_by) {
		this.Modified_by = Modified_by;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 19)
	public Date getModified() {
		return this.Modified;
	}

	public void setModified(Date Modified) {
		this.Modified = Modified;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.Title;
	}

	public void setTitle(String Title) {
		this.Title = Title;
	}

	@Column(name = "inheritedtitle", nullable = false)
	public boolean isInheritedtitle() {
		return this.Inheritedtitle;
	}

	public void setInheritedtitle(boolean Inheritedtitle) {
		this.Inheritedtitle = Inheritedtitle;
	}

	@Column(name = "summary")
	public String getSummary() {
		return this.Summary;
	}

	public void setSummary(String Summary) {
		this.Summary = Summary;
	}

	@Column(name = "inheritedsummary", nullable = false)
	public boolean isInheritedsummary() {
		return this.Inheritedsummary;
	}

	public void setInheritedsummary(boolean Inheritedsummary) {
		this.Inheritedsummary = Inheritedsummary;
	}

	@Column(name = "keyword")
	public String getKeyword() {
		return this.Keyword;
	}

	public void setKeyword(String Keyword) {
		this.Keyword = Keyword;
	}

	@Column(name = "inheritedkeyword", nullable = false)
	public boolean isInheritedkeyword() {
		return this.Inheritedkeyword;
	}

	public void setInheritedkeyword(boolean Inheritedkeyword) {
		this.Inheritedkeyword = Inheritedkeyword;
	}

	@Column(name = "fee")
	public String getFee() {
		return this.Fee;
	}

	public void setFee(String Fee) {
		this.Fee = Fee;
	}

	@Column(name = "inheritedfee", nullable = false)
	public boolean isInheritedfee() {
		return this.Inheritedfee;
	}

	public void setInheritedfee(boolean Inheritedfee) {
		this.Inheritedfee = Inheritedfee;
	}

	@Column(name = "accessconstraint")
	public String getAccessconstraint() {
		return this.Accessconstraint;
	}

	public void setAccessconstraint(String Accessconstraint) {
		this.Accessconstraint = Accessconstraint;
	}

	@Column(name = "inheritedaccessconstraint", nullable = false)
	public boolean isInheritedaccessconstraint() {
		return this.Inheritedaccessconstraint;
	}

	public void setInheritedaccessconstraint(boolean Inheritedaccessconstraint) {
		this.Inheritedaccessconstraint = Inheritedaccessconstraint;
	}

	@Column(name = "inheritedcontact", nullable = false)
	public boolean isInheritedcontact() {
		return this.Inheritedcontact;
	}

	public void setInheritedcontact(boolean Inheritedcontact) {
		this.Inheritedcontact = Inheritedcontact;
	}

	@Column(name = "contactorganization")
	public String getContactorganization() {
		return this.Contactorganization;
	}

	public void setContactorganization(String Contactorganization) {
		this.Contactorganization = Contactorganization;
	}

	@Column(name = "contactname")
	public String getContactname() {
		return this.Contactname;
	}

	public void setContactname(String Contactname) {
		this.Contactname = Contactname;
	}

	@Column(name = "contactposition")
	public String getContactposition() {
		return this.Contactposition;
	}

	public void setContactposition(String Contactposition) {
		this.Contactposition = Contactposition;
	}

	@Column(name = "contactadress")
	public String getContactadress() {
		return this.Contactadress;
	}

	public void setContactadress(String Contactadress) {
		this.Contactadress = Contactadress;
	}

	@Column(name = "contactpostalcode")
	public String getContactpostalcode() {
		return this.Contactpostalcode;
	}

	public void setContactpostalcode(String Contactpostalcode) {
		this.Contactpostalcode = Contactpostalcode;
	}

	@Column(name = "contactlocality")
	public String getContactlocality() {
		return this.Contactlocality;
	}

	public void setContactlocality(String Contactlocality) {
		this.Contactlocality = Contactlocality;
	}

	@Column(name = "contactstate")
	public String getContactstate() {
		return this.Contactstate;
	}

	public void setContactstate(String Contactstate) {
		this.Contactstate = Contactstate;
	}

	@Column(name = "contactphone")
	public String getContactphone() {
		return this.Contactphone;
	}

	public void setContactphone(String Contactphone) {
		this.Contactphone = Contactphone;
	}

	@Column(name = "contactfax")
	public String getContactfax() {
		return this.Contactfax;
	}

	public void setContactfax(String Contactfax) {
		this.Contactfax = Contactfax;
	}

	@Column(name = "contactemail")
	public String getContactemail() {
		return this.Contactemail;
	}

	public void setContactemail(String Contactemail) {
		this.Contactemail = Contactemail;
	}

	@Column(name = "contacturl")
	public String getContacturl() {
		return this.Contacturl;
	}

	public void setContacturl(String Contacturl) {
		this.Contacturl = Contacturl;
	}

	@Column(name = "contactavailability")
	public String getContactavailability() {
		return this.Contactavailability;
	}

	public void setContactavailability(String Contactavailability) {
		this.Contactavailability = Contactavailability;
	}

	@Column(name = "contactinstruction")
	public String getContactinstruction() {
		return this.Contactinstruction;
	}

	public void setContactinstruction(String Contactinstruction) {
		this.Contactinstruction = Contactinstruction;
	}

}
