package org.easysdi.proxy.domain;

// Generated Apr 9, 2013 11:54:41 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Immutable;

/**
 * SdiWmtsSpatialpolicy generated by hbm2java
 */
@Entity
@Immutable
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
public class SdiWmtsSpatialpolicy implements java.io.Serializable {

	private static final long serialVersionUID = 8455203134703753668L;
	private Integer Id;
	private SdiSysSpatialoperator sdiSysSpatialoperator;
	private BigDecimal Eastboundlongitude;
	private BigDecimal Westboundlongitude;
	private BigDecimal Northboundlatitude;
	private BigDecimal Southboundlatitude;
	private Set<SdiPolicy> sdiPolicies = new HashSet<SdiPolicy>(0);
	private Set<SdiPhysicalservicePolicy> sdiPhysicalservicePolicies = new HashSet<SdiPhysicalservicePolicy>(
			0);
	private Set<SdiWmtslayerPolicy> sdiWmtslayerPolicies = new HashSet<SdiWmtslayerPolicy>(
			0);

	public SdiWmtsSpatialpolicy() {
	}

	public SdiWmtsSpatialpolicy(SdiSysSpatialoperator sdiSysSpatialoperator) {
		this.sdiSysSpatialoperator = sdiSysSpatialoperator;
	}

	public SdiWmtsSpatialpolicy(SdiSysSpatialoperator sdiSysSpatialoperator,
			BigDecimal Eastboundlongitude, BigDecimal Westboundlongitude,
			BigDecimal Northboundlatitude, BigDecimal Southboundlatitude,
			Set<SdiPolicy> sdiPolicies,
			Set<SdiPhysicalservicePolicy> sdiPhysicalservicePolicies,
			Set<SdiWmtslayerPolicy> sdiWmtslayerPolicies) {
		this.sdiSysSpatialoperator = sdiSysSpatialoperator;
		this.Eastboundlongitude = Eastboundlongitude;
		this.Westboundlongitude = Westboundlongitude;
		this.Northboundlatitude = Northboundlatitude;
		this.Southboundlatitude = Southboundlatitude;
		this.sdiPolicies = sdiPolicies;
		this.sdiPhysicalservicePolicies = sdiPhysicalservicePolicies;
		this.sdiWmtslayerPolicies = sdiWmtslayerPolicies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "spatialoperator_id", nullable = false)
	public SdiSysSpatialoperator getSdiSysSpatialoperator() {
		return this.sdiSysSpatialoperator;
	}

	public void setSdiSysSpatialoperator(
			SdiSysSpatialoperator sdiSysSpatialoperator) {
		this.sdiSysSpatialoperator = sdiSysSpatialoperator;
	}

	@Column(name = "eastboundlongitude", precision = 10, scale = 6)
	public BigDecimal getEastboundlongitude() {
		return this.Eastboundlongitude;
	}

	public void setEastboundlongitude(BigDecimal Eastboundlongitude) {
		this.Eastboundlongitude = Eastboundlongitude;
	}

	@Column(name = "westboundlongitude", precision = 10, scale = 6)
	public BigDecimal getWestboundlongitude() {
		return this.Westboundlongitude;
	}

	public void setWestboundlongitude(BigDecimal Westboundlongitude) {
		this.Westboundlongitude = Westboundlongitude;
	}

	@Column(name = "northboundlatitude", precision = 10, scale = 6)
	public BigDecimal getNorthboundlatitude() {
		return this.Northboundlatitude;
	}

	public void setNorthboundlatitude(BigDecimal Northboundlatitude) {
		this.Northboundlatitude = Northboundlatitude;
	}

	@Column(name = "southboundlatitude", precision = 10, scale = 6)
	public BigDecimal getSouthboundlatitude() {
		return this.Southboundlatitude;
	}

	public void setSouthboundlatitude(BigDecimal Southboundlatitude) {
		this.Southboundlatitude = Southboundlatitude;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiWmtsSpatialpolicy")
	public Set<SdiPolicy> getSdiPolicies() {
		return this.sdiPolicies;
	}

	public void setSdiPolicies(Set<SdiPolicy> sdiPolicies) {
		this.sdiPolicies = sdiPolicies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiWmtsSpatialpolicy")
	public Set<SdiPhysicalservicePolicy> getSdiPhysicalservicePolicies() {
		return this.sdiPhysicalservicePolicies;
	}

	public void setSdiPhysicalservicePolicies(
			Set<SdiPhysicalservicePolicy> sdiPhysicalservicePolicies) {
		this.sdiPhysicalservicePolicies = sdiPhysicalservicePolicies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiWmtsSpatialpolicy")
	public Set<SdiWmtslayerPolicy> getSdiWmtslayerPolicies() {
		return this.sdiWmtslayerPolicies;
	}

	public void setSdiWmtslayerPolicies(
			Set<SdiWmtslayerPolicy> sdiWmtslayerPolicies) {
		this.sdiWmtslayerPolicies = sdiWmtslayerPolicies;
	}

}
