package org.easysdi.proxy.domain;

// Generated Mar 28, 2013 4:35:10 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;

/**
 * SdiWmtsSpatialpolicy generated by hbm2java
 */
@Entity
public class SdiWmtsSpatialpolicy implements java.io.Serializable {

	private Integer Id;
	private int Spatialoperator_id;
	private BigDecimal Eastboundlongitude;
	private BigDecimal Westboundlongitude;
	private BigDecimal Northboundlatitude;
	private BigDecimal Southboundlatitude;

	public SdiWmtsSpatialpolicy() {
	}

	public SdiWmtsSpatialpolicy(int Spatialoperator_id) {
		this.Spatialoperator_id = Spatialoperator_id;
	}

	public SdiWmtsSpatialpolicy(int Spatialoperator_id,
			BigDecimal Eastboundlongitude, BigDecimal Westboundlongitude,
			BigDecimal Northboundlatitude, BigDecimal Southboundlatitude) {
		this.Spatialoperator_id = Spatialoperator_id;
		this.Eastboundlongitude = Eastboundlongitude;
		this.Westboundlongitude = Westboundlongitude;
		this.Northboundlatitude = Northboundlatitude;
		this.Southboundlatitude = Southboundlatitude;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "spatialoperator_id", nullable = false)
	public int getSpatialoperator_id() {
		return this.Spatialoperator_id;
	}

	public void setSpatialoperator_id(int Spatialoperator_id) {
		this.Spatialoperator_id = Spatialoperator_id;
	}

	@Column(name = "eastboundlongitude", precision = 10, scale = 6)
	public BigDecimal getEastboundlongitude() {
		return this.Eastboundlongitude;
	}

	public void setEastboundlongitude(BigDecimal Eastboundlongitude) {
		this.Eastboundlongitude = Eastboundlongitude;
	}

	@Column(name = "westboundlongitude", precision = 10, scale = 6)
	public BigDecimal getWestboundlongitude() {
		return this.Westboundlongitude;
	}

	public void setWestboundlongitude(BigDecimal Westboundlongitude) {
		this.Westboundlongitude = Westboundlongitude;
	}

	@Column(name = "northboundlatitude", precision = 10, scale = 6)
	public BigDecimal getNorthboundlatitude() {
		return this.Northboundlatitude;
	}

	public void setNorthboundlatitude(BigDecimal Northboundlatitude) {
		this.Northboundlatitude = Northboundlatitude;
	}

	@Column(name = "southboundlatitude", precision = 10, scale = 6)
	public BigDecimal getSouthboundlatitude() {
		return this.Southboundlatitude;
	}

	public void setSouthboundlatitude(BigDecimal Southboundlatitude) {
		this.Southboundlatitude = Southboundlatitude;
	}

}
