package org.easysdi.proxy.domain;

// Generated Mar 28, 2013 4:35:10 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;

/**
 * SdiWmtslayerPolicy generated by hbm2java
 */
@Entity
public class SdiWmtslayerPolicy implements java.io.Serializable {

	private Integer Id;
	private String Identifier;
	private boolean Enabled;
	private boolean Inheritedspatialpolicy;
	private Integer Spatialpolicy_id;
	private boolean Anytilematrixset;
	private int Physicalservicepolicy_id;

	public SdiWmtslayerPolicy() {
	}

	public SdiWmtslayerPolicy(String Identifier, boolean Enabled,
			boolean Inheritedspatialpolicy, boolean Anytilematrixset,
			int Physicalservicepolicy_id) {
		this.Identifier = Identifier;
		this.Enabled = Enabled;
		this.Inheritedspatialpolicy = Inheritedspatialpolicy;
		this.Anytilematrixset = Anytilematrixset;
		this.Physicalservicepolicy_id = Physicalservicepolicy_id;
	}

	public SdiWmtslayerPolicy(String Identifier, boolean Enabled,
			boolean Inheritedspatialpolicy, Integer Spatialpolicy_id,
			boolean Anytilematrixset, int Physicalservicepolicy_id) {
		this.Identifier = Identifier;
		this.Enabled = Enabled;
		this.Inheritedspatialpolicy = Inheritedspatialpolicy;
		this.Spatialpolicy_id = Spatialpolicy_id;
		this.Anytilematrixset = Anytilematrixset;
		this.Physicalservicepolicy_id = Physicalservicepolicy_id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "identifier", nullable = false)
	public String getIdentifier() {
		return this.Identifier;
	}

	public void setIdentifier(String Identifier) {
		this.Identifier = Identifier;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.Enabled;
	}

	public void setEnabled(boolean Enabled) {
		this.Enabled = Enabled;
	}

	@Column(name = "inheritedspatialpolicy", nullable = false)
	public boolean isInheritedspatialpolicy() {
		return this.Inheritedspatialpolicy;
	}

	public void setInheritedspatialpolicy(boolean Inheritedspatialpolicy) {
		this.Inheritedspatialpolicy = Inheritedspatialpolicy;
	}

	@Column(name = "spatialpolicy_id")
	public Integer getSpatialpolicy_id() {
		return this.Spatialpolicy_id;
	}

	public void setSpatialpolicy_id(Integer Spatialpolicy_id) {
		this.Spatialpolicy_id = Spatialpolicy_id;
	}

	@Column(name = "anytilematrixset", nullable = false)
	public boolean isAnytilematrixset() {
		return this.Anytilematrixset;
	}

	public void setAnytilematrixset(boolean Anytilematrixset) {
		this.Anytilematrixset = Anytilematrixset;
	}

	@Column(name = "physicalservicepolicy_id", nullable = false)
	public int getPhysicalservicepolicy_id() {
		return this.Physicalservicepolicy_id;
	}

	public void setPhysicalservicepolicy_id(int Physicalservicepolicy_id) {
		this.Physicalservicepolicy_id = Physicalservicepolicy_id;
	}

}
