package org.easysdi.proxy.domain;

// Generated Apr 9, 2013 11:54:41 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SdiWmslayerPolicy generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
public class SdiWmslayerPolicy implements java.io.Serializable {

	private static final long serialVersionUID = 1270331377106612332L;
	private Integer Id;
	private SdiWmsSpatialpolicy sdiWmsSpatialpolicy;
	private SdiPhysicalservicePolicy sdiPhysicalservicePolicy;
	private String Name;
	private String Description;
	private boolean Enabled;
	private boolean Inheritedspatialpolicy;

	public SdiWmslayerPolicy() {
	}

	public SdiWmslayerPolicy(SdiPhysicalservicePolicy sdiPhysicalservicePolicy,
			String Name, String Description, boolean Enabled,
			boolean Inheritedspatialpolicy) {
		this.sdiPhysicalservicePolicy = sdiPhysicalservicePolicy;
		this.Name = Name;
		this.Description = Description;
		this.Enabled = Enabled;
		this.Inheritedspatialpolicy = Inheritedspatialpolicy;
	}

	public SdiWmslayerPolicy(SdiWmsSpatialpolicy sdiWmsSpatialpolicy,
			SdiPhysicalservicePolicy sdiPhysicalservicePolicy, String Name,
			String Description, boolean Enabled, boolean Inheritedspatialpolicy) {
		this.sdiWmsSpatialpolicy = sdiWmsSpatialpolicy;
		this.sdiPhysicalservicePolicy = sdiPhysicalservicePolicy;
		this.Name = Name;
		this.Description = Description;
		this.Enabled = Enabled;
		this.Inheritedspatialpolicy = Inheritedspatialpolicy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "spatialpolicy_id")
	public SdiWmsSpatialpolicy getSdiWmsSpatialpolicy() {
		if(this.sdiWmsSpatialpolicy == null)
		{
			if(this.getSdiPhysicalservicePolicy().getSdiWmsSpatialpolicy()==null)
			{
				if(this.getSdiPhysicalservicePolicy().getSdiPolicy().getSdiWmsSpatialpolicy()!= null)
					return this.getSdiPhysicalservicePolicy().getSdiPolicy().getSdiWmsSpatialpolicy();
			}
			else
			{
				return this.getSdiPhysicalservicePolicy().getSdiWmsSpatialpolicy();
			}
		}
		return this.sdiWmsSpatialpolicy;
	}

	public void setSdiWmsSpatialpolicy(SdiWmsSpatialpolicy sdiWmsSpatialpolicy) {
		this.sdiWmsSpatialpolicy = sdiWmsSpatialpolicy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "physicalservicepolicy_id", nullable = false)
	public SdiPhysicalservicePolicy getSdiPhysicalservicePolicy() {
		return this.sdiPhysicalservicePolicy;
	}

	public void setSdiPhysicalservicePolicy(
			SdiPhysicalservicePolicy sdiPhysicalservicePolicy) {
		this.sdiPhysicalservicePolicy = sdiPhysicalservicePolicy;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.Description;
	}

	public void setDescription(String Description) {
		this.Description = Description;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.Enabled;
	}

	public void setEnabled(boolean Enabled) {
		this.Enabled = Enabled;
	}

	@Column(name = "inheritedspatialpolicy", nullable = false)
	public boolean isInheritedspatialpolicy() {
		return this.Inheritedspatialpolicy;
	}

	public void setInheritedspatialpolicy(boolean Inheritedspatialpolicy) {
		this.Inheritedspatialpolicy = Inheritedspatialpolicy;
	}

}
