package org.easysdi.proxy.domain;

// Generated Apr 9, 2013 11:54:41 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SdiWmsSpatialpolicy generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
public class SdiWmsSpatialpolicy implements java.io.Serializable {

	private Integer Id;
	private BigDecimal Maxx;
	private BigDecimal Maxy;
	private BigDecimal Minx;
	private BigDecimal Miny;
	private String Geographicfilter;
	private Integer Maximumscale;
	private Integer Minimumscale;
	private String Srssource;
	private Set<SdiWmslayerPolicy> sdiWmslayerPolicies = new HashSet<SdiWmslayerPolicy>(
			0);
	private Set<SdiPolicy> sdiPolicies = new HashSet<SdiPolicy>(0);
	private Set<SdiPhysicalservicePolicy> sdiPhysicalservicePolicies = new HashSet<SdiPhysicalservicePolicy>(
			0);

	public SdiWmsSpatialpolicy() {
	}

	public SdiWmsSpatialpolicy(BigDecimal Maxx, BigDecimal Maxy,
			BigDecimal Minx, BigDecimal Miny, String Geographicfilter,
			Integer Maximumscale, Integer Minimumscale, String Srssource,
			Set<SdiWmslayerPolicy> sdiWmslayerPolicies,
			Set<SdiPolicy> sdiPolicies,
			Set<SdiPhysicalservicePolicy> sdiPhysicalservicePolicies) {
		this.Maxx = Maxx;
		this.Maxy = Maxy;
		this.Minx = Minx;
		this.Miny = Miny;
		this.Geographicfilter = Geographicfilter;
		this.Maximumscale = Maximumscale;
		this.Minimumscale = Minimumscale;
		this.Srssource = Srssource;
		this.sdiWmslayerPolicies = sdiWmslayerPolicies;
		this.sdiPolicies = sdiPolicies;
		this.sdiPhysicalservicePolicies = sdiPhysicalservicePolicies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "maxx", precision = 18, scale = 6)
	public BigDecimal getMaxx() {
		return this.Maxx;
	}

	public void setMaxx(BigDecimal Maxx) {
		this.Maxx = Maxx;
	}

	@Column(name = "maxy", precision = 18, scale = 6)
	public BigDecimal getMaxy() {
		return this.Maxy;
	}

	public void setMaxy(BigDecimal Maxy) {
		this.Maxy = Maxy;
	}

	@Column(name = "minx", precision = 18, scale = 6)
	public BigDecimal getMinx() {
		return this.Minx;
	}

	public void setMinx(BigDecimal Minx) {
		this.Minx = Minx;
	}

	@Column(name = "miny", precision = 18, scale = 6)
	public BigDecimal getMiny() {
		return this.Miny;
	}

	public void setMiny(BigDecimal Miny) {
		this.Miny = Miny;
	}

	@Column(name = "geographicfilter", length = 65535)
	public String getGeographicfilter() {
		return this.Geographicfilter;
	}

	public void setGeographicfilter(String Geographicfilter) {
		this.Geographicfilter = Geographicfilter;
	}

	@Column(name = "maximumscale")
	public Integer getMaximumscale() {
		return this.Maximumscale;
	}

	public void setMaximumscale(Integer Maximumscale) {
		this.Maximumscale = Maximumscale;
	}

	@Column(name = "minimumscale")
	public Integer getMinimumscale() {
		return this.Minimumscale;
	}

	public void setMinimumscale(Integer Minimumscale) {
		this.Minimumscale = Minimumscale;
	}

	@Column(name = "srssource")
	public String getSrssource() {
		return this.Srssource;
	}

	public void setSrssource(String Srssource) {
		this.Srssource = Srssource;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiWmsSpatialpolicy")
	public Set<SdiWmslayerPolicy> getSdiWmslayerPolicies() {
		return this.sdiWmslayerPolicies;
	}

	public void setSdiWmslayerPolicies(
			Set<SdiWmslayerPolicy> sdiWmslayerPolicies) {
		this.sdiWmslayerPolicies = sdiWmslayerPolicies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiWmsSpatialpolicy")
	public Set<SdiPolicy> getSdiPolicies() {
		return this.sdiPolicies;
	}

	public void setSdiPolicies(Set<SdiPolicy> sdiPolicies) {
		this.sdiPolicies = sdiPolicies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdiWmsSpatialpolicy")
	public Set<SdiPhysicalservicePolicy> getSdiPhysicalservicePolicies() {
		return this.sdiPhysicalservicePolicies;
	}

	public void setSdiPhysicalservicePolicies(
			Set<SdiPhysicalservicePolicy> sdiPhysicalservicePolicies) {
		this.sdiPhysicalservicePolicies = sdiPhysicalservicePolicies;
	}

}
