package org.easysdi.proxy.domain;

// Generated Apr 4, 2013 10:31:47 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
public class Users implements java.io.Serializable {

	private Integer Id;
	private String Name;
	private String Username;
	private String Email;
	private String Password;
	private byte Block;
	private Byte SendEmail;
	private Date RegisterDate;
	private Date LastvisitDate;
	private String Activation;
	private String Params;
	private Date LastResetTime;
	private int ResetCount;
	private Set<SdiUser> sdiUsers = new HashSet<SdiUser>(0);

	public Users() {
	}

	public Users(String Name, String Username, String Email, String Password,
			byte Block, Date RegisterDate, Date LastvisitDate,
			String Activation, String Params, Date LastResetTime, int ResetCount) {
		this.Name = Name;
		this.Username = Username;
		this.Email = Email;
		this.Password = Password;
		this.Block = Block;
		this.RegisterDate = RegisterDate;
		this.LastvisitDate = LastvisitDate;
		this.Activation = Activation;
		this.Params = Params;
		this.LastResetTime = LastResetTime;
		this.ResetCount = ResetCount;
	}

	public Users(String Name, String Username, String Email, String Password,
			byte Block, Byte SendEmail, Date RegisterDate, Date LastvisitDate,
			String Activation, String Params, Date LastResetTime,
			int ResetCount, Set<SdiUser> sdiUsers) {
		this.Name = Name;
		this.Username = Username;
		this.Email = Email;
		this.Password = Password;
		this.Block = Block;
		this.SendEmail = SendEmail;
		this.RegisterDate = RegisterDate;
		this.LastvisitDate = LastvisitDate;
		this.Activation = Activation;
		this.Params = Params;
		this.LastResetTime = LastResetTime;
		this.ResetCount = ResetCount;
		this.sdiUsers = sdiUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.Id;
	}

	public void setId(Integer Id) {
		this.Id = Id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}

	@Column(name = "username", nullable = false, length = 150)
	public String getUsername() {
		return this.Username;
	}

	public void setUsername(String Username) {
		this.Username = Username;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.Email;
	}

	public void setEmail(String Email) {
		this.Email = Email;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.Password;
	}

	public void setPassword(String Password) {
		this.Password = Password;
	}

	@Column(name = "block", nullable = false)
	public byte getBlock() {
		return this.Block;
	}

	public void setBlock(byte Block) {
		this.Block = Block;
	}

	@Column(name = "sendEmail")
	public Byte getSendEmail() {
		return this.SendEmail;
	}

	public void setSendEmail(Byte SendEmail) {
		this.SendEmail = SendEmail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "registerDate", nullable = false, length = 19)
	public Date getRegisterDate() {
		return this.RegisterDate;
	}

	public void setRegisterDate(Date RegisterDate) {
		this.RegisterDate = RegisterDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastvisitDate", nullable = false, length = 19)
	public Date getLastvisitDate() {
		return this.LastvisitDate;
	}

	public void setLastvisitDate(Date LastvisitDate) {
		this.LastvisitDate = LastvisitDate;
	}

	@Column(name = "activation", nullable = false, length = 100)
	public String getActivation() {
		return this.Activation;
	}

	public void setActivation(String Activation) {
		this.Activation = Activation;
	}

	@Column(name = "params", nullable = false, length = 65535)
	public String getParams() {
		return this.Params;
	}

	public void setParams(String Params) {
		this.Params = Params;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastResetTime", nullable = false, length = 19)
	public Date getLastResetTime() {
		return this.LastResetTime;
	}

	public void setLastResetTime(Date LastResetTime) {
		this.LastResetTime = LastResetTime;
	}

	@Column(name = "resetCount", nullable = false)
	public int getResetCount() {
		return this.ResetCount;
	}

	public void setResetCount(int ResetCount) {
		this.ResetCount = ResetCount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<SdiUser> getSdiUsers() {
		return this.sdiUsers;
	}

	public void setSdiUsers(Set<SdiUser> sdiUsers) {
		this.sdiUsers = sdiUsers;
	}

}
