

INSERT INTO `#__sdi_sys_civility` (ordering,state,checked_out,value) 
VALUES 
(1 ,1,0,'COM_EASYSDI_CORE_CIVILITY_MADAM'),
(2 ,1,0,'COM_EASYSDI_CORE_CIVILITY_MISTER'),
(3 ,1,0,'COM_EASYSDI_CORE_CIVILITY_MISS'),
(4 ,1,0,'COM_EASYSDI_CORE_CIVILITY_MASTER'),
(5 ,1,0,'COM_EASYSDI_CORE_CIVILITY_MISS_PRESIDENT'),
(6 ,1,0,'COM_EASYSDI_CORE_CIVILITY_MISTER_PRESIDENT'),
(7 ,1,0,'COM_EASYSDI_CORE_CIVILITY_MISS_PROPERTY_AGENT'),
(8 ,1,0,'COM_EASYSDI_CORE_CIVILITY_MISTER_PROPERTY_AGENT'),
(9 ,1,0,'COM_EASYSDI_CORE_CIVILITY_MISS_MISTER'),
(10,1,0,'COM_EASYSDI_CORE_CIVILITY_MADAMS'),
(11,1,0,'COM_EASYSDI_CORE_CIVILITY_MISTERS'),
(12,1,0,'COM_EASYSDI_CORE_CIVILITY_MISSES'),
(13,1,0,'COM_EASYSDI_CORE_CIVILITY_MASTERS'),
(14,1,0,'COM_EASYSDI_CORE_CIVILITY_MISS_MISTERS'),
(15,1,0,'COM_EASYSDI_CORE_CIVILITY_MISSES_MISTERS'),
(16,1,0,'COM_EASYSDI_CORE_CIVILITY_MADAM_MISTERS'),
(17,1,0,'COM_EASYSDI_CORE_CIVILITY_MADAMS_MISTER')
;

INSERT INTO `#__sdi_sys_addresstype` (ordering,state,checked_out,value) 
VALUES 
(1 ,1,0,'contact'),
(2 ,1,0,'billing'),
(3 ,1,0,'delivry')
;